#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ABP_FNFAL_AnimLayer

#include "Basic.hpp"

#include "ABP_Rifle_AnimLayerBase_classes.hpp"


namespace SDK
{

// AnimBlueprintGeneratedClass ABP_FNFAL_AnimLayer.ABP_FNFAL_AnimLayer_C
// 0x0000 (0xB0E0 - 0xB0E0)
class UABP_FNFAL_AnimLayer_C final : public UABP_Rifle_AnimLayerBase_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"ABP_FNFAL_AnimLayer_C">();
	}
	static class UABP_FNFAL_AnimLayer_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UABP_FNFAL_AnimLayer_C>();
	}
};
static_assert(alignof(UABP_FNFAL_AnimLayer_C) == 0x000010, "Wrong alignment on UABP_FNFAL_AnimLayer_C");
static_assert(sizeof(UABP_FNFAL_AnimLayer_C) == 0x00B0E0, "Wrong size on UABP_FNFAL_AnimLayer_C");

}

