#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ABP_GenericItem_AnimLayerBase

#include "Basic.hpp"

#include "ControlRig_structs.hpp"
#include "Engine_structs.hpp"
#include "AnimGraphRuntime_structs.hpp"
#include "GroundBranch_structs.hpp"
#include "GroundBranch_classes.hpp"
#include "CoreUObject_structs.hpp"


namespace SDK
{

// AnimBlueprintGeneratedClass ABP_GenericItem_AnimLayerBase.ABP_GenericItem_AnimLayerBase_C
// 0x7600 (0x80C0 - 0x0AC0)
class UABP_GenericItem_AnimLayerBase_C : public UGBCharAnimInstanceLayer
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0AC0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_49;                   // 0x0AC8(0x0080)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_48;                   // 0x0B48(0x0080)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_47;                   // 0x0BC8(0x0080)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_46;                   // 0x0C48(0x0080)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_45;                   // 0x0CC8(0x0080)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_44;                   // 0x0D48(0x0080)()
	struct FAnimNode_Root                         AnimGraphNode_Root_10;                             // 0x0DC8(0x0030)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_43;                   // 0x0DF8(0x0080)()
	struct FAnimNode_BlendListByBool              AnimGraphNode_BlendListByBool_9;                   // 0x0E78(0x00A0)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_42;                   // 0x0F18(0x0080)()
	struct FAnimNode_BlendListByEnum              AnimGraphNode_BlendListByEnum_6;                   // 0x0F98(0x00B0)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_41;                   // 0x1048(0x0080)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_40;                   // 0x10C8(0x0080)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_39;                   // 0x1148(0x0080)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_38;                   // 0x11C8(0x0080)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_37;                   // 0x1248(0x0080)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_36;                   // 0x12C8(0x0080)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_35;                   // 0x1348(0x0080)()
	struct FAnimNode_Root                         AnimGraphNode_Root_9;                              // 0x13C8(0x0030)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_34;                   // 0x13F8(0x0080)()
	struct FAnimNode_Root                         AnimGraphNode_Root_8;                              // 0x1478(0x0030)()
	struct FAnimNode_LinkedInputPose              AnimGraphNode_LinkedInputPose_3;                   // 0x14A8(0x0118)()
	struct FAnimNode_ControlRig                   AnimGraphNode_ControlRig_4;                        // 0x15C0(0x0368)()
	struct FAnimNode_Root                         AnimGraphNode_Root_7;                              // 0x1928(0x0030)()
	struct FAnimNode_LinkedInputPose              AnimGraphNode_LinkedInputPose_2;                   // 0x1958(0x0118)()
	struct FAnimNode_SaveCachedPose               AnimGraphNode_SaveCachedPose_5;                    // 0x1A70(0x0158)()
	struct FAnimNode_SaveCachedPose               AnimGraphNode_SaveCachedPose_4;                    // 0x1BC8(0x0158)()
	struct FAnimNode_UseCachedPose                AnimGraphNode_UseCachedPose_16;                    // 0x1D20(0x0028)()
	struct FAnimNode_ControlRig                   AnimGraphNode_ControlRig_3;                        // 0x1D48(0x0368)()
	struct FAnimNode_LayeredBoneBlend             AnimGraphNode_LayeredBoneBlend_4;                  // 0x20B0(0x00C0)()
	struct FAnimNode_SequenceEvaluator            AnimGraphNode_SequenceEvaluator_9;                 // 0x2170(0x0050)()
	struct FAnimNode_SequenceEvaluator            AnimGraphNode_SequenceEvaluator_8;                 // 0x21C0(0x0050)()
	struct FAnimNode_ApplyMeshSpaceAdditive       AnimGraphNode_ApplyMeshSpaceAdditive_2;            // 0x2210(0x00D0)()
	struct FAnimNode_ConvertLocalToComponentSpace AnimGraphNode_LocalToComponentSpace_7;             // 0x22E0(0x0020)()
	struct FAnimNode_CopyBone                     AnimGraphNode_CopyBone_20;                         // 0x2300(0x00F0)()
	struct FAnimNode_ConvertComponentToLocalSpace AnimGraphNode_ComponentToLocalSpace_7;             // 0x23F0(0x0020)()
	struct FAnimNode_ConvertLocalToComponentSpace AnimGraphNode_LocalToComponentSpace_6;             // 0x2410(0x0020)()
	struct FAnimNode_CopyBone                     AnimGraphNode_CopyBone_19;                         // 0x2430(0x00F0)()
	struct FAnimNode_CopyBone                     AnimGraphNode_CopyBone_18;                         // 0x2520(0x00F0)()
	struct FAnimNode_ConvertComponentToLocalSpace AnimGraphNode_ComponentToLocalSpace_6;             // 0x2610(0x0020)()
	struct FAnimNode_CopyBone                     AnimGraphNode_CopyBone_17;                         // 0x2630(0x00F0)()
	struct FAnimNode_CopyBone                     AnimGraphNode_CopyBone_16;                         // 0x2720(0x00F0)()
	struct FAnimNode_CopyBone                     AnimGraphNode_CopyBone_15;                         // 0x2810(0x00F0)()
	struct FAnimNode_CopyBone                     AnimGraphNode_CopyBone_14;                         // 0x2900(0x00F0)()
	struct FAnimNode_UseCachedPose                AnimGraphNode_UseCachedPose_15;                    // 0x29F0(0x0028)()
	struct FAnimNode_UseCachedPose                AnimGraphNode_UseCachedPose_14;                    // 0x2A18(0x0028)()
	struct FAnimNode_BlendListByBool              AnimGraphNode_BlendListByBool_8;                   // 0x2A40(0x00A0)()
	struct FAnimNode_Root                         AnimGraphNode_Root_6;                              // 0x2AE0(0x0030)()
	struct FAnimNode_RefPose                      AnimGraphNode_IdentityPose;                        // 0x2B10(0x0018)()
	struct FAnimNode_Root                         AnimGraphNode_Root_5;                              // 0x2B28(0x0030)()
	struct FAnimNode_LinkedInputPose              AnimGraphNode_LinkedInputPose_1;                   // 0x2B58(0x0118)()
	struct FAnimNode_SaveCachedPose               AnimGraphNode_SaveCachedPose_3;                    // 0x2C70(0x0158)()
	struct FAnimNode_UseCachedPose                AnimGraphNode_UseCachedPose_13;                    // 0x2DC8(0x0028)()
	struct FAnimNode_UseCachedPose                AnimGraphNode_UseCachedPose_12;                    // 0x2DF0(0x0028)()
	struct FAnimNode_ConvertComponentToLocalSpace AnimGraphNode_ComponentToLocalSpace_5;             // 0x2E18(0x0020)()
	struct FAnimNode_CopyBone                     AnimGraphNode_CopyBone_13;                         // 0x2E38(0x00F0)()
	struct FAnimNode_CopyBone                     AnimGraphNode_CopyBone_12;                         // 0x2F28(0x00F0)()
	struct FAnimNode_CopyBone                     AnimGraphNode_CopyBone_11;                         // 0x3018(0x00F0)()
	struct FAnimNode_BlendListByBool              AnimGraphNode_BlendListByBool_7;                   // 0x3108(0x00A0)()
	struct FAnimNode_SaveCachedPose               AnimGraphNode_SaveCachedPose_2;                    // 0x31A8(0x0158)()
	struct FAnimNode_BlendListByBool              AnimGraphNode_BlendListByBool_6;                   // 0x3300(0x00A0)()
	struct FAnimNode_TwoWayBlend                  AnimGraphNode_TwoWayBlend_8;                       // 0x33A0(0x00C8)()
	struct FAnimNode_RotationOffsetBlendSpace     AnimGraphNode_RotationOffsetBlendSpace_3;          // 0x3468(0x0190)()
	struct FAnimNode_RotationOffsetBlendSpace     AnimGraphNode_RotationOffsetBlendSpace_2;          // 0x35F8(0x0190)()
	struct FAnimNode_RotationOffsetBlendSpace     AnimGraphNode_RotationOffsetBlendSpace_1;          // 0x3788(0x0190)()
	struct FAnimNode_LayeredBoneBlend             AnimGraphNode_LayeredBoneBlend_3;                  // 0x3918(0x00C0)()
	struct FAnimNode_ConvertLocalToComponentSpace AnimGraphNode_LocalToComponentSpace_5;             // 0x39D8(0x0020)()
	struct FAnimNode_UseCachedPose                AnimGraphNode_UseCachedPose_11;                    // 0x39F8(0x0028)()
	struct FAnimNode_BlendListByBool              AnimGraphNode_BlendListByBool_5;                   // 0x3A20(0x00A0)()
	struct FAnimNode_UseCachedPose                AnimGraphNode_UseCachedPose_10;                    // 0x3AC0(0x0028)()
	struct FAnimNode_ConvertLocalToComponentSpace AnimGraphNode_LocalToComponentSpace_4;             // 0x3AE8(0x0020)()
	struct FAnimNode_CopyBone                     AnimGraphNode_CopyBone_10;                         // 0x3B08(0x00F0)()
	struct FAnimNode_CopyBone                     AnimGraphNode_CopyBone_9;                          // 0x3BF8(0x00F0)()
	struct FAnimNode_CopyBone                     AnimGraphNode_CopyBone_8;                          // 0x3CE8(0x00F0)()
	struct FAnimNode_ConvertComponentToLocalSpace AnimGraphNode_ComponentToLocalSpace_4;             // 0x3DD8(0x0020)()
	struct FAnimNode_UseCachedPose                AnimGraphNode_UseCachedPose_9;                     // 0x3DF8(0x0028)()
	struct FAnimNode_RotationOffsetBlendSpace     AnimGraphNode_RotationOffsetBlendSpace;            // 0x3E20(0x0190)()
	struct FAnimNode_UseCachedPose                AnimGraphNode_UseCachedPose_8;                     // 0x3FB0(0x0028)()
	struct FAnimNode_UseCachedPose                AnimGraphNode_UseCachedPose_7;                     // 0x3FD8(0x0028)()
	struct FAnimNode_ControlRig                   AnimGraphNode_ControlRig_2;                        // 0x4000(0x0368)()
	struct FAnimNode_LayeredBoneBlend             AnimGraphNode_LayeredBoneBlend_2;                  // 0x4368(0x00C0)()
	struct FAnimNode_UseCachedPose                AnimGraphNode_UseCachedPose_6;                     // 0x4428(0x0028)()
	struct FAnimNode_Root                         AnimGraphNode_Root_4;                              // 0x4450(0x0030)()
	struct FAnimNode_LinkedInputPose              AnimGraphNode_LinkedInputPose;                     // 0x4480(0x0118)()
	struct FAnimNode_SaveCachedPose               AnimGraphNode_SaveCachedPose_1;                    // 0x4598(0x0158)()
	struct FAnimNode_TwoWayBlend                  AnimGraphNode_TwoWayBlend_7;                       // 0x46F0(0x00C8)()
	struct FAnimNode_SequenceEvaluator            AnimGraphNode_SequenceEvaluator_7;                 // 0x47B8(0x0050)()
	struct FAnimNode_SequenceEvaluator            AnimGraphNode_SequenceEvaluator_6;                 // 0x4808(0x0050)()
	struct FAnimNode_ModifyCurve                  AnimGraphNode_ModifyCurve;                         // 0x4858(0x0058)()
	struct FAnimNode_BlendListByBool              AnimGraphNode_BlendListByBool_4;                   // 0x48B0(0x00A0)()
	struct FAnimNode_UseCachedPose                AnimGraphNode_UseCachedPose_5;                     // 0x4950(0x0028)()
	struct FAnimNode_BlendListByBool              AnimGraphNode_BlendListByBool_3;                   // 0x4978(0x00A0)()
	struct FAnimNode_BlendListByBool              AnimGraphNode_BlendListByBool_2;                   // 0x4A18(0x00A0)()
	struct FAnimNode_UseCachedPose                AnimGraphNode_UseCachedPose_4;                     // 0x4AB8(0x0028)()
	struct FAnimNode_UseCachedPose                AnimGraphNode_UseCachedPose_3;                     // 0x4AE0(0x0028)()
	struct FAnimNode_LayeredBoneBlend             AnimGraphNode_LayeredBoneBlend_1;                  // 0x4B08(0x00C0)()
	struct FAnimNode_ConvertLocalToComponentSpace AnimGraphNode_LocalToComponentSpace_3;             // 0x4BC8(0x0020)()
	struct FAnimNode_CopyBone                     AnimGraphNode_CopyBone_7;                          // 0x4BE8(0x00F0)()
	struct FAnimNode_CopyBone                     AnimGraphNode_CopyBone_6;                          // 0x4CD8(0x00F0)()
	struct FAnimNode_ConvertComponentToLocalSpace AnimGraphNode_ComponentToLocalSpace_3;             // 0x4DC8(0x0020)()
	struct FAnimNode_ConvertLocalToComponentSpace AnimGraphNode_LocalToComponentSpace_2;             // 0x4DE8(0x0020)()
	struct FAnimNode_CopyBone                     AnimGraphNode_CopyBone_5;                          // 0x4E08(0x00F0)()
	struct FAnimNode_CopyBone                     AnimGraphNode_CopyBone_4;                          // 0x4EF8(0x00F0)()
	struct FAnimNode_ConvertComponentToLocalSpace AnimGraphNode_ComponentToLocalSpace_2;             // 0x4FE8(0x0020)()
	struct FAnimNode_ControlRig                   AnimGraphNode_ControlRig_1;                        // 0x5008(0x0368)()
	struct FAnimNode_SequenceEvaluator            AnimGraphNode_SequenceEvaluator_5;                 // 0x5370(0x0050)()
	struct FAnimNode_SequenceEvaluator            AnimGraphNode_SequenceEvaluator_4;                 // 0x53C0(0x0050)()
	struct FAnimNode_TwoWayBlend                  AnimGraphNode_TwoWayBlend_6;                       // 0x5410(0x00C8)()
	struct FAnimNode_ApplyMeshSpaceAdditive       AnimGraphNode_ApplyMeshSpaceAdditive_1;            // 0x54D8(0x00D0)()
	struct FAnimNode_TwoWayBlend                  AnimGraphNode_TwoWayBlend_5;                       // 0x55A8(0x00C8)()
	struct FAnimNode_BlendListByEnum              AnimGraphNode_BlendListByEnum_5;                   // 0x5670(0x00B0)()
	struct FAnimNode_BlendListByEnum              AnimGraphNode_BlendListByEnum_4;                   // 0x5720(0x00B0)()
	struct FAnimNode_Root                         AnimGraphNode_Root_3;                              // 0x57D0(0x0030)()
	struct FAnimNode_ApplyMeshSpaceAdditive       AnimGraphNode_ApplyMeshSpaceAdditive;              // 0x5800(0x00D0)()
	struct FAnimNode_TwoWayBlend                  AnimGraphNode_TwoWayBlend_4;                       // 0x58D0(0x00C8)()
	struct FAnimNode_SequenceEvaluator            AnimGraphNode_SequenceEvaluator_3;                 // 0x5998(0x0050)()
	struct FAnimNode_UseCachedPose                AnimGraphNode_UseCachedPose_2;                     // 0x59E8(0x0028)()
	struct FAnimNode_SequenceEvaluator            AnimGraphNode_SequenceEvaluator_2;                 // 0x5A10(0x0050)()
	struct FAnimNode_ControlRig                   AnimGraphNode_ControlRig;                          // 0x5A60(0x0368)()
	struct FAnimNode_LayeredBoneBlend             AnimGraphNode_LayeredBoneBlend;                    // 0x5DC8(0x00C0)()
	struct FAnimNode_TwoWayBlend                  AnimGraphNode_TwoWayBlend_3;                       // 0x5E88(0x00C8)()
	struct FAnimNode_SaveCachedPose               AnimGraphNode_SaveCachedPose;                      // 0x5F50(0x0158)()
	struct FAnimNode_UseCachedPose                AnimGraphNode_UseCachedPose_1;                     // 0x60A8(0x0028)()
	struct FAnimNode_UseCachedPose                AnimGraphNode_UseCachedPose;                       // 0x60D0(0x0028)()
	struct FAnimNode_SequenceEvaluator            AnimGraphNode_SequenceEvaluator_1;                 // 0x60F8(0x0050)()
	struct FAnimNode_SequenceEvaluator            AnimGraphNode_SequenceEvaluator;                   // 0x6148(0x0050)()
	struct FAnimNode_TwoWayBlend                  AnimGraphNode_TwoWayBlend_2;                       // 0x6198(0x00C8)()
	struct FAnimNode_ConvertLocalToComponentSpace AnimGraphNode_LocalToComponentSpace_1;             // 0x6260(0x0020)()
	struct FAnimNode_CopyBone                     AnimGraphNode_CopyBone_3;                          // 0x6280(0x00F0)()
	struct FAnimNode_CopyBone                     AnimGraphNode_CopyBone_2;                          // 0x6370(0x00F0)()
	struct FAnimNode_ConvertComponentToLocalSpace AnimGraphNode_ComponentToLocalSpace_1;             // 0x6460(0x0020)()
	struct FAnimNode_ConvertLocalToComponentSpace AnimGraphNode_LocalToComponentSpace;               // 0x6480(0x0020)()
	struct FAnimNode_CopyBone                     AnimGraphNode_CopyBone_1;                          // 0x64A0(0x00F0)()
	struct FAnimNode_CopyBone                     AnimGraphNode_CopyBone;                            // 0x6590(0x00F0)()
	struct FAnimNode_ConvertComponentToLocalSpace AnimGraphNode_ComponentToLocalSpace;               // 0x6680(0x0020)()
	struct FAnimNode_Root                         AnimGraphNode_Root_2;                              // 0x66A0(0x0030)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_33;                   // 0x66D0(0x0080)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_32;                   // 0x6750(0x0080)()
	struct FAnimNode_TwoWayBlend                  AnimGraphNode_TwoWayBlend_1;                       // 0x67D0(0x00C8)()
	struct FAnimNode_Root                         AnimGraphNode_Root_1;                              // 0x6898(0x0030)()
	struct FAnimNode_BlendListByBool              AnimGraphNode_BlendListByBool_1;                   // 0x68C8(0x00A0)()
	struct FAnimNode_BlendListByBool              AnimGraphNode_BlendListByBool;                     // 0x6968(0x00A0)()
	struct FAnimNode_BlendListByEnum              AnimGraphNode_BlendListByEnum_3;                   // 0x6A08(0x00B0)()
	struct FAnimNode_BlendListByEnum              AnimGraphNode_BlendListByEnum_2;                   // 0x6AB8(0x00B0)()
	struct FAnimNode_BlendListByEnum              AnimGraphNode_BlendListByEnum_1;                   // 0x6B68(0x00B0)()
	struct FAnimNode_BlendListByEnum              AnimGraphNode_BlendListByEnum;                     // 0x6C18(0x00B0)()
	struct FAnimNode_TwoWayBlend                  AnimGraphNode_TwoWayBlend;                         // 0x6CC8(0x00C8)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_31;                   // 0x6D90(0x0080)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_30;                   // 0x6E10(0x0080)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_29;                   // 0x6E90(0x0080)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_28;                   // 0x6F10(0x0080)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_27;                   // 0x6F90(0x0080)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_26;                   // 0x7010(0x0080)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_25;                   // 0x7090(0x0080)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_24;                   // 0x7110(0x0080)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_23;                   // 0x7190(0x0080)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_22;                   // 0x7210(0x0080)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_21;                   // 0x7290(0x0080)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_20;                   // 0x7310(0x0080)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_19;                   // 0x7390(0x0080)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_18;                   // 0x7410(0x0080)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_17;                   // 0x7490(0x0080)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_16;                   // 0x7510(0x0080)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_15;                   // 0x7590(0x0080)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_14;                   // 0x7610(0x0080)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_13;                   // 0x7690(0x0080)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_12;                   // 0x7710(0x0080)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_11;                   // 0x7790(0x0080)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_10;                   // 0x7810(0x0080)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_9;                    // 0x7890(0x0080)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_8;                    // 0x7910(0x0080)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_7;                    // 0x7990(0x0080)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_6;                    // 0x7A10(0x0080)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_5;                    // 0x7A90(0x0080)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_4;                    // 0x7B10(0x0080)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_3;                    // 0x7B90(0x0080)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_2;                    // 0x7C10(0x0080)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_1;                    // 0x7C90(0x0080)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer;                      // 0x7D10(0x0080)()
	struct FAnimNode_Root                         AnimGraphNode_Root;                                // 0x7D90(0x0030)()
	struct FRotator                               __CustomProperty_RotationalInertiaOffset_1CDC39C9FFC742B8AD857B7C38E95464; // 0x7DC0(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          __CustomProperty_bRunning_1CDC39C9FFC742B8AD857B7C38E95464; // 0x7DCC(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          __CustomProperty_bApplyMovementSway_1CDC39C9FFC742B8AD857B7C38E95464; // 0x7DCD(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_7DCE[0x2];                                     // 0x7DCE(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	class UAnimSequence*                          Idle_Prone;                                        // 0x7DD0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UAnimSequence*                          Idle_Crouch;                                       // 0x7DD8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UAnimSequence*                          Idle_Stand;                                        // 0x7DE0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UABP_Base_C*                            BaseABPRef;                                        // 0x7DE8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         StrideWarpingCycleAlpha;                           // 0x7DF0(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         OrientationAngle;                                  // 0x7DF4(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         LocomotionAngleDeltaThreshold;                     // 0x7DF8(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                EyeRightOffset;                                    // 0x7DFC(0x000C)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                EyeLeftOffset;                                     // 0x7E08(0x000C)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CollisionTraceEndOffset;                           // 0x7E14(0x000C)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         EngagedAlpha;                                      // 0x7E20(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         OffTargetAlpha;                                    // 0x7E24(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UBlendSpaceBase*                        AimOffsetProne;                                    // 0x7E28(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UBlendSpaceBase*                        AimOffsetCrouch;                                   // 0x7E30(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UBlendSpaceBase*                        AimOffsetStand;                                    // 0x7E38(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         LowReadyHighExplicitTime;                          // 0x7E40(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         PrevOffTargetAlpha;                                // 0x7E44(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         LowHighAlpha;                                      // 0x7E48(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         DirectionBlendTime;                                // 0x7E4C(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         TwoHandAlpha;                                      // 0x7E50(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          bTwoHandsOnItem;                                   // 0x7E54(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	uint8                                         Pad_7E55[0x3];                                     // 0x7E55(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class UAnimSequenceBase*                      ProneReadyEngagedAdditivePose;                     // 0x7E58(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UAnimSequenceBase*                      CrouchReadyEngagedAdditivePose;                    // 0x7E60(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UAnimSequenceBase*                      StandReadyEngagedAdditivePose;                     // 0x7E68(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FGBAnimDirectionSequences              Sprint_Crouch;                                     // 0x7E70(0x0040)(Edit, BlueprintVisible, DisableEditOnInstance, NoDestructor)
	struct FGBAnimDirectionSequences              Sprint_Stand;                                      // 0x7EB0(0x0040)(Edit, BlueprintVisible, DisableEditOnInstance, NoDestructor)
	struct FGBAnimDirectionSequences              Walk_Prone;                                        // 0x7EF0(0x0040)(Edit, BlueprintVisible, DisableEditOnInstance, NoDestructor)
	struct FGBAnimDirectionSequences              Walk_Crouch;                                       // 0x7F30(0x0040)(Edit, BlueprintVisible, DisableEditOnInstance, NoDestructor)
	struct FGBAnimDirectionSequences              Walk_Stand;                                        // 0x7F70(0x0040)(Edit, BlueprintVisible, DisableEditOnInstance, NoDestructor)
	class UAnimSequence*                          Run_Prone;                                         // 0x7FB0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FGBAnimDirectionSequences              Run_Crouch;                                        // 0x7FB8(0x0040)(Edit, BlueprintVisible, DisableEditOnInstance, NoDestructor)
	struct FGBAnimDirectionSequences              Run_Stand;                                         // 0x7FF8(0x0040)(Edit, BlueprintVisible, DisableEditOnInstance, NoDestructor)
	class UAnimMontage*                           ProneToStand;                                      // 0x8038(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UAnimMontage*                           ProneToCrouch;                                     // 0x8040(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UAnimMontage*                           StandToProne;                                      // 0x8048(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UAnimMontage*                           CrouchToProne;                                     // 0x8050(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UAnimMontage*                           SprintToProne;                                     // 0x8058(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UAnimMontage*                           ProneTurnLeft;                                     // 0x8060(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UAnimMontage*                           ProneTurnRIght;                                    // 0x8068(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UBlendSpaceBase*                        LeanPoses;                                         // 0x8070(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          EngagedRightHandBone;                              // 0x8078(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	uint8                                         Pad_8079[0x3];                                     // 0x8079(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class FName                                   EngagedDynamicRightHandIKRoot;                     // 0x807C(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FName                                   EngagedDynamicLeftHandIKRoot;                      // 0x8084(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         Movement_Sway_Walk_Pitch;                          // 0x808C(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         Movement_Sway_Walk_Yaw;                            // 0x8090(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         Movement_Sway_Run_Pitch;                           // 0x8094(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         Movement_Sway_Run_Yaw;                             // 0x8098(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_809C[0x4];                                     // 0x809C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UAnimMontage*                           NVGFlipDownMontage;                                // 0x80A0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UAnimMontage*                           NVGFlipUpMontage;                                  // 0x80A8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UAnimMontage*                           WatchCheck;                                        // 0x80B0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UAnimMontage*                           WatchCheckProne;                                   // 0x80B8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_ABP_GenericItem_AnimLayerBase(int32 EntryPoint);
	void AnimNotify_LeftFootDown();
	void AnimNotify_RightFootDown();
	void BlueprintInitializeAnimation();
	void BlueprintUpdateAnimation(float DeltaTimeX);
	void UpdateWeaponPositionData(float DeltaTime);
	void AnimGraph(struct FPoseLink* AnimGraph_0);
	void FullBody_CycleState(struct FPoseLink* FullBody_CycleState_0);
	void FullBody_IdleState(struct FPoseLink* FullBody_IdleState_0);
	void HandPose_OverrideState(const struct FPoseLink& InLocomotion, struct FPoseLink* HandPose_OverrideState_0);
	void FullBody_Aiming(const struct FPoseLink& InUpperbodyLowerbodySplit, struct FPoseLink* FullBody_Aiming_0);
	void FullBody_Additives(struct FPoseLink* FullBody_Additives_0);
	void FullBody_SkeletalControls(const struct FPoseLink& InNearFinal, struct FPoseLink* FullBody_SkeletalControls_0);
	void FullBody_PreAim(const struct FPoseLink& InPreAim, struct FPoseLink* FullBody_PreAim_0);
	void FullBody_ProneIdleState(struct FPoseLink* FullBody_ProneIdleState_0);
	void FullBody_ProneCycleState(struct FPoseLink* FullBody_ProneCycleState_0);
	void FullBody_SprintCycleState(struct FPoseLink* FullBody_SprintCycleState_0);

	class UAnimMontage* GetMontageFromLinkedLayer(class FName MontageName) const;

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"ABP_GenericItem_AnimLayerBase_C">();
	}
	static class UABP_GenericItem_AnimLayerBase_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UABP_GenericItem_AnimLayerBase_C>();
	}
};
static_assert(alignof(UABP_GenericItem_AnimLayerBase_C) == 0x000010, "Wrong alignment on UABP_GenericItem_AnimLayerBase_C");
static_assert(sizeof(UABP_GenericItem_AnimLayerBase_C) == 0x0080C0, "Wrong size on UABP_GenericItem_AnimLayerBase_C");
static_assert(offsetof(UABP_GenericItem_AnimLayerBase_C, UberGraphFrame) == 0x000AC0, "Member 'UABP_GenericItem_AnimLayerBase_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UABP_GenericItem_AnimLayerBase_C, AnimGraphNode_SequencePlayer_49) == 0x000AC8, "Member 'UABP_GenericItem_AnimLayerBase_C::AnimGraphNode_SequencePlayer_49' has a wrong offset!");
static_assert(offsetof(UABP_GenericItem_AnimLayerBase_C, AnimGraphNode_SequencePlayer_48) == 0x000B48, "Member 'UABP_GenericItem_AnimLayerBase_C::AnimGraphNode_SequencePlayer_48' has a wrong offset!");
static_assert(offsetof(UABP_GenericItem_AnimLayerBase_C, AnimGraphNode_SequencePlayer_47) == 0x000BC8, "Member 'UABP_GenericItem_AnimLayerBase_C::AnimGraphNode_SequencePlayer_47' has a wrong offset!");
static_assert(offsetof(UABP_GenericItem_AnimLayerBase_C, AnimGraphNode_SequencePlayer_46) == 0x000C48, "Member 'UABP_GenericItem_AnimLayerBase_C::AnimGraphNode_SequencePlayer_46' has a wrong offset!");
static_assert(offsetof(UABP_GenericItem_AnimLayerBase_C, AnimGraphNode_SequencePlayer_45) == 0x000CC8, "Member 'UABP_GenericItem_AnimLayerBase_C::AnimGraphNode_SequencePlayer_45' has a wrong offset!");
static_assert(offsetof(UABP_GenericItem_AnimLayerBase_C, AnimGraphNode_SequencePlayer_44) == 0x000D48, "Member 'UABP_GenericItem_AnimLayerBase_C::AnimGraphNode_SequencePlayer_44' has a wrong offset!");
static_assert(offsetof(UABP_GenericItem_AnimLayerBase_C, AnimGraphNode_Root_10) == 0x000DC8, "Member 'UABP_GenericItem_AnimLayerBase_C::AnimGraphNode_Root_10' has a wrong offset!");
static_assert(offsetof(UABP_GenericItem_AnimLayerBase_C, AnimGraphNode_SequencePlayer_43) == 0x000DF8, "Member 'UABP_GenericItem_AnimLayerBase_C::AnimGraphNode_SequencePlayer_43' has a wrong offset!");
static_assert(offsetof(UABP_GenericItem_AnimLayerBase_C, AnimGraphNode_BlendListByBool_9) == 0x000E78, "Member 'UABP_GenericItem_AnimLayerBase_C::AnimGraphNode_BlendListByBool_9' has a wrong offset!");
static_assert(offsetof(UABP_GenericItem_AnimLayerBase_C, AnimGraphNode_SequencePlayer_42) == 0x000F18, "Member 'UABP_GenericItem_AnimLayerBase_C::AnimGraphNode_SequencePlayer_42' has a wrong offset!");
static_assert(offsetof(UABP_GenericItem_AnimLayerBase_C, AnimGraphNode_BlendListByEnum_6) == 0x000F98, "Member 'UABP_GenericItem_AnimLayerBase_C::AnimGraphNode_BlendListByEnum_6' has a wrong offset!");
static_assert(offsetof(UABP_GenericItem_AnimLayerBase_C, AnimGraphNode_SequencePlayer_41) == 0x001048, "Member 'UABP_GenericItem_AnimLayerBase_C::AnimGraphNode_SequencePlayer_41' has a wrong offset!");
static_assert(offsetof(UABP_GenericItem_AnimLayerBase_C, AnimGraphNode_SequencePlayer_40) == 0x0010C8, "Member 'UABP_GenericItem_AnimLayerBase_C::AnimGraphNode_SequencePlayer_40' has a wrong offset!");
static_assert(offsetof(UABP_GenericItem_AnimLayerBase_C, AnimGraphNode_SequencePlayer_39) == 0x001148, "Member 'UABP_GenericItem_AnimLayerBase_C::AnimGraphNode_SequencePlayer_39' has a wrong offset!");
static_assert(offsetof(UABP_GenericItem_AnimLayerBase_C, AnimGraphNode_SequencePlayer_38) == 0x0011C8, "Member 'UABP_GenericItem_AnimLayerBase_C::AnimGraphNode_SequencePlayer_38' has a wrong offset!");
static_assert(offsetof(UABP_GenericItem_AnimLayerBase_C, AnimGraphNode_SequencePlayer_37) == 0x001248, "Member 'UABP_GenericItem_AnimLayerBase_C::AnimGraphNode_SequencePlayer_37' has a wrong offset!");
static_assert(offsetof(UABP_GenericItem_AnimLayerBase_C, AnimGraphNode_SequencePlayer_36) == 0x0012C8, "Member 'UABP_GenericItem_AnimLayerBase_C::AnimGraphNode_SequencePlayer_36' has a wrong offset!");
static_assert(offsetof(UABP_GenericItem_AnimLayerBase_C, AnimGraphNode_SequencePlayer_35) == 0x001348, "Member 'UABP_GenericItem_AnimLayerBase_C::AnimGraphNode_SequencePlayer_35' has a wrong offset!");
static_assert(offsetof(UABP_GenericItem_AnimLayerBase_C, AnimGraphNode_Root_9) == 0x0013C8, "Member 'UABP_GenericItem_AnimLayerBase_C::AnimGraphNode_Root_9' has a wrong offset!");
static_assert(offsetof(UABP_GenericItem_AnimLayerBase_C, AnimGraphNode_SequencePlayer_34) == 0x0013F8, "Member 'UABP_GenericItem_AnimLayerBase_C::AnimGraphNode_SequencePlayer_34' has a wrong offset!");
static_assert(offsetof(UABP_GenericItem_AnimLayerBase_C, AnimGraphNode_Root_8) == 0x001478, "Member 'UABP_GenericItem_AnimLayerBase_C::AnimGraphNode_Root_8' has a wrong offset!");
static_assert(offsetof(UABP_GenericItem_AnimLayerBase_C, AnimGraphNode_LinkedInputPose_3) == 0x0014A8, "Member 'UABP_GenericItem_AnimLayerBase_C::AnimGraphNode_LinkedInputPose_3' has a wrong offset!");
static_assert(offsetof(UABP_GenericItem_AnimLayerBase_C, AnimGraphNode_ControlRig_4) == 0x0015C0, "Member 'UABP_GenericItem_AnimLayerBase_C::AnimGraphNode_ControlRig_4' has a wrong offset!");
static_assert(offsetof(UABP_GenericItem_AnimLayerBase_C, AnimGraphNode_Root_7) == 0x001928, "Member 'UABP_GenericItem_AnimLayerBase_C::AnimGraphNode_Root_7' has a wrong offset!");
static_assert(offsetof(UABP_GenericItem_AnimLayerBase_C, AnimGraphNode_LinkedInputPose_2) == 0x001958, "Member 'UABP_GenericItem_AnimLayerBase_C::AnimGraphNode_LinkedInputPose_2' has a wrong offset!");
static_assert(offsetof(UABP_GenericItem_AnimLayerBase_C, AnimGraphNode_SaveCachedPose_5) == 0x001A70, "Member 'UABP_GenericItem_AnimLayerBase_C::AnimGraphNode_SaveCachedPose_5' has a wrong offset!");
static_assert(offsetof(UABP_GenericItem_AnimLayerBase_C, AnimGraphNode_SaveCachedPose_4) == 0x001BC8, "Member 'UABP_GenericItem_AnimLayerBase_C::AnimGraphNode_SaveCachedPose_4' has a wrong offset!");
static_assert(offsetof(UABP_GenericItem_AnimLayerBase_C, AnimGraphNode_UseCachedPose_16) == 0x001D20, "Member 'UABP_GenericItem_AnimLayerBase_C::AnimGraphNode_UseCachedPose_16' has a wrong offset!");
static_assert(offsetof(UABP_GenericItem_AnimLayerBase_C, AnimGraphNode_ControlRig_3) == 0x001D48, "Member 'UABP_GenericItem_AnimLayerBase_C::AnimGraphNode_ControlRig_3' has a wrong offset!");
static_assert(offsetof(UABP_GenericItem_AnimLayerBase_C, AnimGraphNode_LayeredBoneBlend_4) == 0x0020B0, "Member 'UABP_GenericItem_AnimLayerBase_C::AnimGraphNode_LayeredBoneBlend_4' has a wrong offset!");
static_assert(offsetof(UABP_GenericItem_AnimLayerBase_C, AnimGraphNode_SequenceEvaluator_9) == 0x002170, "Member 'UABP_GenericItem_AnimLayerBase_C::AnimGraphNode_SequenceEvaluator_9' has a wrong offset!");
static_assert(offsetof(UABP_GenericItem_AnimLayerBase_C, AnimGraphNode_SequenceEvaluator_8) == 0x0021C0, "Member 'UABP_GenericItem_AnimLayerBase_C::AnimGraphNode_SequenceEvaluator_8' has a wrong offset!");
static_assert(offsetof(UABP_GenericItem_AnimLayerBase_C, AnimGraphNode_ApplyMeshSpaceAdditive_2) == 0x002210, "Member 'UABP_GenericItem_AnimLayerBase_C::AnimGraphNode_ApplyMeshSpaceAdditive_2' has a wrong offset!");
static_assert(offsetof(UABP_GenericItem_AnimLayerBase_C, AnimGraphNode_LocalToComponentSpace_7) == 0x0022E0, "Member 'UABP_GenericItem_AnimLayerBase_C::AnimGraphNode_LocalToComponentSpace_7' has a wrong offset!");
static_assert(offsetof(UABP_GenericItem_AnimLayerBase_C, AnimGraphNode_CopyBone_20) == 0x002300, "Member 'UABP_GenericItem_AnimLayerBase_C::AnimGraphNode_CopyBone_20' has a wrong offset!");
static_assert(offsetof(UABP_GenericItem_AnimLayerBase_C, AnimGraphNode_ComponentToLocalSpace_7) == 0x0023F0, "Member 'UABP_GenericItem_AnimLayerBase_C::AnimGraphNode_ComponentToLocalSpace_7' has a wrong offset!");
static_assert(offsetof(UABP_GenericItem_AnimLayerBase_C, AnimGraphNode_LocalToComponentSpace_6) == 0x002410, "Member 'UABP_GenericItem_AnimLayerBase_C::AnimGraphNode_LocalToComponentSpace_6' has a wrong offset!");
static_assert(offsetof(UABP_GenericItem_AnimLayerBase_C, AnimGraphNode_CopyBone_19) == 0x002430, "Member 'UABP_GenericItem_AnimLayerBase_C::AnimGraphNode_CopyBone_19' has a wrong offset!");
static_assert(offsetof(UABP_GenericItem_AnimLayerBase_C, AnimGraphNode_CopyBone_18) == 0x002520, "Member 'UABP_GenericItem_AnimLayerBase_C::AnimGraphNode_CopyBone_18' has a wrong offset!");
static_assert(offsetof(UABP_GenericItem_AnimLayerBase_C, AnimGraphNode_ComponentToLocalSpace_6) == 0x002610, "Member 'UABP_GenericItem_AnimLayerBase_C::AnimGraphNode_ComponentToLocalSpace_6' has a wrong offset!");
static_assert(offsetof(UABP_GenericItem_AnimLayerBase_C, AnimGraphNode_CopyBone_17) == 0x002630, "Member 'UABP_GenericItem_AnimLayerBase_C::AnimGraphNode_CopyBone_17' has a wrong offset!");
static_assert(offsetof(UABP_GenericItem_AnimLayerBase_C, AnimGraphNode_CopyBone_16) == 0x002720, "Member 'UABP_GenericItem_AnimLayerBase_C::AnimGraphNode_CopyBone_16' has a wrong offset!");
static_assert(offsetof(UABP_GenericItem_AnimLayerBase_C, AnimGraphNode_CopyBone_15) == 0x002810, "Member 'UABP_GenericItem_AnimLayerBase_C::AnimGraphNode_CopyBone_15' has a wrong offset!");
static_assert(offsetof(UABP_GenericItem_AnimLayerBase_C, AnimGraphNode_CopyBone_14) == 0x002900, "Member 'UABP_GenericItem_AnimLayerBase_C::AnimGraphNode_CopyBone_14' has a wrong offset!");
static_assert(offsetof(UABP_GenericItem_AnimLayerBase_C, AnimGraphNode_UseCachedPose_15) == 0x0029F0, "Member 'UABP_GenericItem_AnimLayerBase_C::AnimGraphNode_UseCachedPose_15' has a wrong offset!");
static_assert(offsetof(UABP_GenericItem_AnimLayerBase_C, AnimGraphNode_UseCachedPose_14) == 0x002A18, "Member 'UABP_GenericItem_AnimLayerBase_C::AnimGraphNode_UseCachedPose_14' has a wrong offset!");
static_assert(offsetof(UABP_GenericItem_AnimLayerBase_C, AnimGraphNode_BlendListByBool_8) == 0x002A40, "Member 'UABP_GenericItem_AnimLayerBase_C::AnimGraphNode_BlendListByBool_8' has a wrong offset!");
static_assert(offsetof(UABP_GenericItem_AnimLayerBase_C, AnimGraphNode_Root_6) == 0x002AE0, "Member 'UABP_GenericItem_AnimLayerBase_C::AnimGraphNode_Root_6' has a wrong offset!");
static_assert(offsetof(UABP_GenericItem_AnimLayerBase_C, AnimGraphNode_IdentityPose) == 0x002B10, "Member 'UABP_GenericItem_AnimLayerBase_C::AnimGraphNode_IdentityPose' has a wrong offset!");
static_assert(offsetof(UABP_GenericItem_AnimLayerBase_C, AnimGraphNode_Root_5) == 0x002B28, "Member 'UABP_GenericItem_AnimLayerBase_C::AnimGraphNode_Root_5' has a wrong offset!");
static_assert(offsetof(UABP_GenericItem_AnimLayerBase_C, AnimGraphNode_LinkedInputPose_1) == 0x002B58, "Member 'UABP_GenericItem_AnimLayerBase_C::AnimGraphNode_LinkedInputPose_1' has a wrong offset!");
static_assert(offsetof(UABP_GenericItem_AnimLayerBase_C, AnimGraphNode_SaveCachedPose_3) == 0x002C70, "Member 'UABP_GenericItem_AnimLayerBase_C::AnimGraphNode_SaveCachedPose_3' has a wrong offset!");
static_assert(offsetof(UABP_GenericItem_AnimLayerBase_C, AnimGraphNode_UseCachedPose_13) == 0x002DC8, "Member 'UABP_GenericItem_AnimLayerBase_C::AnimGraphNode_UseCachedPose_13' has a wrong offset!");
static_assert(offsetof(UABP_GenericItem_AnimLayerBase_C, AnimGraphNode_UseCachedPose_12) == 0x002DF0, "Member 'UABP_GenericItem_AnimLayerBase_C::AnimGraphNode_UseCachedPose_12' has a wrong offset!");
static_assert(offsetof(UABP_GenericItem_AnimLayerBase_C, AnimGraphNode_ComponentToLocalSpace_5) == 0x002E18, "Member 'UABP_GenericItem_AnimLayerBase_C::AnimGraphNode_ComponentToLocalSpace_5' has a wrong offset!");
static_assert(offsetof(UABP_GenericItem_AnimLayerBase_C, AnimGraphNode_CopyBone_13) == 0x002E38, "Member 'UABP_GenericItem_AnimLayerBase_C::AnimGraphNode_CopyBone_13' has a wrong offset!");
static_assert(offsetof(UABP_GenericItem_AnimLayerBase_C, AnimGraphNode_CopyBone_12) == 0x002F28, "Member 'UABP_GenericItem_AnimLayerBase_C::AnimGraphNode_CopyBone_12' has a wrong offset!");
static_assert(offsetof(UABP_GenericItem_AnimLayerBase_C, AnimGraphNode_CopyBone_11) == 0x003018, "Member 'UABP_GenericItem_AnimLayerBase_C::AnimGraphNode_CopyBone_11' has a wrong offset!");
static_assert(offsetof(UABP_GenericItem_AnimLayerBase_C, AnimGraphNode_BlendListByBool_7) == 0x003108, "Member 'UABP_GenericItem_AnimLayerBase_C::AnimGraphNode_BlendListByBool_7' has a wrong offset!");
static_assert(offsetof(UABP_GenericItem_AnimLayerBase_C, AnimGraphNode_SaveCachedPose_2) == 0x0031A8, "Member 'UABP_GenericItem_AnimLayerBase_C::AnimGraphNode_SaveCachedPose_2' has a wrong offset!");
static_assert(offsetof(UABP_GenericItem_AnimLayerBase_C, AnimGraphNode_BlendListByBool_6) == 0x003300, "Member 'UABP_GenericItem_AnimLayerBase_C::AnimGraphNode_BlendListByBool_6' has a wrong offset!");
static_assert(offsetof(UABP_GenericItem_AnimLayerBase_C, AnimGraphNode_TwoWayBlend_8) == 0x0033A0, "Member 'UABP_GenericItem_AnimLayerBase_C::AnimGraphNode_TwoWayBlend_8' has a wrong offset!");
static_assert(offsetof(UABP_GenericItem_AnimLayerBase_C, AnimGraphNode_RotationOffsetBlendSpace_3) == 0x003468, "Member 'UABP_GenericItem_AnimLayerBase_C::AnimGraphNode_RotationOffsetBlendSpace_3' has a wrong offset!");
static_assert(offsetof(UABP_GenericItem_AnimLayerBase_C, AnimGraphNode_RotationOffsetBlendSpace_2) == 0x0035F8, "Member 'UABP_GenericItem_AnimLayerBase_C::AnimGraphNode_RotationOffsetBlendSpace_2' has a wrong offset!");
static_assert(offsetof(UABP_GenericItem_AnimLayerBase_C, AnimGraphNode_RotationOffsetBlendSpace_1) == 0x003788, "Member 'UABP_GenericItem_AnimLayerBase_C::AnimGraphNode_RotationOffsetBlendSpace_1' has a wrong offset!");
static_assert(offsetof(UABP_GenericItem_AnimLayerBase_C, AnimGraphNode_LayeredBoneBlend_3) == 0x003918, "Member 'UABP_GenericItem_AnimLayerBase_C::AnimGraphNode_LayeredBoneBlend_3' has a wrong offset!");
static_assert(offsetof(UABP_GenericItem_AnimLayerBase_C, AnimGraphNode_LocalToComponentSpace_5) == 0x0039D8, "Member 'UABP_GenericItem_AnimLayerBase_C::AnimGraphNode_LocalToComponentSpace_5' has a wrong offset!");
static_assert(offsetof(UABP_GenericItem_AnimLayerBase_C, AnimGraphNode_UseCachedPose_11) == 0x0039F8, "Member 'UABP_GenericItem_AnimLayerBase_C::AnimGraphNode_UseCachedPose_11' has a wrong offset!");
static_assert(offsetof(UABP_GenericItem_AnimLayerBase_C, AnimGraphNode_BlendListByBool_5) == 0x003A20, "Member 'UABP_GenericItem_AnimLayerBase_C::AnimGraphNode_BlendListByBool_5' has a wrong offset!");
static_assert(offsetof(UABP_GenericItem_AnimLayerBase_C, AnimGraphNode_UseCachedPose_10) == 0x003AC0, "Member 'UABP_GenericItem_AnimLayerBase_C::AnimGraphNode_UseCachedPose_10' has a wrong offset!");
static_assert(offsetof(UABP_GenericItem_AnimLayerBase_C, AnimGraphNode_LocalToComponentSpace_4) == 0x003AE8, "Member 'UABP_GenericItem_AnimLayerBase_C::AnimGraphNode_LocalToComponentSpace_4' has a wrong offset!");
static_assert(offsetof(UABP_GenericItem_AnimLayerBase_C, AnimGraphNode_CopyBone_10) == 0x003B08, "Member 'UABP_GenericItem_AnimLayerBase_C::AnimGraphNode_CopyBone_10' has a wrong offset!");
static_assert(offsetof(UABP_GenericItem_AnimLayerBase_C, AnimGraphNode_CopyBone_9) == 0x003BF8, "Member 'UABP_GenericItem_AnimLayerBase_C::AnimGraphNode_CopyBone_9' has a wrong offset!");
static_assert(offsetof(UABP_GenericItem_AnimLayerBase_C, AnimGraphNode_CopyBone_8) == 0x003CE8, "Member 'UABP_GenericItem_AnimLayerBase_C::AnimGraphNode_CopyBone_8' has a wrong offset!");
static_assert(offsetof(UABP_GenericItem_AnimLayerBase_C, AnimGraphNode_ComponentToLocalSpace_4) == 0x003DD8, "Member 'UABP_GenericItem_AnimLayerBase_C::AnimGraphNode_ComponentToLocalSpace_4' has a wrong offset!");
static_assert(offsetof(UABP_GenericItem_AnimLayerBase_C, AnimGraphNode_UseCachedPose_9) == 0x003DF8, "Member 'UABP_GenericItem_AnimLayerBase_C::AnimGraphNode_UseCachedPose_9' has a wrong offset!");
static_assert(offsetof(UABP_GenericItem_AnimLayerBase_C, AnimGraphNode_RotationOffsetBlendSpace) == 0x003E20, "Member 'UABP_GenericItem_AnimLayerBase_C::AnimGraphNode_RotationOffsetBlendSpace' has a wrong offset!");
static_assert(offsetof(UABP_GenericItem_AnimLayerBase_C, AnimGraphNode_UseCachedPose_8) == 0x003FB0, "Member 'UABP_GenericItem_AnimLayerBase_C::AnimGraphNode_UseCachedPose_8' has a wrong offset!");
static_assert(offsetof(UABP_GenericItem_AnimLayerBase_C, AnimGraphNode_UseCachedPose_7) == 0x003FD8, "Member 'UABP_GenericItem_AnimLayerBase_C::AnimGraphNode_UseCachedPose_7' has a wrong offset!");
static_assert(offsetof(UABP_GenericItem_AnimLayerBase_C, AnimGraphNode_ControlRig_2) == 0x004000, "Member 'UABP_GenericItem_AnimLayerBase_C::AnimGraphNode_ControlRig_2' has a wrong offset!");
static_assert(offsetof(UABP_GenericItem_AnimLayerBase_C, AnimGraphNode_LayeredBoneBlend_2) == 0x004368, "Member 'UABP_GenericItem_AnimLayerBase_C::AnimGraphNode_LayeredBoneBlend_2' has a wrong offset!");
static_assert(offsetof(UABP_GenericItem_AnimLayerBase_C, AnimGraphNode_UseCachedPose_6) == 0x004428, "Member 'UABP_GenericItem_AnimLayerBase_C::AnimGraphNode_UseCachedPose_6' has a wrong offset!");
static_assert(offsetof(UABP_GenericItem_AnimLayerBase_C, AnimGraphNode_Root_4) == 0x004450, "Member 'UABP_GenericItem_AnimLayerBase_C::AnimGraphNode_Root_4' has a wrong offset!");
static_assert(offsetof(UABP_GenericItem_AnimLayerBase_C, AnimGraphNode_LinkedInputPose) == 0x004480, "Member 'UABP_GenericItem_AnimLayerBase_C::AnimGraphNode_LinkedInputPose' has a wrong offset!");
static_assert(offsetof(UABP_GenericItem_AnimLayerBase_C, AnimGraphNode_SaveCachedPose_1) == 0x004598, "Member 'UABP_GenericItem_AnimLayerBase_C::AnimGraphNode_SaveCachedPose_1' has a wrong offset!");
static_assert(offsetof(UABP_GenericItem_AnimLayerBase_C, AnimGraphNode_TwoWayBlend_7) == 0x0046F0, "Member 'UABP_GenericItem_AnimLayerBase_C::AnimGraphNode_TwoWayBlend_7' has a wrong offset!");
static_assert(offsetof(UABP_GenericItem_AnimLayerBase_C, AnimGraphNode_SequenceEvaluator_7) == 0x0047B8, "Member 'UABP_GenericItem_AnimLayerBase_C::AnimGraphNode_SequenceEvaluator_7' has a wrong offset!");
static_assert(offsetof(UABP_GenericItem_AnimLayerBase_C, AnimGraphNode_SequenceEvaluator_6) == 0x004808, "Member 'UABP_GenericItem_AnimLayerBase_C::AnimGraphNode_SequenceEvaluator_6' has a wrong offset!");
static_assert(offsetof(UABP_GenericItem_AnimLayerBase_C, AnimGraphNode_ModifyCurve) == 0x004858, "Member 'UABP_GenericItem_AnimLayerBase_C::AnimGraphNode_ModifyCurve' has a wrong offset!");
static_assert(offsetof(UABP_GenericItem_AnimLayerBase_C, AnimGraphNode_BlendListByBool_4) == 0x0048B0, "Member 'UABP_GenericItem_AnimLayerBase_C::AnimGraphNode_BlendListByBool_4' has a wrong offset!");
static_assert(offsetof(UABP_GenericItem_AnimLayerBase_C, AnimGraphNode_UseCachedPose_5) == 0x004950, "Member 'UABP_GenericItem_AnimLayerBase_C::AnimGraphNode_UseCachedPose_5' has a wrong offset!");
static_assert(offsetof(UABP_GenericItem_AnimLayerBase_C, AnimGraphNode_BlendListByBool_3) == 0x004978, "Member 'UABP_GenericItem_AnimLayerBase_C::AnimGraphNode_BlendListByBool_3' has a wrong offset!");
static_assert(offsetof(UABP_GenericItem_AnimLayerBase_C, AnimGraphNode_BlendListByBool_2) == 0x004A18, "Member 'UABP_GenericItem_AnimLayerBase_C::AnimGraphNode_BlendListByBool_2' has a wrong offset!");
static_assert(offsetof(UABP_GenericItem_AnimLayerBase_C, AnimGraphNode_UseCachedPose_4) == 0x004AB8, "Member 'UABP_GenericItem_AnimLayerBase_C::AnimGraphNode_UseCachedPose_4' has a wrong offset!");
static_assert(offsetof(UABP_GenericItem_AnimLayerBase_C, AnimGraphNode_UseCachedPose_3) == 0x004AE0, "Member 'UABP_GenericItem_AnimLayerBase_C::AnimGraphNode_UseCachedPose_3' has a wrong offset!");
static_assert(offsetof(UABP_GenericItem_AnimLayerBase_C, AnimGraphNode_LayeredBoneBlend_1) == 0x004B08, "Member 'UABP_GenericItem_AnimLayerBase_C::AnimGraphNode_LayeredBoneBlend_1' has a wrong offset!");
static_assert(offsetof(UABP_GenericItem_AnimLayerBase_C, AnimGraphNode_LocalToComponentSpace_3) == 0x004BC8, "Member 'UABP_GenericItem_AnimLayerBase_C::AnimGraphNode_LocalToComponentSpace_3' has a wrong offset!");
static_assert(offsetof(UABP_GenericItem_AnimLayerBase_C, AnimGraphNode_CopyBone_7) == 0x004BE8, "Member 'UABP_GenericItem_AnimLayerBase_C::AnimGraphNode_CopyBone_7' has a wrong offset!");
static_assert(offsetof(UABP_GenericItem_AnimLayerBase_C, AnimGraphNode_CopyBone_6) == 0x004CD8, "Member 'UABP_GenericItem_AnimLayerBase_C::AnimGraphNode_CopyBone_6' has a wrong offset!");
static_assert(offsetof(UABP_GenericItem_AnimLayerBase_C, AnimGraphNode_ComponentToLocalSpace_3) == 0x004DC8, "Member 'UABP_GenericItem_AnimLayerBase_C::AnimGraphNode_ComponentToLocalSpace_3' has a wrong offset!");
static_assert(offsetof(UABP_GenericItem_AnimLayerBase_C, AnimGraphNode_LocalToComponentSpace_2) == 0x004DE8, "Member 'UABP_GenericItem_AnimLayerBase_C::AnimGraphNode_LocalToComponentSpace_2' has a wrong offset!");
static_assert(offsetof(UABP_GenericItem_AnimLayerBase_C, AnimGraphNode_CopyBone_5) == 0x004E08, "Member 'UABP_GenericItem_AnimLayerBase_C::AnimGraphNode_CopyBone_5' has a wrong offset!");
static_assert(offsetof(UABP_GenericItem_AnimLayerBase_C, AnimGraphNode_CopyBone_4) == 0x004EF8, "Member 'UABP_GenericItem_AnimLayerBase_C::AnimGraphNode_CopyBone_4' has a wrong offset!");
static_assert(offsetof(UABP_GenericItem_AnimLayerBase_C, AnimGraphNode_ComponentToLocalSpace_2) == 0x004FE8, "Member 'UABP_GenericItem_AnimLayerBase_C::AnimGraphNode_ComponentToLocalSpace_2' has a wrong offset!");
static_assert(offsetof(UABP_GenericItem_AnimLayerBase_C, AnimGraphNode_ControlRig_1) == 0x005008, "Member 'UABP_GenericItem_AnimLayerBase_C::AnimGraphNode_ControlRig_1' has a wrong offset!");
static_assert(offsetof(UABP_GenericItem_AnimLayerBase_C, AnimGraphNode_SequenceEvaluator_5) == 0x005370, "Member 'UABP_GenericItem_AnimLayerBase_C::AnimGraphNode_SequenceEvaluator_5' has a wrong offset!");
static_assert(offsetof(UABP_GenericItem_AnimLayerBase_C, AnimGraphNode_SequenceEvaluator_4) == 0x0053C0, "Member 'UABP_GenericItem_AnimLayerBase_C::AnimGraphNode_SequenceEvaluator_4' has a wrong offset!");
static_assert(offsetof(UABP_GenericItem_AnimLayerBase_C, AnimGraphNode_TwoWayBlend_6) == 0x005410, "Member 'UABP_GenericItem_AnimLayerBase_C::AnimGraphNode_TwoWayBlend_6' has a wrong offset!");
static_assert(offsetof(UABP_GenericItem_AnimLayerBase_C, AnimGraphNode_ApplyMeshSpaceAdditive_1) == 0x0054D8, "Member 'UABP_GenericItem_AnimLayerBase_C::AnimGraphNode_ApplyMeshSpaceAdditive_1' has a wrong offset!");
static_assert(offsetof(UABP_GenericItem_AnimLayerBase_C, AnimGraphNode_TwoWayBlend_5) == 0x0055A8, "Member 'UABP_GenericItem_AnimLayerBase_C::AnimGraphNode_TwoWayBlend_5' has a wrong offset!");
static_assert(offsetof(UABP_GenericItem_AnimLayerBase_C, AnimGraphNode_BlendListByEnum_5) == 0x005670, "Member 'UABP_GenericItem_AnimLayerBase_C::AnimGraphNode_BlendListByEnum_5' has a wrong offset!");
static_assert(offsetof(UABP_GenericItem_AnimLayerBase_C, AnimGraphNode_BlendListByEnum_4) == 0x005720, "Member 'UABP_GenericItem_AnimLayerBase_C::AnimGraphNode_BlendListByEnum_4' has a wrong offset!");
static_assert(offsetof(UABP_GenericItem_AnimLayerBase_C, AnimGraphNode_Root_3) == 0x0057D0, "Member 'UABP_GenericItem_AnimLayerBase_C::AnimGraphNode_Root_3' has a wrong offset!");
static_assert(offsetof(UABP_GenericItem_AnimLayerBase_C, AnimGraphNode_ApplyMeshSpaceAdditive) == 0x005800, "Member 'UABP_GenericItem_AnimLayerBase_C::AnimGraphNode_ApplyMeshSpaceAdditive' has a wrong offset!");
static_assert(offsetof(UABP_GenericItem_AnimLayerBase_C, AnimGraphNode_TwoWayBlend_4) == 0x0058D0, "Member 'UABP_GenericItem_AnimLayerBase_C::AnimGraphNode_TwoWayBlend_4' has a wrong offset!");
static_assert(offsetof(UABP_GenericItem_AnimLayerBase_C, AnimGraphNode_SequenceEvaluator_3) == 0x005998, "Member 'UABP_GenericItem_AnimLayerBase_C::AnimGraphNode_SequenceEvaluator_3' has a wrong offset!");
static_assert(offsetof(UABP_GenericItem_AnimLayerBase_C, AnimGraphNode_UseCachedPose_2) == 0x0059E8, "Member 'UABP_GenericItem_AnimLayerBase_C::AnimGraphNode_UseCachedPose_2' has a wrong offset!");
static_assert(offsetof(UABP_GenericItem_AnimLayerBase_C, AnimGraphNode_SequenceEvaluator_2) == 0x005A10, "Member 'UABP_GenericItem_AnimLayerBase_C::AnimGraphNode_SequenceEvaluator_2' has a wrong offset!");
static_assert(offsetof(UABP_GenericItem_AnimLayerBase_C, AnimGraphNode_ControlRig) == 0x005A60, "Member 'UABP_GenericItem_AnimLayerBase_C::AnimGraphNode_ControlRig' has a wrong offset!");
static_assert(offsetof(UABP_GenericItem_AnimLayerBase_C, AnimGraphNode_LayeredBoneBlend) == 0x005DC8, "Member 'UABP_GenericItem_AnimLayerBase_C::AnimGraphNode_LayeredBoneBlend' has a wrong offset!");
static_assert(offsetof(UABP_GenericItem_AnimLayerBase_C, AnimGraphNode_TwoWayBlend_3) == 0x005E88, "Member 'UABP_GenericItem_AnimLayerBase_C::AnimGraphNode_TwoWayBlend_3' has a wrong offset!");
static_assert(offsetof(UABP_GenericItem_AnimLayerBase_C, AnimGraphNode_SaveCachedPose) == 0x005F50, "Member 'UABP_GenericItem_AnimLayerBase_C::AnimGraphNode_SaveCachedPose' has a wrong offset!");
static_assert(offsetof(UABP_GenericItem_AnimLayerBase_C, AnimGraphNode_UseCachedPose_1) == 0x0060A8, "Member 'UABP_GenericItem_AnimLayerBase_C::AnimGraphNode_UseCachedPose_1' has a wrong offset!");
static_assert(offsetof(UABP_GenericItem_AnimLayerBase_C, AnimGraphNode_UseCachedPose) == 0x0060D0, "Member 'UABP_GenericItem_AnimLayerBase_C::AnimGraphNode_UseCachedPose' has a wrong offset!");
static_assert(offsetof(UABP_GenericItem_AnimLayerBase_C, AnimGraphNode_SequenceEvaluator_1) == 0x0060F8, "Member 'UABP_GenericItem_AnimLayerBase_C::AnimGraphNode_SequenceEvaluator_1' has a wrong offset!");
static_assert(offsetof(UABP_GenericItem_AnimLayerBase_C, AnimGraphNode_SequenceEvaluator) == 0x006148, "Member 'UABP_GenericItem_AnimLayerBase_C::AnimGraphNode_SequenceEvaluator' has a wrong offset!");
static_assert(offsetof(UABP_GenericItem_AnimLayerBase_C, AnimGraphNode_TwoWayBlend_2) == 0x006198, "Member 'UABP_GenericItem_AnimLayerBase_C::AnimGraphNode_TwoWayBlend_2' has a wrong offset!");
static_assert(offsetof(UABP_GenericItem_AnimLayerBase_C, AnimGraphNode_LocalToComponentSpace_1) == 0x006260, "Member 'UABP_GenericItem_AnimLayerBase_C::AnimGraphNode_LocalToComponentSpace_1' has a wrong offset!");
static_assert(offsetof(UABP_GenericItem_AnimLayerBase_C, AnimGraphNode_CopyBone_3) == 0x006280, "Member 'UABP_GenericItem_AnimLayerBase_C::AnimGraphNode_CopyBone_3' has a wrong offset!");
static_assert(offsetof(UABP_GenericItem_AnimLayerBase_C, AnimGraphNode_CopyBone_2) == 0x006370, "Member 'UABP_GenericItem_AnimLayerBase_C::AnimGraphNode_CopyBone_2' has a wrong offset!");
static_assert(offsetof(UABP_GenericItem_AnimLayerBase_C, AnimGraphNode_ComponentToLocalSpace_1) == 0x006460, "Member 'UABP_GenericItem_AnimLayerBase_C::AnimGraphNode_ComponentToLocalSpace_1' has a wrong offset!");
static_assert(offsetof(UABP_GenericItem_AnimLayerBase_C, AnimGraphNode_LocalToComponentSpace) == 0x006480, "Member 'UABP_GenericItem_AnimLayerBase_C::AnimGraphNode_LocalToComponentSpace' has a wrong offset!");
static_assert(offsetof(UABP_GenericItem_AnimLayerBase_C, AnimGraphNode_CopyBone_1) == 0x0064A0, "Member 'UABP_GenericItem_AnimLayerBase_C::AnimGraphNode_CopyBone_1' has a wrong offset!");
static_assert(offsetof(UABP_GenericItem_AnimLayerBase_C, AnimGraphNode_CopyBone) == 0x006590, "Member 'UABP_GenericItem_AnimLayerBase_C::AnimGraphNode_CopyBone' has a wrong offset!");
static_assert(offsetof(UABP_GenericItem_AnimLayerBase_C, AnimGraphNode_ComponentToLocalSpace) == 0x006680, "Member 'UABP_GenericItem_AnimLayerBase_C::AnimGraphNode_ComponentToLocalSpace' has a wrong offset!");
static_assert(offsetof(UABP_GenericItem_AnimLayerBase_C, AnimGraphNode_Root_2) == 0x0066A0, "Member 'UABP_GenericItem_AnimLayerBase_C::AnimGraphNode_Root_2' has a wrong offset!");
static_assert(offsetof(UABP_GenericItem_AnimLayerBase_C, AnimGraphNode_SequencePlayer_33) == 0x0066D0, "Member 'UABP_GenericItem_AnimLayerBase_C::AnimGraphNode_SequencePlayer_33' has a wrong offset!");
static_assert(offsetof(UABP_GenericItem_AnimLayerBase_C, AnimGraphNode_SequencePlayer_32) == 0x006750, "Member 'UABP_GenericItem_AnimLayerBase_C::AnimGraphNode_SequencePlayer_32' has a wrong offset!");
static_assert(offsetof(UABP_GenericItem_AnimLayerBase_C, AnimGraphNode_TwoWayBlend_1) == 0x0067D0, "Member 'UABP_GenericItem_AnimLayerBase_C::AnimGraphNode_TwoWayBlend_1' has a wrong offset!");
static_assert(offsetof(UABP_GenericItem_AnimLayerBase_C, AnimGraphNode_Root_1) == 0x006898, "Member 'UABP_GenericItem_AnimLayerBase_C::AnimGraphNode_Root_1' has a wrong offset!");
static_assert(offsetof(UABP_GenericItem_AnimLayerBase_C, AnimGraphNode_BlendListByBool_1) == 0x0068C8, "Member 'UABP_GenericItem_AnimLayerBase_C::AnimGraphNode_BlendListByBool_1' has a wrong offset!");
static_assert(offsetof(UABP_GenericItem_AnimLayerBase_C, AnimGraphNode_BlendListByBool) == 0x006968, "Member 'UABP_GenericItem_AnimLayerBase_C::AnimGraphNode_BlendListByBool' has a wrong offset!");
static_assert(offsetof(UABP_GenericItem_AnimLayerBase_C, AnimGraphNode_BlendListByEnum_3) == 0x006A08, "Member 'UABP_GenericItem_AnimLayerBase_C::AnimGraphNode_BlendListByEnum_3' has a wrong offset!");
static_assert(offsetof(UABP_GenericItem_AnimLayerBase_C, AnimGraphNode_BlendListByEnum_2) == 0x006AB8, "Member 'UABP_GenericItem_AnimLayerBase_C::AnimGraphNode_BlendListByEnum_2' has a wrong offset!");
static_assert(offsetof(UABP_GenericItem_AnimLayerBase_C, AnimGraphNode_BlendListByEnum_1) == 0x006B68, "Member 'UABP_GenericItem_AnimLayerBase_C::AnimGraphNode_BlendListByEnum_1' has a wrong offset!");
static_assert(offsetof(UABP_GenericItem_AnimLayerBase_C, AnimGraphNode_BlendListByEnum) == 0x006C18, "Member 'UABP_GenericItem_AnimLayerBase_C::AnimGraphNode_BlendListByEnum' has a wrong offset!");
static_assert(offsetof(UABP_GenericItem_AnimLayerBase_C, AnimGraphNode_TwoWayBlend) == 0x006CC8, "Member 'UABP_GenericItem_AnimLayerBase_C::AnimGraphNode_TwoWayBlend' has a wrong offset!");
static_assert(offsetof(UABP_GenericItem_AnimLayerBase_C, AnimGraphNode_SequencePlayer_31) == 0x006D90, "Member 'UABP_GenericItem_AnimLayerBase_C::AnimGraphNode_SequencePlayer_31' has a wrong offset!");
static_assert(offsetof(UABP_GenericItem_AnimLayerBase_C, AnimGraphNode_SequencePlayer_30) == 0x006E10, "Member 'UABP_GenericItem_AnimLayerBase_C::AnimGraphNode_SequencePlayer_30' has a wrong offset!");
static_assert(offsetof(UABP_GenericItem_AnimLayerBase_C, AnimGraphNode_SequencePlayer_29) == 0x006E90, "Member 'UABP_GenericItem_AnimLayerBase_C::AnimGraphNode_SequencePlayer_29' has a wrong offset!");
static_assert(offsetof(UABP_GenericItem_AnimLayerBase_C, AnimGraphNode_SequencePlayer_28) == 0x006F10, "Member 'UABP_GenericItem_AnimLayerBase_C::AnimGraphNode_SequencePlayer_28' has a wrong offset!");
static_assert(offsetof(UABP_GenericItem_AnimLayerBase_C, AnimGraphNode_SequencePlayer_27) == 0x006F90, "Member 'UABP_GenericItem_AnimLayerBase_C::AnimGraphNode_SequencePlayer_27' has a wrong offset!");
static_assert(offsetof(UABP_GenericItem_AnimLayerBase_C, AnimGraphNode_SequencePlayer_26) == 0x007010, "Member 'UABP_GenericItem_AnimLayerBase_C::AnimGraphNode_SequencePlayer_26' has a wrong offset!");
static_assert(offsetof(UABP_GenericItem_AnimLayerBase_C, AnimGraphNode_SequencePlayer_25) == 0x007090, "Member 'UABP_GenericItem_AnimLayerBase_C::AnimGraphNode_SequencePlayer_25' has a wrong offset!");
static_assert(offsetof(UABP_GenericItem_AnimLayerBase_C, AnimGraphNode_SequencePlayer_24) == 0x007110, "Member 'UABP_GenericItem_AnimLayerBase_C::AnimGraphNode_SequencePlayer_24' has a wrong offset!");
static_assert(offsetof(UABP_GenericItem_AnimLayerBase_C, AnimGraphNode_SequencePlayer_23) == 0x007190, "Member 'UABP_GenericItem_AnimLayerBase_C::AnimGraphNode_SequencePlayer_23' has a wrong offset!");
static_assert(offsetof(UABP_GenericItem_AnimLayerBase_C, AnimGraphNode_SequencePlayer_22) == 0x007210, "Member 'UABP_GenericItem_AnimLayerBase_C::AnimGraphNode_SequencePlayer_22' has a wrong offset!");
static_assert(offsetof(UABP_GenericItem_AnimLayerBase_C, AnimGraphNode_SequencePlayer_21) == 0x007290, "Member 'UABP_GenericItem_AnimLayerBase_C::AnimGraphNode_SequencePlayer_21' has a wrong offset!");
static_assert(offsetof(UABP_GenericItem_AnimLayerBase_C, AnimGraphNode_SequencePlayer_20) == 0x007310, "Member 'UABP_GenericItem_AnimLayerBase_C::AnimGraphNode_SequencePlayer_20' has a wrong offset!");
static_assert(offsetof(UABP_GenericItem_AnimLayerBase_C, AnimGraphNode_SequencePlayer_19) == 0x007390, "Member 'UABP_GenericItem_AnimLayerBase_C::AnimGraphNode_SequencePlayer_19' has a wrong offset!");
static_assert(offsetof(UABP_GenericItem_AnimLayerBase_C, AnimGraphNode_SequencePlayer_18) == 0x007410, "Member 'UABP_GenericItem_AnimLayerBase_C::AnimGraphNode_SequencePlayer_18' has a wrong offset!");
static_assert(offsetof(UABP_GenericItem_AnimLayerBase_C, AnimGraphNode_SequencePlayer_17) == 0x007490, "Member 'UABP_GenericItem_AnimLayerBase_C::AnimGraphNode_SequencePlayer_17' has a wrong offset!");
static_assert(offsetof(UABP_GenericItem_AnimLayerBase_C, AnimGraphNode_SequencePlayer_16) == 0x007510, "Member 'UABP_GenericItem_AnimLayerBase_C::AnimGraphNode_SequencePlayer_16' has a wrong offset!");
static_assert(offsetof(UABP_GenericItem_AnimLayerBase_C, AnimGraphNode_SequencePlayer_15) == 0x007590, "Member 'UABP_GenericItem_AnimLayerBase_C::AnimGraphNode_SequencePlayer_15' has a wrong offset!");
static_assert(offsetof(UABP_GenericItem_AnimLayerBase_C, AnimGraphNode_SequencePlayer_14) == 0x007610, "Member 'UABP_GenericItem_AnimLayerBase_C::AnimGraphNode_SequencePlayer_14' has a wrong offset!");
static_assert(offsetof(UABP_GenericItem_AnimLayerBase_C, AnimGraphNode_SequencePlayer_13) == 0x007690, "Member 'UABP_GenericItem_AnimLayerBase_C::AnimGraphNode_SequencePlayer_13' has a wrong offset!");
static_assert(offsetof(UABP_GenericItem_AnimLayerBase_C, AnimGraphNode_SequencePlayer_12) == 0x007710, "Member 'UABP_GenericItem_AnimLayerBase_C::AnimGraphNode_SequencePlayer_12' has a wrong offset!");
static_assert(offsetof(UABP_GenericItem_AnimLayerBase_C, AnimGraphNode_SequencePlayer_11) == 0x007790, "Member 'UABP_GenericItem_AnimLayerBase_C::AnimGraphNode_SequencePlayer_11' has a wrong offset!");
static_assert(offsetof(UABP_GenericItem_AnimLayerBase_C, AnimGraphNode_SequencePlayer_10) == 0x007810, "Member 'UABP_GenericItem_AnimLayerBase_C::AnimGraphNode_SequencePlayer_10' has a wrong offset!");
static_assert(offsetof(UABP_GenericItem_AnimLayerBase_C, AnimGraphNode_SequencePlayer_9) == 0x007890, "Member 'UABP_GenericItem_AnimLayerBase_C::AnimGraphNode_SequencePlayer_9' has a wrong offset!");
static_assert(offsetof(UABP_GenericItem_AnimLayerBase_C, AnimGraphNode_SequencePlayer_8) == 0x007910, "Member 'UABP_GenericItem_AnimLayerBase_C::AnimGraphNode_SequencePlayer_8' has a wrong offset!");
static_assert(offsetof(UABP_GenericItem_AnimLayerBase_C, AnimGraphNode_SequencePlayer_7) == 0x007990, "Member 'UABP_GenericItem_AnimLayerBase_C::AnimGraphNode_SequencePlayer_7' has a wrong offset!");
static_assert(offsetof(UABP_GenericItem_AnimLayerBase_C, AnimGraphNode_SequencePlayer_6) == 0x007A10, "Member 'UABP_GenericItem_AnimLayerBase_C::AnimGraphNode_SequencePlayer_6' has a wrong offset!");
static_assert(offsetof(UABP_GenericItem_AnimLayerBase_C, AnimGraphNode_SequencePlayer_5) == 0x007A90, "Member 'UABP_GenericItem_AnimLayerBase_C::AnimGraphNode_SequencePlayer_5' has a wrong offset!");
static_assert(offsetof(UABP_GenericItem_AnimLayerBase_C, AnimGraphNode_SequencePlayer_4) == 0x007B10, "Member 'UABP_GenericItem_AnimLayerBase_C::AnimGraphNode_SequencePlayer_4' has a wrong offset!");
static_assert(offsetof(UABP_GenericItem_AnimLayerBase_C, AnimGraphNode_SequencePlayer_3) == 0x007B90, "Member 'UABP_GenericItem_AnimLayerBase_C::AnimGraphNode_SequencePlayer_3' has a wrong offset!");
static_assert(offsetof(UABP_GenericItem_AnimLayerBase_C, AnimGraphNode_SequencePlayer_2) == 0x007C10, "Member 'UABP_GenericItem_AnimLayerBase_C::AnimGraphNode_SequencePlayer_2' has a wrong offset!");
static_assert(offsetof(UABP_GenericItem_AnimLayerBase_C, AnimGraphNode_SequencePlayer_1) == 0x007C90, "Member 'UABP_GenericItem_AnimLayerBase_C::AnimGraphNode_SequencePlayer_1' has a wrong offset!");
static_assert(offsetof(UABP_GenericItem_AnimLayerBase_C, AnimGraphNode_SequencePlayer) == 0x007D10, "Member 'UABP_GenericItem_AnimLayerBase_C::AnimGraphNode_SequencePlayer' has a wrong offset!");
static_assert(offsetof(UABP_GenericItem_AnimLayerBase_C, AnimGraphNode_Root) == 0x007D90, "Member 'UABP_GenericItem_AnimLayerBase_C::AnimGraphNode_Root' has a wrong offset!");
static_assert(offsetof(UABP_GenericItem_AnimLayerBase_C, __CustomProperty_RotationalInertiaOffset_1CDC39C9FFC742B8AD857B7C38E95464) == 0x007DC0, "Member 'UABP_GenericItem_AnimLayerBase_C::__CustomProperty_RotationalInertiaOffset_1CDC39C9FFC742B8AD857B7C38E95464' has a wrong offset!");
static_assert(offsetof(UABP_GenericItem_AnimLayerBase_C, __CustomProperty_bRunning_1CDC39C9FFC742B8AD857B7C38E95464) == 0x007DCC, "Member 'UABP_GenericItem_AnimLayerBase_C::__CustomProperty_bRunning_1CDC39C9FFC742B8AD857B7C38E95464' has a wrong offset!");
static_assert(offsetof(UABP_GenericItem_AnimLayerBase_C, __CustomProperty_bApplyMovementSway_1CDC39C9FFC742B8AD857B7C38E95464) == 0x007DCD, "Member 'UABP_GenericItem_AnimLayerBase_C::__CustomProperty_bApplyMovementSway_1CDC39C9FFC742B8AD857B7C38E95464' has a wrong offset!");
static_assert(offsetof(UABP_GenericItem_AnimLayerBase_C, Idle_Prone) == 0x007DD0, "Member 'UABP_GenericItem_AnimLayerBase_C::Idle_Prone' has a wrong offset!");
static_assert(offsetof(UABP_GenericItem_AnimLayerBase_C, Idle_Crouch) == 0x007DD8, "Member 'UABP_GenericItem_AnimLayerBase_C::Idle_Crouch' has a wrong offset!");
static_assert(offsetof(UABP_GenericItem_AnimLayerBase_C, Idle_Stand) == 0x007DE0, "Member 'UABP_GenericItem_AnimLayerBase_C::Idle_Stand' has a wrong offset!");
static_assert(offsetof(UABP_GenericItem_AnimLayerBase_C, BaseABPRef) == 0x007DE8, "Member 'UABP_GenericItem_AnimLayerBase_C::BaseABPRef' has a wrong offset!");
static_assert(offsetof(UABP_GenericItem_AnimLayerBase_C, StrideWarpingCycleAlpha) == 0x007DF0, "Member 'UABP_GenericItem_AnimLayerBase_C::StrideWarpingCycleAlpha' has a wrong offset!");
static_assert(offsetof(UABP_GenericItem_AnimLayerBase_C, OrientationAngle) == 0x007DF4, "Member 'UABP_GenericItem_AnimLayerBase_C::OrientationAngle' has a wrong offset!");
static_assert(offsetof(UABP_GenericItem_AnimLayerBase_C, LocomotionAngleDeltaThreshold) == 0x007DF8, "Member 'UABP_GenericItem_AnimLayerBase_C::LocomotionAngleDeltaThreshold' has a wrong offset!");
static_assert(offsetof(UABP_GenericItem_AnimLayerBase_C, EyeRightOffset) == 0x007DFC, "Member 'UABP_GenericItem_AnimLayerBase_C::EyeRightOffset' has a wrong offset!");
static_assert(offsetof(UABP_GenericItem_AnimLayerBase_C, EyeLeftOffset) == 0x007E08, "Member 'UABP_GenericItem_AnimLayerBase_C::EyeLeftOffset' has a wrong offset!");
static_assert(offsetof(UABP_GenericItem_AnimLayerBase_C, CollisionTraceEndOffset) == 0x007E14, "Member 'UABP_GenericItem_AnimLayerBase_C::CollisionTraceEndOffset' has a wrong offset!");
static_assert(offsetof(UABP_GenericItem_AnimLayerBase_C, EngagedAlpha) == 0x007E20, "Member 'UABP_GenericItem_AnimLayerBase_C::EngagedAlpha' has a wrong offset!");
static_assert(offsetof(UABP_GenericItem_AnimLayerBase_C, OffTargetAlpha) == 0x007E24, "Member 'UABP_GenericItem_AnimLayerBase_C::OffTargetAlpha' has a wrong offset!");
static_assert(offsetof(UABP_GenericItem_AnimLayerBase_C, AimOffsetProne) == 0x007E28, "Member 'UABP_GenericItem_AnimLayerBase_C::AimOffsetProne' has a wrong offset!");
static_assert(offsetof(UABP_GenericItem_AnimLayerBase_C, AimOffsetCrouch) == 0x007E30, "Member 'UABP_GenericItem_AnimLayerBase_C::AimOffsetCrouch' has a wrong offset!");
static_assert(offsetof(UABP_GenericItem_AnimLayerBase_C, AimOffsetStand) == 0x007E38, "Member 'UABP_GenericItem_AnimLayerBase_C::AimOffsetStand' has a wrong offset!");
static_assert(offsetof(UABP_GenericItem_AnimLayerBase_C, LowReadyHighExplicitTime) == 0x007E40, "Member 'UABP_GenericItem_AnimLayerBase_C::LowReadyHighExplicitTime' has a wrong offset!");
static_assert(offsetof(UABP_GenericItem_AnimLayerBase_C, PrevOffTargetAlpha) == 0x007E44, "Member 'UABP_GenericItem_AnimLayerBase_C::PrevOffTargetAlpha' has a wrong offset!");
static_assert(offsetof(UABP_GenericItem_AnimLayerBase_C, LowHighAlpha) == 0x007E48, "Member 'UABP_GenericItem_AnimLayerBase_C::LowHighAlpha' has a wrong offset!");
static_assert(offsetof(UABP_GenericItem_AnimLayerBase_C, DirectionBlendTime) == 0x007E4C, "Member 'UABP_GenericItem_AnimLayerBase_C::DirectionBlendTime' has a wrong offset!");
static_assert(offsetof(UABP_GenericItem_AnimLayerBase_C, TwoHandAlpha) == 0x007E50, "Member 'UABP_GenericItem_AnimLayerBase_C::TwoHandAlpha' has a wrong offset!");
static_assert(offsetof(UABP_GenericItem_AnimLayerBase_C, bTwoHandsOnItem) == 0x007E54, "Member 'UABP_GenericItem_AnimLayerBase_C::bTwoHandsOnItem' has a wrong offset!");
static_assert(offsetof(UABP_GenericItem_AnimLayerBase_C, ProneReadyEngagedAdditivePose) == 0x007E58, "Member 'UABP_GenericItem_AnimLayerBase_C::ProneReadyEngagedAdditivePose' has a wrong offset!");
static_assert(offsetof(UABP_GenericItem_AnimLayerBase_C, CrouchReadyEngagedAdditivePose) == 0x007E60, "Member 'UABP_GenericItem_AnimLayerBase_C::CrouchReadyEngagedAdditivePose' has a wrong offset!");
static_assert(offsetof(UABP_GenericItem_AnimLayerBase_C, StandReadyEngagedAdditivePose) == 0x007E68, "Member 'UABP_GenericItem_AnimLayerBase_C::StandReadyEngagedAdditivePose' has a wrong offset!");
static_assert(offsetof(UABP_GenericItem_AnimLayerBase_C, Sprint_Crouch) == 0x007E70, "Member 'UABP_GenericItem_AnimLayerBase_C::Sprint_Crouch' has a wrong offset!");
static_assert(offsetof(UABP_GenericItem_AnimLayerBase_C, Sprint_Stand) == 0x007EB0, "Member 'UABP_GenericItem_AnimLayerBase_C::Sprint_Stand' has a wrong offset!");
static_assert(offsetof(UABP_GenericItem_AnimLayerBase_C, Walk_Prone) == 0x007EF0, "Member 'UABP_GenericItem_AnimLayerBase_C::Walk_Prone' has a wrong offset!");
static_assert(offsetof(UABP_GenericItem_AnimLayerBase_C, Walk_Crouch) == 0x007F30, "Member 'UABP_GenericItem_AnimLayerBase_C::Walk_Crouch' has a wrong offset!");
static_assert(offsetof(UABP_GenericItem_AnimLayerBase_C, Walk_Stand) == 0x007F70, "Member 'UABP_GenericItem_AnimLayerBase_C::Walk_Stand' has a wrong offset!");
static_assert(offsetof(UABP_GenericItem_AnimLayerBase_C, Run_Prone) == 0x007FB0, "Member 'UABP_GenericItem_AnimLayerBase_C::Run_Prone' has a wrong offset!");
static_assert(offsetof(UABP_GenericItem_AnimLayerBase_C, Run_Crouch) == 0x007FB8, "Member 'UABP_GenericItem_AnimLayerBase_C::Run_Crouch' has a wrong offset!");
static_assert(offsetof(UABP_GenericItem_AnimLayerBase_C, Run_Stand) == 0x007FF8, "Member 'UABP_GenericItem_AnimLayerBase_C::Run_Stand' has a wrong offset!");
static_assert(offsetof(UABP_GenericItem_AnimLayerBase_C, ProneToStand) == 0x008038, "Member 'UABP_GenericItem_AnimLayerBase_C::ProneToStand' has a wrong offset!");
static_assert(offsetof(UABP_GenericItem_AnimLayerBase_C, ProneToCrouch) == 0x008040, "Member 'UABP_GenericItem_AnimLayerBase_C::ProneToCrouch' has a wrong offset!");
static_assert(offsetof(UABP_GenericItem_AnimLayerBase_C, StandToProne) == 0x008048, "Member 'UABP_GenericItem_AnimLayerBase_C::StandToProne' has a wrong offset!");
static_assert(offsetof(UABP_GenericItem_AnimLayerBase_C, CrouchToProne) == 0x008050, "Member 'UABP_GenericItem_AnimLayerBase_C::CrouchToProne' has a wrong offset!");
static_assert(offsetof(UABP_GenericItem_AnimLayerBase_C, SprintToProne) == 0x008058, "Member 'UABP_GenericItem_AnimLayerBase_C::SprintToProne' has a wrong offset!");
static_assert(offsetof(UABP_GenericItem_AnimLayerBase_C, ProneTurnLeft) == 0x008060, "Member 'UABP_GenericItem_AnimLayerBase_C::ProneTurnLeft' has a wrong offset!");
static_assert(offsetof(UABP_GenericItem_AnimLayerBase_C, ProneTurnRIght) == 0x008068, "Member 'UABP_GenericItem_AnimLayerBase_C::ProneTurnRIght' has a wrong offset!");
static_assert(offsetof(UABP_GenericItem_AnimLayerBase_C, LeanPoses) == 0x008070, "Member 'UABP_GenericItem_AnimLayerBase_C::LeanPoses' has a wrong offset!");
static_assert(offsetof(UABP_GenericItem_AnimLayerBase_C, EngagedRightHandBone) == 0x008078, "Member 'UABP_GenericItem_AnimLayerBase_C::EngagedRightHandBone' has a wrong offset!");
static_assert(offsetof(UABP_GenericItem_AnimLayerBase_C, EngagedDynamicRightHandIKRoot) == 0x00807C, "Member 'UABP_GenericItem_AnimLayerBase_C::EngagedDynamicRightHandIKRoot' has a wrong offset!");
static_assert(offsetof(UABP_GenericItem_AnimLayerBase_C, EngagedDynamicLeftHandIKRoot) == 0x008084, "Member 'UABP_GenericItem_AnimLayerBase_C::EngagedDynamicLeftHandIKRoot' has a wrong offset!");
static_assert(offsetof(UABP_GenericItem_AnimLayerBase_C, Movement_Sway_Walk_Pitch) == 0x00808C, "Member 'UABP_GenericItem_AnimLayerBase_C::Movement_Sway_Walk_Pitch' has a wrong offset!");
static_assert(offsetof(UABP_GenericItem_AnimLayerBase_C, Movement_Sway_Walk_Yaw) == 0x008090, "Member 'UABP_GenericItem_AnimLayerBase_C::Movement_Sway_Walk_Yaw' has a wrong offset!");
static_assert(offsetof(UABP_GenericItem_AnimLayerBase_C, Movement_Sway_Run_Pitch) == 0x008094, "Member 'UABP_GenericItem_AnimLayerBase_C::Movement_Sway_Run_Pitch' has a wrong offset!");
static_assert(offsetof(UABP_GenericItem_AnimLayerBase_C, Movement_Sway_Run_Yaw) == 0x008098, "Member 'UABP_GenericItem_AnimLayerBase_C::Movement_Sway_Run_Yaw' has a wrong offset!");
static_assert(offsetof(UABP_GenericItem_AnimLayerBase_C, NVGFlipDownMontage) == 0x0080A0, "Member 'UABP_GenericItem_AnimLayerBase_C::NVGFlipDownMontage' has a wrong offset!");
static_assert(offsetof(UABP_GenericItem_AnimLayerBase_C, NVGFlipUpMontage) == 0x0080A8, "Member 'UABP_GenericItem_AnimLayerBase_C::NVGFlipUpMontage' has a wrong offset!");
static_assert(offsetof(UABP_GenericItem_AnimLayerBase_C, WatchCheck) == 0x0080B0, "Member 'UABP_GenericItem_AnimLayerBase_C::WatchCheck' has a wrong offset!");
static_assert(offsetof(UABP_GenericItem_AnimLayerBase_C, WatchCheckProne) == 0x0080B8, "Member 'UABP_GenericItem_AnimLayerBase_C::WatchCheckProne' has a wrong offset!");

}

