#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ABP_Base

#include "Basic.hpp"

#include "CoreUObject_structs.hpp"
#include "DistanceMatching_structs.hpp"
#include "ControlRig_structs.hpp"
#include "Engine_structs.hpp"
#include "AnimGraphRuntime_structs.hpp"
#include "GroundBranch_classes.hpp"


namespace SDK
{

// AnimBlueprintGeneratedClass ABP_Base.ABP_Base_C
// 0x45A0 (0x5230 - 0x0C90)
class UABP_Base_C final : public UGBCharAnimInstance
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0C90(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	struct FAnimNode_ApplyAdditive                AnimGraphNode_ApplyAdditive_1;                     // 0x0C98(0x00C8)()
	struct FAnimNode_LinkedAnimLayer              AnimGraphNode_LinkedAnimLayer_9;                   // 0x0D60(0x00B0)()
	struct FAnimNode_Slot                         AnimGraphNode_Slot_6;                              // 0x0E10(0x0048)()
	struct FAnimNode_SaveCachedPose               AnimGraphNode_SaveCachedPose_6;                    // 0x0E58(0x0158)()
	struct FAnimNode_UseCachedPose                AnimGraphNode_UseCachedPose_15;                    // 0x0FB0(0x0028)()
	struct FAnimNode_LayeredBoneBlend             AnimGraphNode_LayeredBoneBlend_8;                  // 0x0FD8(0x00C0)()
	struct FAnimNode_Slot                         AnimGraphNode_Slot_5;                              // 0x1098(0x0048)()
	struct FAnimNode_RefPose                      AnimGraphNode_IdentityPose;                        // 0x10E0(0x0018)()
	struct FAnimNode_SaveCachedPose               AnimGraphNode_SaveCachedPose_5;                    // 0x10F8(0x0158)()
	struct FAnimNode_UseCachedPose                AnimGraphNode_UseCachedPose_14;                    // 0x1250(0x0028)()
	struct FAnimNode_ApplyAdditive                AnimGraphNode_ApplyAdditive;                       // 0x1278(0x00C8)()
	struct FAnimNode_Slot                         AnimGraphNode_Slot_4;                              // 0x1340(0x0048)()
	struct FAnimNode_UseCachedPose                AnimGraphNode_UseCachedPose_13;                    // 0x1388(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_12;                 // 0x13B0(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_11;                 // 0x13D8(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_10;                 // 0x1400(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_9;                  // 0x1428(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_8;                  // 0x1450(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_7;                  // 0x1478(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_6;                  // 0x14A0(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_5;                  // 0x14C8(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_4;                  // 0x14F0(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_3;                  // 0x1518(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_2;                  // 0x1540(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_1;                  // 0x1568(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult;                    // 0x1590(0x0028)()
	struct FAnimNode_DistanceMatching             AnimGraphNode_DistanceMatching;                    // 0x15B8(0x0088)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_5;                       // 0x1640(0x0030)()
	struct FAnimNode_LinkedAnimLayer              AnimGraphNode_LinkedAnimLayer_8;                   // 0x1670(0x00B0)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_4;                       // 0x1720(0x0030)()
	struct FAnimNode_LinkedAnimLayer              AnimGraphNode_LinkedAnimLayer_7;                   // 0x1750(0x00B0)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_3;                       // 0x1800(0x0030)()
	struct FAnimNode_LinkedAnimLayer              AnimGraphNode_LinkedAnimLayer_6;                   // 0x1830(0x00B0)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_2;                       // 0x18E0(0x0030)()
	struct FAnimNode_LinkedAnimLayer              AnimGraphNode_LinkedAnimLayer_5;                   // 0x1910(0x00B0)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_1;                       // 0x19C0(0x0030)()
	struct FAnimNode_LinkedAnimLayer              AnimGraphNode_LinkedAnimLayer_4;                   // 0x19F0(0x00B0)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult;                         // 0x1AA0(0x0030)()
	struct FAnimNode_StateMachine                 AnimGraphNode_StateMachine;                        // 0x1AD0(0x00B0)()
	struct FAnimNode_LinkedAnimLayer              AnimGraphNode_LinkedAnimLayer_3;                   // 0x1B80(0x00B0)()
	struct FAnimNode_LinkedAnimLayer              AnimGraphNode_LinkedAnimLayer_2;                   // 0x1C30(0x00B0)()
	struct FAnimNode_ControlRig                   AnimGraphNode_ControlRig_7;                        // 0x1CE0(0x0368)()
	struct FAnimNode_Inertialization              AnimGraphNode_Inertialization;                     // 0x2048(0x0070)()
	struct FAnimNode_UseCachedPose                AnimGraphNode_UseCachedPose_12;                    // 0x20B8(0x0028)()
	struct FAnimNode_LinkedAnimLayer              AnimGraphNode_LinkedAnimLayer_1;                   // 0x20E0(0x00B0)()
	struct FAnimNode_LayeredBoneBlend             AnimGraphNode_LayeredBoneBlend_7;                  // 0x2190(0x00C0)()
	struct FAnimNode_ControlRig                   AnimGraphNode_ControlRig_6;                        // 0x2250(0x0368)()
	struct FAnimNode_UseCachedPose                AnimGraphNode_UseCachedPose_11;                    // 0x25B8(0x0028)()
	struct FAnimNode_LayeredBoneBlend             AnimGraphNode_LayeredBoneBlend_6;                  // 0x25E0(0x00C0)()
	struct FAnimNode_UseCachedPose                AnimGraphNode_UseCachedPose_10;                    // 0x26A0(0x0028)()
	struct FAnimNode_ControlRig                   AnimGraphNode_ControlRig_5;                        // 0x26C8(0x0368)()
	struct FAnimNode_UseCachedPose                AnimGraphNode_UseCachedPose_9;                     // 0x2A30(0x0028)()
	struct FAnimNode_UseCachedPose                AnimGraphNode_UseCachedPose_8;                     // 0x2A58(0x0028)()
	struct FAnimNode_LinkedAnimLayer              AnimGraphNode_LinkedAnimLayer;                     // 0x2A80(0x00B0)()
	struct FAnimNode_ControlRig                   AnimGraphNode_ControlRig_4;                        // 0x2B30(0x0368)()
	struct FAnimNode_Slot                         AnimGraphNode_Slot_3;                              // 0x2E98(0x0048)()
	struct FAnimNode_Root                         AnimGraphNode_Root_10;                             // 0x2EE0(0x0030)()
	struct FAnimNode_ControlRig                   AnimGraphNode_ControlRig_3;                        // 0x2F10(0x0368)()
	struct FAnimNode_TwoWayBlend                  AnimGraphNode_TwoWayBlend;                         // 0x3278(0x00C8)()
	struct FAnimNode_Slot                         AnimGraphNode_Slot_2;                              // 0x3340(0x0048)()
	struct FAnimNode_LayeredBoneBlend             AnimGraphNode_LayeredBoneBlend_5;                  // 0x3388(0x00C0)()
	struct FAnimNode_SaveCachedPose               AnimGraphNode_SaveCachedPose_4;                    // 0x3448(0x0158)()
	struct FAnimNode_LinkedInputPose              AnimGraphNode_LinkedInputPose_3;                   // 0x35A0(0x0118)()
	struct FAnimNode_Root                         AnimGraphNode_Root_9;                              // 0x36B8(0x0030)()
	struct FAnimNode_SaveCachedPose               AnimGraphNode_SaveCachedPose_3;                    // 0x36E8(0x0158)()
	struct FAnimNode_UseCachedPose                AnimGraphNode_UseCachedPose_7;                     // 0x3840(0x0028)()
	struct FAnimNode_UseCachedPose                AnimGraphNode_UseCachedPose_6;                     // 0x3868(0x0028)()
	struct FAnimNode_Root                         AnimGraphNode_Root_8;                              // 0x3890(0x0030)()
	struct FAnimNode_LayeredBoneBlend             AnimGraphNode_LayeredBoneBlend_4;                  // 0x38C0(0x00C0)()
	struct FAnimNode_RotateRootBone               AnimGraphNode_RotateRootBone;                      // 0x3980(0x00A0)()
	struct FAnimNode_LayeredBoneBlend             AnimGraphNode_LayeredBoneBlend_3;                  // 0x3A20(0x00C0)()
	struct FAnimNode_UseCachedPose                AnimGraphNode_UseCachedPose_5;                     // 0x3AE0(0x0028)()
	struct FAnimNode_ControlRig                   AnimGraphNode_ControlRig_2;                        // 0x3B08(0x0368)()
	struct FAnimNode_SaveCachedPose               AnimGraphNode_SaveCachedPose_2;                    // 0x3E70(0x0158)()
	struct FAnimNode_LinkedInputPose              AnimGraphNode_LinkedInputPose_2;                   // 0x3FC8(0x0118)()
	struct FAnimNode_LayeredBoneBlend             AnimGraphNode_LayeredBoneBlend_2;                  // 0x40E0(0x00C0)()
	struct FAnimNode_Root                         AnimGraphNode_Root_7;                              // 0x41A0(0x0030)()
	struct FAnimNode_LinkedInputPose              AnimGraphNode_LinkedInputPose_1;                   // 0x41D0(0x0118)()
	struct FAnimNode_UseCachedPose                AnimGraphNode_UseCachedPose_4;                     // 0x42E8(0x0028)()
	struct FAnimNode_Root                         AnimGraphNode_Root_6;                              // 0x4310(0x0030)()
	struct FAnimNode_Root                         AnimGraphNode_Root_5;                              // 0x4340(0x0030)()
	struct FAnimNode_Root                         AnimGraphNode_Root_4;                              // 0x4370(0x0030)()
	struct FAnimNode_LinkedInputPose              AnimGraphNode_LinkedInputPose;                     // 0x43A0(0x0118)()
	struct FAnimNode_Root                         AnimGraphNode_Root_3;                              // 0x44B8(0x0030)()
	struct FAnimNode_Slot                         AnimGraphNode_Slot_1;                              // 0x44E8(0x0048)()
	struct FAnimNode_Root                         AnimGraphNode_Root_2;                              // 0x4530(0x0030)()
	struct FAnimNode_LayeredBoneBlend             AnimGraphNode_LayeredBoneBlend_1;                  // 0x4560(0x00C0)()
	struct FAnimNode_UseCachedPose                AnimGraphNode_UseCachedPose_3;                     // 0x4620(0x0028)()
	struct FAnimNode_UseCachedPose                AnimGraphNode_UseCachedPose_2;                     // 0x4648(0x0028)()
	struct FAnimNode_SaveCachedPose               AnimGraphNode_SaveCachedPose_1;                    // 0x4670(0x0158)()
	struct FAnimNode_LayeredBoneBlend             AnimGraphNode_LayeredBoneBlend;                    // 0x47C8(0x00C0)()
	struct FAnimNode_UseCachedPose                AnimGraphNode_UseCachedPose_1;                     // 0x4888(0x0028)()
	struct FAnimNode_UseCachedPose                AnimGraphNode_UseCachedPose;                       // 0x48B0(0x0028)()
	struct FAnimNode_Slot                         AnimGraphNode_Slot;                                // 0x48D8(0x0048)()
	struct FAnimNode_ControlRig                   AnimGraphNode_ControlRig_1;                        // 0x4920(0x0368)()
	struct FAnimNode_ControlRig                   AnimGraphNode_ControlRig;                          // 0x4C88(0x0368)()
	struct FAnimNode_SaveCachedPose               AnimGraphNode_SaveCachedPose;                      // 0x4FF0(0x0158)()
	struct FAnimNode_Root                         AnimGraphNode_Root_1;                              // 0x5148(0x0030)()
	struct FAnimNode_Root                         AnimGraphNode_Root;                                // 0x5178(0x0030)()
	bool                                          K2Node_PropertyAccess_9;                           // 0x51A8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          K2Node_PropertyAccess_8;                           // 0x51A9(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          K2Node_PropertyAccess_7;                           // 0x51AA(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          K2Node_PropertyAccess_6;                           // 0x51AB(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          K2Node_PropertyAccess_5;                           // 0x51AC(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          K2Node_PropertyAccess_4;                           // 0x51AD(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          K2Node_PropertyAccess_3;                           // 0x51AE(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          K2Node_PropertyAccess_2;                           // 0x51AF(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          K2Node_PropertyAccess_1;                           // 0x51B0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          K2Node_PropertyAccess;                             // 0x51B1(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_51B2[0x2];                                     // 0x51B2(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	class FName                                   __CustomProperty_DynamicLeftHandIKRoot_BoneName_F245D82582F44CC58D4CA913D6708A94; // 0x51B4(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FName                                   __CustomProperty_DynamicLeftHandIKRoot_BoneName_129D599A1F25408885024AE111A6A52D; // 0x51BC(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FName                                   __CustomProperty_DynamicLeftHandIKRoot_BoneName_01539DA250DF454DBFB0930F32343253; // 0x51C4(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FName                                   __CustomProperty_DynamicLeftHandIKRoot_BoneName_06C1DCE5E990460EA04EB06737470176; // 0x51CC(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FName                                   __CustomProperty_DynamicRightItemParent_A127D59AE00D4BCE977DB3150B0B88AE; // 0x51D4(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FName                                   __CustomProperty_DynamicRightHandIKParent_CB584B86F3A8460C80FCB8E101D93AA1; // 0x51DC(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FRotator                               __CustomProperty_DynamicLeftHandIKRoot_RotOffset_4C1F2A5C42854D638936F7E321A1DA54; // 0x51E4(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor)
	struct FVector                                __CustomProperty_DynamicLeftHandIKRoot_LocOffset_4C1F2A5C42854D638936F7E321A1DA54; // 0x51F0(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FName                                   __CustomProperty_DynamicLeftHandIKRoot_BoneName_4C1F2A5C42854D638936F7E321A1DA54; // 0x51FC(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FName                                   __CustomProperty_DynamicRightItemRoot_BoneName_CDC0D867E23F4429A518CC1C60D99A80; // 0x5204(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FName                                   __CustomProperty_DynamicRightHandIKRoot_BoneName_CDC0D867E23F4429A518CC1C60D99A80; // 0x520C(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FName                                   __CustomProperty_DynamicLeftHandIKRoot_BoneName_CDC0D867E23F4429A518CC1C60D99A80; // 0x5214(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FRotator                               __CustomProperty_HeadOffset_CDC0D867E23F4429A518CC1C60D99A80; // 0x521C(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor)

public:
	void ExecuteUbergraph_ABP_Base(int32 EntryPoint);
	void AnimNotify_LeftFootDown();
	void AnimNotify_RightFootDown();
	void IdleFullBlendedState();
	void IdleLeftState();
	void AnimGraph(struct FPoseLink* AnimGraph_0);
	void FullBody_SkeletalControls(const struct FPoseLink& InNearFinal, struct FPoseLink* FullBody_SkeletalControls_0);
	void FullBody_Additives(struct FPoseLink* FullBody_Additives_0);
	void FullBody_Aiming(const struct FPoseLink& InUpperbodyLowerbodySplit, struct FPoseLink* FullBody_Aiming_0);
	void HandPose_OverrideState(const struct FPoseLink& InLocomotion, struct FPoseLink* HandPose_OverrideState_0);
	void FullBody_IdleState(struct FPoseLink* FullBody_IdleState_0);
	void FullBody_CycleState(struct FPoseLink* FullBody_CycleState_0);
	void FullBody_PreAim(const struct FPoseLink& InPreAim, struct FPoseLink* FullBody_PreAim_0);
	void FullBody_ProneIdleState(struct FPoseLink* FullBody_ProneIdleState_0);
	void FullBody_ProneCycleState(struct FPoseLink* FullBody_ProneCycleState_0);
	void FullBody_SprintCycleState(struct FPoseLink* FullBody_SprintCycleState_0);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"ABP_Base_C">();
	}
	static class UABP_Base_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UABP_Base_C>();
	}
};
static_assert(alignof(UABP_Base_C) == 0x000010, "Wrong alignment on UABP_Base_C");
static_assert(sizeof(UABP_Base_C) == 0x005230, "Wrong size on UABP_Base_C");
static_assert(offsetof(UABP_Base_C, UberGraphFrame) == 0x000C90, "Member 'UABP_Base_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UABP_Base_C, AnimGraphNode_ApplyAdditive_1) == 0x000C98, "Member 'UABP_Base_C::AnimGraphNode_ApplyAdditive_1' has a wrong offset!");
static_assert(offsetof(UABP_Base_C, AnimGraphNode_LinkedAnimLayer_9) == 0x000D60, "Member 'UABP_Base_C::AnimGraphNode_LinkedAnimLayer_9' has a wrong offset!");
static_assert(offsetof(UABP_Base_C, AnimGraphNode_Slot_6) == 0x000E10, "Member 'UABP_Base_C::AnimGraphNode_Slot_6' has a wrong offset!");
static_assert(offsetof(UABP_Base_C, AnimGraphNode_SaveCachedPose_6) == 0x000E58, "Member 'UABP_Base_C::AnimGraphNode_SaveCachedPose_6' has a wrong offset!");
static_assert(offsetof(UABP_Base_C, AnimGraphNode_UseCachedPose_15) == 0x000FB0, "Member 'UABP_Base_C::AnimGraphNode_UseCachedPose_15' has a wrong offset!");
static_assert(offsetof(UABP_Base_C, AnimGraphNode_LayeredBoneBlend_8) == 0x000FD8, "Member 'UABP_Base_C::AnimGraphNode_LayeredBoneBlend_8' has a wrong offset!");
static_assert(offsetof(UABP_Base_C, AnimGraphNode_Slot_5) == 0x001098, "Member 'UABP_Base_C::AnimGraphNode_Slot_5' has a wrong offset!");
static_assert(offsetof(UABP_Base_C, AnimGraphNode_IdentityPose) == 0x0010E0, "Member 'UABP_Base_C::AnimGraphNode_IdentityPose' has a wrong offset!");
static_assert(offsetof(UABP_Base_C, AnimGraphNode_SaveCachedPose_5) == 0x0010F8, "Member 'UABP_Base_C::AnimGraphNode_SaveCachedPose_5' has a wrong offset!");
static_assert(offsetof(UABP_Base_C, AnimGraphNode_UseCachedPose_14) == 0x001250, "Member 'UABP_Base_C::AnimGraphNode_UseCachedPose_14' has a wrong offset!");
static_assert(offsetof(UABP_Base_C, AnimGraphNode_ApplyAdditive) == 0x001278, "Member 'UABP_Base_C::AnimGraphNode_ApplyAdditive' has a wrong offset!");
static_assert(offsetof(UABP_Base_C, AnimGraphNode_Slot_4) == 0x001340, "Member 'UABP_Base_C::AnimGraphNode_Slot_4' has a wrong offset!");
static_assert(offsetof(UABP_Base_C, AnimGraphNode_UseCachedPose_13) == 0x001388, "Member 'UABP_Base_C::AnimGraphNode_UseCachedPose_13' has a wrong offset!");
static_assert(offsetof(UABP_Base_C, AnimGraphNode_TransitionResult_12) == 0x0013B0, "Member 'UABP_Base_C::AnimGraphNode_TransitionResult_12' has a wrong offset!");
static_assert(offsetof(UABP_Base_C, AnimGraphNode_TransitionResult_11) == 0x0013D8, "Member 'UABP_Base_C::AnimGraphNode_TransitionResult_11' has a wrong offset!");
static_assert(offsetof(UABP_Base_C, AnimGraphNode_TransitionResult_10) == 0x001400, "Member 'UABP_Base_C::AnimGraphNode_TransitionResult_10' has a wrong offset!");
static_assert(offsetof(UABP_Base_C, AnimGraphNode_TransitionResult_9) == 0x001428, "Member 'UABP_Base_C::AnimGraphNode_TransitionResult_9' has a wrong offset!");
static_assert(offsetof(UABP_Base_C, AnimGraphNode_TransitionResult_8) == 0x001450, "Member 'UABP_Base_C::AnimGraphNode_TransitionResult_8' has a wrong offset!");
static_assert(offsetof(UABP_Base_C, AnimGraphNode_TransitionResult_7) == 0x001478, "Member 'UABP_Base_C::AnimGraphNode_TransitionResult_7' has a wrong offset!");
static_assert(offsetof(UABP_Base_C, AnimGraphNode_TransitionResult_6) == 0x0014A0, "Member 'UABP_Base_C::AnimGraphNode_TransitionResult_6' has a wrong offset!");
static_assert(offsetof(UABP_Base_C, AnimGraphNode_TransitionResult_5) == 0x0014C8, "Member 'UABP_Base_C::AnimGraphNode_TransitionResult_5' has a wrong offset!");
static_assert(offsetof(UABP_Base_C, AnimGraphNode_TransitionResult_4) == 0x0014F0, "Member 'UABP_Base_C::AnimGraphNode_TransitionResult_4' has a wrong offset!");
static_assert(offsetof(UABP_Base_C, AnimGraphNode_TransitionResult_3) == 0x001518, "Member 'UABP_Base_C::AnimGraphNode_TransitionResult_3' has a wrong offset!");
static_assert(offsetof(UABP_Base_C, AnimGraphNode_TransitionResult_2) == 0x001540, "Member 'UABP_Base_C::AnimGraphNode_TransitionResult_2' has a wrong offset!");
static_assert(offsetof(UABP_Base_C, AnimGraphNode_TransitionResult_1) == 0x001568, "Member 'UABP_Base_C::AnimGraphNode_TransitionResult_1' has a wrong offset!");
static_assert(offsetof(UABP_Base_C, AnimGraphNode_TransitionResult) == 0x001590, "Member 'UABP_Base_C::AnimGraphNode_TransitionResult' has a wrong offset!");
static_assert(offsetof(UABP_Base_C, AnimGraphNode_DistanceMatching) == 0x0015B8, "Member 'UABP_Base_C::AnimGraphNode_DistanceMatching' has a wrong offset!");
static_assert(offsetof(UABP_Base_C, AnimGraphNode_StateResult_5) == 0x001640, "Member 'UABP_Base_C::AnimGraphNode_StateResult_5' has a wrong offset!");
static_assert(offsetof(UABP_Base_C, AnimGraphNode_LinkedAnimLayer_8) == 0x001670, "Member 'UABP_Base_C::AnimGraphNode_LinkedAnimLayer_8' has a wrong offset!");
static_assert(offsetof(UABP_Base_C, AnimGraphNode_StateResult_4) == 0x001720, "Member 'UABP_Base_C::AnimGraphNode_StateResult_4' has a wrong offset!");
static_assert(offsetof(UABP_Base_C, AnimGraphNode_LinkedAnimLayer_7) == 0x001750, "Member 'UABP_Base_C::AnimGraphNode_LinkedAnimLayer_7' has a wrong offset!");
static_assert(offsetof(UABP_Base_C, AnimGraphNode_StateResult_3) == 0x001800, "Member 'UABP_Base_C::AnimGraphNode_StateResult_3' has a wrong offset!");
static_assert(offsetof(UABP_Base_C, AnimGraphNode_LinkedAnimLayer_6) == 0x001830, "Member 'UABP_Base_C::AnimGraphNode_LinkedAnimLayer_6' has a wrong offset!");
static_assert(offsetof(UABP_Base_C, AnimGraphNode_StateResult_2) == 0x0018E0, "Member 'UABP_Base_C::AnimGraphNode_StateResult_2' has a wrong offset!");
static_assert(offsetof(UABP_Base_C, AnimGraphNode_LinkedAnimLayer_5) == 0x001910, "Member 'UABP_Base_C::AnimGraphNode_LinkedAnimLayer_5' has a wrong offset!");
static_assert(offsetof(UABP_Base_C, AnimGraphNode_StateResult_1) == 0x0019C0, "Member 'UABP_Base_C::AnimGraphNode_StateResult_1' has a wrong offset!");
static_assert(offsetof(UABP_Base_C, AnimGraphNode_LinkedAnimLayer_4) == 0x0019F0, "Member 'UABP_Base_C::AnimGraphNode_LinkedAnimLayer_4' has a wrong offset!");
static_assert(offsetof(UABP_Base_C, AnimGraphNode_StateResult) == 0x001AA0, "Member 'UABP_Base_C::AnimGraphNode_StateResult' has a wrong offset!");
static_assert(offsetof(UABP_Base_C, AnimGraphNode_StateMachine) == 0x001AD0, "Member 'UABP_Base_C::AnimGraphNode_StateMachine' has a wrong offset!");
static_assert(offsetof(UABP_Base_C, AnimGraphNode_LinkedAnimLayer_3) == 0x001B80, "Member 'UABP_Base_C::AnimGraphNode_LinkedAnimLayer_3' has a wrong offset!");
static_assert(offsetof(UABP_Base_C, AnimGraphNode_LinkedAnimLayer_2) == 0x001C30, "Member 'UABP_Base_C::AnimGraphNode_LinkedAnimLayer_2' has a wrong offset!");
static_assert(offsetof(UABP_Base_C, AnimGraphNode_ControlRig_7) == 0x001CE0, "Member 'UABP_Base_C::AnimGraphNode_ControlRig_7' has a wrong offset!");
static_assert(offsetof(UABP_Base_C, AnimGraphNode_Inertialization) == 0x002048, "Member 'UABP_Base_C::AnimGraphNode_Inertialization' has a wrong offset!");
static_assert(offsetof(UABP_Base_C, AnimGraphNode_UseCachedPose_12) == 0x0020B8, "Member 'UABP_Base_C::AnimGraphNode_UseCachedPose_12' has a wrong offset!");
static_assert(offsetof(UABP_Base_C, AnimGraphNode_LinkedAnimLayer_1) == 0x0020E0, "Member 'UABP_Base_C::AnimGraphNode_LinkedAnimLayer_1' has a wrong offset!");
static_assert(offsetof(UABP_Base_C, AnimGraphNode_LayeredBoneBlend_7) == 0x002190, "Member 'UABP_Base_C::AnimGraphNode_LayeredBoneBlend_7' has a wrong offset!");
static_assert(offsetof(UABP_Base_C, AnimGraphNode_ControlRig_6) == 0x002250, "Member 'UABP_Base_C::AnimGraphNode_ControlRig_6' has a wrong offset!");
static_assert(offsetof(UABP_Base_C, AnimGraphNode_UseCachedPose_11) == 0x0025B8, "Member 'UABP_Base_C::AnimGraphNode_UseCachedPose_11' has a wrong offset!");
static_assert(offsetof(UABP_Base_C, AnimGraphNode_LayeredBoneBlend_6) == 0x0025E0, "Member 'UABP_Base_C::AnimGraphNode_LayeredBoneBlend_6' has a wrong offset!");
static_assert(offsetof(UABP_Base_C, AnimGraphNode_UseCachedPose_10) == 0x0026A0, "Member 'UABP_Base_C::AnimGraphNode_UseCachedPose_10' has a wrong offset!");
static_assert(offsetof(UABP_Base_C, AnimGraphNode_ControlRig_5) == 0x0026C8, "Member 'UABP_Base_C::AnimGraphNode_ControlRig_5' has a wrong offset!");
static_assert(offsetof(UABP_Base_C, AnimGraphNode_UseCachedPose_9) == 0x002A30, "Member 'UABP_Base_C::AnimGraphNode_UseCachedPose_9' has a wrong offset!");
static_assert(offsetof(UABP_Base_C, AnimGraphNode_UseCachedPose_8) == 0x002A58, "Member 'UABP_Base_C::AnimGraphNode_UseCachedPose_8' has a wrong offset!");
static_assert(offsetof(UABP_Base_C, AnimGraphNode_LinkedAnimLayer) == 0x002A80, "Member 'UABP_Base_C::AnimGraphNode_LinkedAnimLayer' has a wrong offset!");
static_assert(offsetof(UABP_Base_C, AnimGraphNode_ControlRig_4) == 0x002B30, "Member 'UABP_Base_C::AnimGraphNode_ControlRig_4' has a wrong offset!");
static_assert(offsetof(UABP_Base_C, AnimGraphNode_Slot_3) == 0x002E98, "Member 'UABP_Base_C::AnimGraphNode_Slot_3' has a wrong offset!");
static_assert(offsetof(UABP_Base_C, AnimGraphNode_Root_10) == 0x002EE0, "Member 'UABP_Base_C::AnimGraphNode_Root_10' has a wrong offset!");
static_assert(offsetof(UABP_Base_C, AnimGraphNode_ControlRig_3) == 0x002F10, "Member 'UABP_Base_C::AnimGraphNode_ControlRig_3' has a wrong offset!");
static_assert(offsetof(UABP_Base_C, AnimGraphNode_TwoWayBlend) == 0x003278, "Member 'UABP_Base_C::AnimGraphNode_TwoWayBlend' has a wrong offset!");
static_assert(offsetof(UABP_Base_C, AnimGraphNode_Slot_2) == 0x003340, "Member 'UABP_Base_C::AnimGraphNode_Slot_2' has a wrong offset!");
static_assert(offsetof(UABP_Base_C, AnimGraphNode_LayeredBoneBlend_5) == 0x003388, "Member 'UABP_Base_C::AnimGraphNode_LayeredBoneBlend_5' has a wrong offset!");
static_assert(offsetof(UABP_Base_C, AnimGraphNode_SaveCachedPose_4) == 0x003448, "Member 'UABP_Base_C::AnimGraphNode_SaveCachedPose_4' has a wrong offset!");
static_assert(offsetof(UABP_Base_C, AnimGraphNode_LinkedInputPose_3) == 0x0035A0, "Member 'UABP_Base_C::AnimGraphNode_LinkedInputPose_3' has a wrong offset!");
static_assert(offsetof(UABP_Base_C, AnimGraphNode_Root_9) == 0x0036B8, "Member 'UABP_Base_C::AnimGraphNode_Root_9' has a wrong offset!");
static_assert(offsetof(UABP_Base_C, AnimGraphNode_SaveCachedPose_3) == 0x0036E8, "Member 'UABP_Base_C::AnimGraphNode_SaveCachedPose_3' has a wrong offset!");
static_assert(offsetof(UABP_Base_C, AnimGraphNode_UseCachedPose_7) == 0x003840, "Member 'UABP_Base_C::AnimGraphNode_UseCachedPose_7' has a wrong offset!");
static_assert(offsetof(UABP_Base_C, AnimGraphNode_UseCachedPose_6) == 0x003868, "Member 'UABP_Base_C::AnimGraphNode_UseCachedPose_6' has a wrong offset!");
static_assert(offsetof(UABP_Base_C, AnimGraphNode_Root_8) == 0x003890, "Member 'UABP_Base_C::AnimGraphNode_Root_8' has a wrong offset!");
static_assert(offsetof(UABP_Base_C, AnimGraphNode_LayeredBoneBlend_4) == 0x0038C0, "Member 'UABP_Base_C::AnimGraphNode_LayeredBoneBlend_4' has a wrong offset!");
static_assert(offsetof(UABP_Base_C, AnimGraphNode_RotateRootBone) == 0x003980, "Member 'UABP_Base_C::AnimGraphNode_RotateRootBone' has a wrong offset!");
static_assert(offsetof(UABP_Base_C, AnimGraphNode_LayeredBoneBlend_3) == 0x003A20, "Member 'UABP_Base_C::AnimGraphNode_LayeredBoneBlend_3' has a wrong offset!");
static_assert(offsetof(UABP_Base_C, AnimGraphNode_UseCachedPose_5) == 0x003AE0, "Member 'UABP_Base_C::AnimGraphNode_UseCachedPose_5' has a wrong offset!");
static_assert(offsetof(UABP_Base_C, AnimGraphNode_ControlRig_2) == 0x003B08, "Member 'UABP_Base_C::AnimGraphNode_ControlRig_2' has a wrong offset!");
static_assert(offsetof(UABP_Base_C, AnimGraphNode_SaveCachedPose_2) == 0x003E70, "Member 'UABP_Base_C::AnimGraphNode_SaveCachedPose_2' has a wrong offset!");
static_assert(offsetof(UABP_Base_C, AnimGraphNode_LinkedInputPose_2) == 0x003FC8, "Member 'UABP_Base_C::AnimGraphNode_LinkedInputPose_2' has a wrong offset!");
static_assert(offsetof(UABP_Base_C, AnimGraphNode_LayeredBoneBlend_2) == 0x0040E0, "Member 'UABP_Base_C::AnimGraphNode_LayeredBoneBlend_2' has a wrong offset!");
static_assert(offsetof(UABP_Base_C, AnimGraphNode_Root_7) == 0x0041A0, "Member 'UABP_Base_C::AnimGraphNode_Root_7' has a wrong offset!");
static_assert(offsetof(UABP_Base_C, AnimGraphNode_LinkedInputPose_1) == 0x0041D0, "Member 'UABP_Base_C::AnimGraphNode_LinkedInputPose_1' has a wrong offset!");
static_assert(offsetof(UABP_Base_C, AnimGraphNode_UseCachedPose_4) == 0x0042E8, "Member 'UABP_Base_C::AnimGraphNode_UseCachedPose_4' has a wrong offset!");
static_assert(offsetof(UABP_Base_C, AnimGraphNode_Root_6) == 0x004310, "Member 'UABP_Base_C::AnimGraphNode_Root_6' has a wrong offset!");
static_assert(offsetof(UABP_Base_C, AnimGraphNode_Root_5) == 0x004340, "Member 'UABP_Base_C::AnimGraphNode_Root_5' has a wrong offset!");
static_assert(offsetof(UABP_Base_C, AnimGraphNode_Root_4) == 0x004370, "Member 'UABP_Base_C::AnimGraphNode_Root_4' has a wrong offset!");
static_assert(offsetof(UABP_Base_C, AnimGraphNode_LinkedInputPose) == 0x0043A0, "Member 'UABP_Base_C::AnimGraphNode_LinkedInputPose' has a wrong offset!");
static_assert(offsetof(UABP_Base_C, AnimGraphNode_Root_3) == 0x0044B8, "Member 'UABP_Base_C::AnimGraphNode_Root_3' has a wrong offset!");
static_assert(offsetof(UABP_Base_C, AnimGraphNode_Slot_1) == 0x0044E8, "Member 'UABP_Base_C::AnimGraphNode_Slot_1' has a wrong offset!");
static_assert(offsetof(UABP_Base_C, AnimGraphNode_Root_2) == 0x004530, "Member 'UABP_Base_C::AnimGraphNode_Root_2' has a wrong offset!");
static_assert(offsetof(UABP_Base_C, AnimGraphNode_LayeredBoneBlend_1) == 0x004560, "Member 'UABP_Base_C::AnimGraphNode_LayeredBoneBlend_1' has a wrong offset!");
static_assert(offsetof(UABP_Base_C, AnimGraphNode_UseCachedPose_3) == 0x004620, "Member 'UABP_Base_C::AnimGraphNode_UseCachedPose_3' has a wrong offset!");
static_assert(offsetof(UABP_Base_C, AnimGraphNode_UseCachedPose_2) == 0x004648, "Member 'UABP_Base_C::AnimGraphNode_UseCachedPose_2' has a wrong offset!");
static_assert(offsetof(UABP_Base_C, AnimGraphNode_SaveCachedPose_1) == 0x004670, "Member 'UABP_Base_C::AnimGraphNode_SaveCachedPose_1' has a wrong offset!");
static_assert(offsetof(UABP_Base_C, AnimGraphNode_LayeredBoneBlend) == 0x0047C8, "Member 'UABP_Base_C::AnimGraphNode_LayeredBoneBlend' has a wrong offset!");
static_assert(offsetof(UABP_Base_C, AnimGraphNode_UseCachedPose_1) == 0x004888, "Member 'UABP_Base_C::AnimGraphNode_UseCachedPose_1' has a wrong offset!");
static_assert(offsetof(UABP_Base_C, AnimGraphNode_UseCachedPose) == 0x0048B0, "Member 'UABP_Base_C::AnimGraphNode_UseCachedPose' has a wrong offset!");
static_assert(offsetof(UABP_Base_C, AnimGraphNode_Slot) == 0x0048D8, "Member 'UABP_Base_C::AnimGraphNode_Slot' has a wrong offset!");
static_assert(offsetof(UABP_Base_C, AnimGraphNode_ControlRig_1) == 0x004920, "Member 'UABP_Base_C::AnimGraphNode_ControlRig_1' has a wrong offset!");
static_assert(offsetof(UABP_Base_C, AnimGraphNode_ControlRig) == 0x004C88, "Member 'UABP_Base_C::AnimGraphNode_ControlRig' has a wrong offset!");
static_assert(offsetof(UABP_Base_C, AnimGraphNode_SaveCachedPose) == 0x004FF0, "Member 'UABP_Base_C::AnimGraphNode_SaveCachedPose' has a wrong offset!");
static_assert(offsetof(UABP_Base_C, AnimGraphNode_Root_1) == 0x005148, "Member 'UABP_Base_C::AnimGraphNode_Root_1' has a wrong offset!");
static_assert(offsetof(UABP_Base_C, AnimGraphNode_Root) == 0x005178, "Member 'UABP_Base_C::AnimGraphNode_Root' has a wrong offset!");
static_assert(offsetof(UABP_Base_C, K2Node_PropertyAccess_9) == 0x0051A8, "Member 'UABP_Base_C::K2Node_PropertyAccess_9' has a wrong offset!");
static_assert(offsetof(UABP_Base_C, K2Node_PropertyAccess_8) == 0x0051A9, "Member 'UABP_Base_C::K2Node_PropertyAccess_8' has a wrong offset!");
static_assert(offsetof(UABP_Base_C, K2Node_PropertyAccess_7) == 0x0051AA, "Member 'UABP_Base_C::K2Node_PropertyAccess_7' has a wrong offset!");
static_assert(offsetof(UABP_Base_C, K2Node_PropertyAccess_6) == 0x0051AB, "Member 'UABP_Base_C::K2Node_PropertyAccess_6' has a wrong offset!");
static_assert(offsetof(UABP_Base_C, K2Node_PropertyAccess_5) == 0x0051AC, "Member 'UABP_Base_C::K2Node_PropertyAccess_5' has a wrong offset!");
static_assert(offsetof(UABP_Base_C, K2Node_PropertyAccess_4) == 0x0051AD, "Member 'UABP_Base_C::K2Node_PropertyAccess_4' has a wrong offset!");
static_assert(offsetof(UABP_Base_C, K2Node_PropertyAccess_3) == 0x0051AE, "Member 'UABP_Base_C::K2Node_PropertyAccess_3' has a wrong offset!");
static_assert(offsetof(UABP_Base_C, K2Node_PropertyAccess_2) == 0x0051AF, "Member 'UABP_Base_C::K2Node_PropertyAccess_2' has a wrong offset!");
static_assert(offsetof(UABP_Base_C, K2Node_PropertyAccess_1) == 0x0051B0, "Member 'UABP_Base_C::K2Node_PropertyAccess_1' has a wrong offset!");
static_assert(offsetof(UABP_Base_C, K2Node_PropertyAccess) == 0x0051B1, "Member 'UABP_Base_C::K2Node_PropertyAccess' has a wrong offset!");
static_assert(offsetof(UABP_Base_C, __CustomProperty_DynamicLeftHandIKRoot_BoneName_F245D82582F44CC58D4CA913D6708A94) == 0x0051B4, "Member 'UABP_Base_C::__CustomProperty_DynamicLeftHandIKRoot_BoneName_F245D82582F44CC58D4CA913D6708A94' has a wrong offset!");
static_assert(offsetof(UABP_Base_C, __CustomProperty_DynamicLeftHandIKRoot_BoneName_129D599A1F25408885024AE111A6A52D) == 0x0051BC, "Member 'UABP_Base_C::__CustomProperty_DynamicLeftHandIKRoot_BoneName_129D599A1F25408885024AE111A6A52D' has a wrong offset!");
static_assert(offsetof(UABP_Base_C, __CustomProperty_DynamicLeftHandIKRoot_BoneName_01539DA250DF454DBFB0930F32343253) == 0x0051C4, "Member 'UABP_Base_C::__CustomProperty_DynamicLeftHandIKRoot_BoneName_01539DA250DF454DBFB0930F32343253' has a wrong offset!");
static_assert(offsetof(UABP_Base_C, __CustomProperty_DynamicLeftHandIKRoot_BoneName_06C1DCE5E990460EA04EB06737470176) == 0x0051CC, "Member 'UABP_Base_C::__CustomProperty_DynamicLeftHandIKRoot_BoneName_06C1DCE5E990460EA04EB06737470176' has a wrong offset!");
static_assert(offsetof(UABP_Base_C, __CustomProperty_DynamicRightItemParent_A127D59AE00D4BCE977DB3150B0B88AE) == 0x0051D4, "Member 'UABP_Base_C::__CustomProperty_DynamicRightItemParent_A127D59AE00D4BCE977DB3150B0B88AE' has a wrong offset!");
static_assert(offsetof(UABP_Base_C, __CustomProperty_DynamicRightHandIKParent_CB584B86F3A8460C80FCB8E101D93AA1) == 0x0051DC, "Member 'UABP_Base_C::__CustomProperty_DynamicRightHandIKParent_CB584B86F3A8460C80FCB8E101D93AA1' has a wrong offset!");
static_assert(offsetof(UABP_Base_C, __CustomProperty_DynamicLeftHandIKRoot_RotOffset_4C1F2A5C42854D638936F7E321A1DA54) == 0x0051E4, "Member 'UABP_Base_C::__CustomProperty_DynamicLeftHandIKRoot_RotOffset_4C1F2A5C42854D638936F7E321A1DA54' has a wrong offset!");
static_assert(offsetof(UABP_Base_C, __CustomProperty_DynamicLeftHandIKRoot_LocOffset_4C1F2A5C42854D638936F7E321A1DA54) == 0x0051F0, "Member 'UABP_Base_C::__CustomProperty_DynamicLeftHandIKRoot_LocOffset_4C1F2A5C42854D638936F7E321A1DA54' has a wrong offset!");
static_assert(offsetof(UABP_Base_C, __CustomProperty_DynamicLeftHandIKRoot_BoneName_4C1F2A5C42854D638936F7E321A1DA54) == 0x0051FC, "Member 'UABP_Base_C::__CustomProperty_DynamicLeftHandIKRoot_BoneName_4C1F2A5C42854D638936F7E321A1DA54' has a wrong offset!");
static_assert(offsetof(UABP_Base_C, __CustomProperty_DynamicRightItemRoot_BoneName_CDC0D867E23F4429A518CC1C60D99A80) == 0x005204, "Member 'UABP_Base_C::__CustomProperty_DynamicRightItemRoot_BoneName_CDC0D867E23F4429A518CC1C60D99A80' has a wrong offset!");
static_assert(offsetof(UABP_Base_C, __CustomProperty_DynamicRightHandIKRoot_BoneName_CDC0D867E23F4429A518CC1C60D99A80) == 0x00520C, "Member 'UABP_Base_C::__CustomProperty_DynamicRightHandIKRoot_BoneName_CDC0D867E23F4429A518CC1C60D99A80' has a wrong offset!");
static_assert(offsetof(UABP_Base_C, __CustomProperty_DynamicLeftHandIKRoot_BoneName_CDC0D867E23F4429A518CC1C60D99A80) == 0x005214, "Member 'UABP_Base_C::__CustomProperty_DynamicLeftHandIKRoot_BoneName_CDC0D867E23F4429A518CC1C60D99A80' has a wrong offset!");
static_assert(offsetof(UABP_Base_C, __CustomProperty_HeadOffset_CDC0D867E23F4429A518CC1C60D99A80) == 0x00521C, "Member 'UABP_Base_C::__CustomProperty_HeadOffset_CDC0D867E23F4429A518CC1C60D99A80' has a wrong offset!");

}

