#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_45ACPFMJ

#include "Basic.hpp"

#include "GroundBranch_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_45ACPFMJ.BP_45ACPFMJ_C
// 0x0008 (0x0458 - 0x0450)
class ABP_45ACPFMJ_C final : public AGBBulletItem
{
public:
	class USceneComponent*                        DefaultSceneRoot;                                  // 0x0450(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_45ACPFMJ_C">();
	}
	static class ABP_45ACPFMJ_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_45ACPFMJ_C>();
	}
};
static_assert(alignof(ABP_45ACPFMJ_C) == 0x000008, "Wrong alignment on ABP_45ACPFMJ_C");
static_assert(sizeof(ABP_45ACPFMJ_C) == 0x000458, "Wrong size on ABP_45ACPFMJ_C");
static_assert(offsetof(ABP_45ACPFMJ_C, DefaultSceneRoot) == 0x000450, "Member 'ABP_45ACPFMJ_C::DefaultSceneRoot' has a wrong offset!");

}

