#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_AN_PEQ_Master

#include "Basic.hpp"

#include "GameplayTags_structs.hpp"
#include "GameplayAbilities_structs.hpp"


namespace SDK::Params
{

// Function BP_AN_PEQ_Master.BP_AN_PEQ_Master_C.ExecuteUbergraph_BP_AN_PEQ_Master
// 0x0518 (0x0518 - 0x0000)
struct BP_AN_PEQ_Master_C_ExecuteUbergraph_BP_AN_PEQ_Master final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UWBP_RadialMenu_Entry_C*                CallFunc_Create_ReturnValue;                       // 0x0008(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0010(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsValid_ReturnValue_1;                    // 0x0011(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_12[0x6];                                       // 0x0012(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class AGBCharacter*                           CallFunc_GetGBInstigator_ReturnValue;              // 0x0018(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UWBP_PEQLaserModeIndicator_C*           CallFunc_Create_ReturnValue_1;                     // 0x0020(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsPlayerControlled_ReturnValue;           // 0x0028(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsLocallyControlled_ReturnValue;          // 0x0029(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_BooleanAND_ReturnValue;                   // 0x002A(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsValid_ReturnValue_2;                    // 0x002B(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsValid_ReturnValue_3;                    // 0x002C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_2D[0x3];                                       // 0x002D(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class UUserWidget*                            K2Node_Event_UsageMenu;                            // 0x0030(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_4;                    // 0x0038(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_39[0x7];                                       // 0x0039(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UWBP_RadialMenu_C*                      K2Node_DynamicCast_AsWBP_Radial_Menu;              // 0x0040(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0048(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsServer_ReturnValue;                     // 0x0049(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          K2Node_CustomEvent_bIlluminator_High;              // 0x004A(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_4B[0x5];                                       // 0x004B(0x0005)(Fixing Size After Last Property [ Dumper-7 ])
	class AGBCharacter*                           K2Node_Event_Character_1;                          // 0x0050(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UWBP_RadialMenu_C*                      K2Node_CustomEvent_UsageMenu_3;                    // 0x0058(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         K2Node_CustomEvent_Index_3;                        // 0x0060(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_64[0x4];                                       // 0x0064(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UWBP_RadialMenu_C*                      K2Node_CustomEvent_UsageMenu_2;                    // 0x0068(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         K2Node_CustomEvent_Index_2;                        // 0x0070(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsDedicatedServer_ReturnValue;            // 0x0074(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsValid_ReturnValue_5;                    // 0x0075(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsValid_ReturnValue_6;                    // 0x0076(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_77[0x1];                                       // 0x0077(0x0001)(Fixing Size After Last Property [ Dumper-7 ])
	struct FGameplayTag                           Temp_struct_Variable;                              // 0x0078(0x0008)(NoDestructor, HasGetValueTypeHash)
	struct FGameplayTag                           Temp_struct_Variable_1;                            // 0x0080(0x0008)(NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Variable;                                // 0x0088(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_89[0x7];                                       // 0x0089(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UWBP_RadialMenu_C*                      K2Node_CustomEvent_UsageMenu_1;                    // 0x0090(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         K2Node_CustomEvent_Index_1;                        // 0x0098(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TDelegate<void(int32 Index)>                  K2Node_CreateDelegate_OutputDelegate;              // 0x009C(0x0010)(ZeroConstructor, NoDestructor)
	uint8                                         Pad_AC[0x4];                                       // 0x00AC(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	TSoftObjectPtr<class UTexture2D>              CallFunc_GetIcon_ReturnValue;                      // 0x00B0(0x0028)(UObjectWrapper, HasGetValueTypeHash)
	class AGBCharacter*                           CallFunc_GetGBInstigator_ReturnValue_1;            // 0x00D8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UWBP_RadialMenu_Entry_C*                CallFunc_Create_ReturnValue_2;                     // 0x00E0(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TDelegate<void(int32 Index)>                  K2Node_CreateDelegate_OutputDelegate_1;            // 0x00E8(0x0010)(ZeroConstructor, NoDestructor)
	bool                                          CallFunc_GetLaserActive_OutLaserActive;            // 0x00F8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_GetLaserActive_OutLaserActive_1;          // 0x00F9(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_FA[0x6];                                       // 0x00FA(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class UWBP_RadialMenu_C*                      K2Node_CustomEvent_UsageMenu;                      // 0x0100(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_BooleanOR_ReturnValue;                    // 0x0108(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_109[0x3];                                      // 0x0109(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         K2Node_CustomEvent_Index;                          // 0x010C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FGameplayTag                           Temp_struct_Variable_2;                            // 0x0110(0x0008)(NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_GetLightActive_OutActive;                 // 0x0118(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_119[0x3];                                      // 0x0119(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FGameplayTag                           K2Node_Select_Default;                             // 0x011C(0x0008)(NoDestructor, HasGetValueTypeHash)
	struct FGameplayTag                           Temp_struct_Variable_3;                            // 0x0124(0x0008)(NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Variable_1;                              // 0x012C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_12D[0x3];                                      // 0x012D(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	TSoftObjectPtr<class UTexture2D>              CallFunc_GetIcon_ReturnValue_1;                    // 0x0130(0x0028)(UObjectWrapper, HasGetValueTypeHash)
	struct FGameplayTag                           K2Node_Select_Default_1;                           // 0x0158(0x0008)(NoDestructor, HasGetValueTypeHash)
	class AGBCharacter*                           CallFunc_GetGBInstigator_ReturnValue_2;            // 0x0160(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TDelegate<void(int32 Index)>                  K2Node_CreateDelegate_OutputDelegate_2;            // 0x0168(0x0010)(ZeroConstructor, NoDestructor)
	class UWBP_RadialMenu_Entry_C*                CallFunc_Create_ReturnValue_3;                     // 0x0178(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Variable_2;                              // 0x0180(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_181[0x7];                                      // 0x0181(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class AGBCharacter*                           K2Node_Event_Character;                            // 0x0188(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         K2Node_Select_Default_2;                           // 0x0190(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsDedicatedServer_ReturnValue_1;          // 0x0194(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          Temp_bool_Variable_3;                              // 0x0195(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_196[0x2];                                      // 0x0196(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         K2Node_Select_Default_3;                           // 0x0198(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_ComponentBoundEvent_bLightActive;           // 0x019C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          K2Node_ComponentBoundEvent_bLightVisibility;       // 0x019D(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          Temp_bool_Variable_4;                              // 0x019E(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_19F[0x1];                                      // 0x019F(0x0001)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         CallFunc_Conv_BoolToFloat_ReturnValue;             // 0x01A0(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         K2Node_Select_Default_4;                           // 0x01A4(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_Conv_BoolToFloat_ReturnValue_1;           // 0x01A8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Variable_5;                              // 0x01AC(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_1AD[0x3];                                      // 0x01AD(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class UMaterialInstanceDynamic*               CallFunc_CreateDynamicMaterialInstance_ReturnValue; // 0x01B0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         K2Node_Select_Default_5;                           // 0x01B8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1BC[0x4];                                      // 0x01BC(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UWBP_RadialMenu_Entry_C*                CallFunc_Create_ReturnValue_4;                     // 0x01C0(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsDedicatedServer_ReturnValue_2;          // 0x01C8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_1C9[0x7];                                      // 0x01C9(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	TSoftObjectPtr<class UTexture2D>              CallFunc_GetIcon_ReturnValue_2;                    // 0x01D0(0x0028)(UObjectWrapper, HasGetValueTypeHash)
	bool                                          CallFunc_Not_PreBool_ReturnValue;                  // 0x01F8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_1F9[0x7];                                      // 0x01F9(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	TSoftObjectPtr<class UTexture2D>              CallFunc_GetIcon_ReturnValue_3;                    // 0x0200(0x0028)(UObjectWrapper, HasGetValueTypeHash)
	class AGBCharacter*                           CallFunc_GetGBInstigator_ReturnValue_3;            // 0x0228(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FGameplayEventData                     K2Node_MakeStruct_GameplayEventData;               // 0x0230(0x00B0)()
	struct FGameplayEventData                     K2Node_MakeStruct_GameplayEventData_1;             // 0x02E0(0x00B0)()
	struct FGameplayEventData                     K2Node_MakeStruct_GameplayEventData_2;             // 0x0390(0x00B0)()
	struct FGameplayEventData                     K2Node_MakeStruct_GameplayEventData_3;             // 0x0440(0x00B0)()
	class UNiagaraSystem*                         CallFunc_GetEffect_ReturnValue;                    // 0x04F0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UNiagaraSystem*                         CallFunc_GetEffect_ReturnValue_1;                  // 0x04F8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AGBCharacter*                           CallFunc_GetGBInstigator_ReturnValue_4;            // 0x0500(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TDelegate<void(int32 Index)>                  K2Node_CreateDelegate_OutputDelegate_3;            // 0x0508(0x0010)(ZeroConstructor, NoDestructor)
};
static_assert(alignof(BP_AN_PEQ_Master_C_ExecuteUbergraph_BP_AN_PEQ_Master) == 0x000008, "Wrong alignment on BP_AN_PEQ_Master_C_ExecuteUbergraph_BP_AN_PEQ_Master");
static_assert(sizeof(BP_AN_PEQ_Master_C_ExecuteUbergraph_BP_AN_PEQ_Master) == 0x000518, "Wrong size on BP_AN_PEQ_Master_C_ExecuteUbergraph_BP_AN_PEQ_Master");
static_assert(offsetof(BP_AN_PEQ_Master_C_ExecuteUbergraph_BP_AN_PEQ_Master, EntryPoint) == 0x000000, "Member 'BP_AN_PEQ_Master_C_ExecuteUbergraph_BP_AN_PEQ_Master::EntryPoint' has a wrong offset!");
static_assert(offsetof(BP_AN_PEQ_Master_C_ExecuteUbergraph_BP_AN_PEQ_Master, CallFunc_Create_ReturnValue) == 0x000008, "Member 'BP_AN_PEQ_Master_C_ExecuteUbergraph_BP_AN_PEQ_Master::CallFunc_Create_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_AN_PEQ_Master_C_ExecuteUbergraph_BP_AN_PEQ_Master, CallFunc_IsValid_ReturnValue) == 0x000010, "Member 'BP_AN_PEQ_Master_C_ExecuteUbergraph_BP_AN_PEQ_Master::CallFunc_IsValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_AN_PEQ_Master_C_ExecuteUbergraph_BP_AN_PEQ_Master, CallFunc_IsValid_ReturnValue_1) == 0x000011, "Member 'BP_AN_PEQ_Master_C_ExecuteUbergraph_BP_AN_PEQ_Master::CallFunc_IsValid_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_AN_PEQ_Master_C_ExecuteUbergraph_BP_AN_PEQ_Master, CallFunc_GetGBInstigator_ReturnValue) == 0x000018, "Member 'BP_AN_PEQ_Master_C_ExecuteUbergraph_BP_AN_PEQ_Master::CallFunc_GetGBInstigator_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_AN_PEQ_Master_C_ExecuteUbergraph_BP_AN_PEQ_Master, CallFunc_Create_ReturnValue_1) == 0x000020, "Member 'BP_AN_PEQ_Master_C_ExecuteUbergraph_BP_AN_PEQ_Master::CallFunc_Create_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_AN_PEQ_Master_C_ExecuteUbergraph_BP_AN_PEQ_Master, CallFunc_IsPlayerControlled_ReturnValue) == 0x000028, "Member 'BP_AN_PEQ_Master_C_ExecuteUbergraph_BP_AN_PEQ_Master::CallFunc_IsPlayerControlled_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_AN_PEQ_Master_C_ExecuteUbergraph_BP_AN_PEQ_Master, CallFunc_IsLocallyControlled_ReturnValue) == 0x000029, "Member 'BP_AN_PEQ_Master_C_ExecuteUbergraph_BP_AN_PEQ_Master::CallFunc_IsLocallyControlled_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_AN_PEQ_Master_C_ExecuteUbergraph_BP_AN_PEQ_Master, CallFunc_BooleanAND_ReturnValue) == 0x00002A, "Member 'BP_AN_PEQ_Master_C_ExecuteUbergraph_BP_AN_PEQ_Master::CallFunc_BooleanAND_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_AN_PEQ_Master_C_ExecuteUbergraph_BP_AN_PEQ_Master, CallFunc_IsValid_ReturnValue_2) == 0x00002B, "Member 'BP_AN_PEQ_Master_C_ExecuteUbergraph_BP_AN_PEQ_Master::CallFunc_IsValid_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(BP_AN_PEQ_Master_C_ExecuteUbergraph_BP_AN_PEQ_Master, CallFunc_IsValid_ReturnValue_3) == 0x00002C, "Member 'BP_AN_PEQ_Master_C_ExecuteUbergraph_BP_AN_PEQ_Master::CallFunc_IsValid_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(BP_AN_PEQ_Master_C_ExecuteUbergraph_BP_AN_PEQ_Master, K2Node_Event_UsageMenu) == 0x000030, "Member 'BP_AN_PEQ_Master_C_ExecuteUbergraph_BP_AN_PEQ_Master::K2Node_Event_UsageMenu' has a wrong offset!");
static_assert(offsetof(BP_AN_PEQ_Master_C_ExecuteUbergraph_BP_AN_PEQ_Master, CallFunc_IsValid_ReturnValue_4) == 0x000038, "Member 'BP_AN_PEQ_Master_C_ExecuteUbergraph_BP_AN_PEQ_Master::CallFunc_IsValid_ReturnValue_4' has a wrong offset!");
static_assert(offsetof(BP_AN_PEQ_Master_C_ExecuteUbergraph_BP_AN_PEQ_Master, K2Node_DynamicCast_AsWBP_Radial_Menu) == 0x000040, "Member 'BP_AN_PEQ_Master_C_ExecuteUbergraph_BP_AN_PEQ_Master::K2Node_DynamicCast_AsWBP_Radial_Menu' has a wrong offset!");
static_assert(offsetof(BP_AN_PEQ_Master_C_ExecuteUbergraph_BP_AN_PEQ_Master, K2Node_DynamicCast_bSuccess) == 0x000048, "Member 'BP_AN_PEQ_Master_C_ExecuteUbergraph_BP_AN_PEQ_Master::K2Node_DynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(BP_AN_PEQ_Master_C_ExecuteUbergraph_BP_AN_PEQ_Master, CallFunc_IsServer_ReturnValue) == 0x000049, "Member 'BP_AN_PEQ_Master_C_ExecuteUbergraph_BP_AN_PEQ_Master::CallFunc_IsServer_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_AN_PEQ_Master_C_ExecuteUbergraph_BP_AN_PEQ_Master, K2Node_CustomEvent_bIlluminator_High) == 0x00004A, "Member 'BP_AN_PEQ_Master_C_ExecuteUbergraph_BP_AN_PEQ_Master::K2Node_CustomEvent_bIlluminator_High' has a wrong offset!");
static_assert(offsetof(BP_AN_PEQ_Master_C_ExecuteUbergraph_BP_AN_PEQ_Master, K2Node_Event_Character_1) == 0x000050, "Member 'BP_AN_PEQ_Master_C_ExecuteUbergraph_BP_AN_PEQ_Master::K2Node_Event_Character_1' has a wrong offset!");
static_assert(offsetof(BP_AN_PEQ_Master_C_ExecuteUbergraph_BP_AN_PEQ_Master, K2Node_CustomEvent_UsageMenu_3) == 0x000058, "Member 'BP_AN_PEQ_Master_C_ExecuteUbergraph_BP_AN_PEQ_Master::K2Node_CustomEvent_UsageMenu_3' has a wrong offset!");
static_assert(offsetof(BP_AN_PEQ_Master_C_ExecuteUbergraph_BP_AN_PEQ_Master, K2Node_CustomEvent_Index_3) == 0x000060, "Member 'BP_AN_PEQ_Master_C_ExecuteUbergraph_BP_AN_PEQ_Master::K2Node_CustomEvent_Index_3' has a wrong offset!");
static_assert(offsetof(BP_AN_PEQ_Master_C_ExecuteUbergraph_BP_AN_PEQ_Master, K2Node_CustomEvent_UsageMenu_2) == 0x000068, "Member 'BP_AN_PEQ_Master_C_ExecuteUbergraph_BP_AN_PEQ_Master::K2Node_CustomEvent_UsageMenu_2' has a wrong offset!");
static_assert(offsetof(BP_AN_PEQ_Master_C_ExecuteUbergraph_BP_AN_PEQ_Master, K2Node_CustomEvent_Index_2) == 0x000070, "Member 'BP_AN_PEQ_Master_C_ExecuteUbergraph_BP_AN_PEQ_Master::K2Node_CustomEvent_Index_2' has a wrong offset!");
static_assert(offsetof(BP_AN_PEQ_Master_C_ExecuteUbergraph_BP_AN_PEQ_Master, CallFunc_IsDedicatedServer_ReturnValue) == 0x000074, "Member 'BP_AN_PEQ_Master_C_ExecuteUbergraph_BP_AN_PEQ_Master::CallFunc_IsDedicatedServer_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_AN_PEQ_Master_C_ExecuteUbergraph_BP_AN_PEQ_Master, CallFunc_IsValid_ReturnValue_5) == 0x000075, "Member 'BP_AN_PEQ_Master_C_ExecuteUbergraph_BP_AN_PEQ_Master::CallFunc_IsValid_ReturnValue_5' has a wrong offset!");
static_assert(offsetof(BP_AN_PEQ_Master_C_ExecuteUbergraph_BP_AN_PEQ_Master, CallFunc_IsValid_ReturnValue_6) == 0x000076, "Member 'BP_AN_PEQ_Master_C_ExecuteUbergraph_BP_AN_PEQ_Master::CallFunc_IsValid_ReturnValue_6' has a wrong offset!");
static_assert(offsetof(BP_AN_PEQ_Master_C_ExecuteUbergraph_BP_AN_PEQ_Master, Temp_struct_Variable) == 0x000078, "Member 'BP_AN_PEQ_Master_C_ExecuteUbergraph_BP_AN_PEQ_Master::Temp_struct_Variable' has a wrong offset!");
static_assert(offsetof(BP_AN_PEQ_Master_C_ExecuteUbergraph_BP_AN_PEQ_Master, Temp_struct_Variable_1) == 0x000080, "Member 'BP_AN_PEQ_Master_C_ExecuteUbergraph_BP_AN_PEQ_Master::Temp_struct_Variable_1' has a wrong offset!");
static_assert(offsetof(BP_AN_PEQ_Master_C_ExecuteUbergraph_BP_AN_PEQ_Master, Temp_bool_Variable) == 0x000088, "Member 'BP_AN_PEQ_Master_C_ExecuteUbergraph_BP_AN_PEQ_Master::Temp_bool_Variable' has a wrong offset!");
static_assert(offsetof(BP_AN_PEQ_Master_C_ExecuteUbergraph_BP_AN_PEQ_Master, K2Node_CustomEvent_UsageMenu_1) == 0x000090, "Member 'BP_AN_PEQ_Master_C_ExecuteUbergraph_BP_AN_PEQ_Master::K2Node_CustomEvent_UsageMenu_1' has a wrong offset!");
static_assert(offsetof(BP_AN_PEQ_Master_C_ExecuteUbergraph_BP_AN_PEQ_Master, K2Node_CustomEvent_Index_1) == 0x000098, "Member 'BP_AN_PEQ_Master_C_ExecuteUbergraph_BP_AN_PEQ_Master::K2Node_CustomEvent_Index_1' has a wrong offset!");
static_assert(offsetof(BP_AN_PEQ_Master_C_ExecuteUbergraph_BP_AN_PEQ_Master, K2Node_CreateDelegate_OutputDelegate) == 0x00009C, "Member 'BP_AN_PEQ_Master_C_ExecuteUbergraph_BP_AN_PEQ_Master::K2Node_CreateDelegate_OutputDelegate' has a wrong offset!");
static_assert(offsetof(BP_AN_PEQ_Master_C_ExecuteUbergraph_BP_AN_PEQ_Master, CallFunc_GetIcon_ReturnValue) == 0x0000B0, "Member 'BP_AN_PEQ_Master_C_ExecuteUbergraph_BP_AN_PEQ_Master::CallFunc_GetIcon_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_AN_PEQ_Master_C_ExecuteUbergraph_BP_AN_PEQ_Master, CallFunc_GetGBInstigator_ReturnValue_1) == 0x0000D8, "Member 'BP_AN_PEQ_Master_C_ExecuteUbergraph_BP_AN_PEQ_Master::CallFunc_GetGBInstigator_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_AN_PEQ_Master_C_ExecuteUbergraph_BP_AN_PEQ_Master, CallFunc_Create_ReturnValue_2) == 0x0000E0, "Member 'BP_AN_PEQ_Master_C_ExecuteUbergraph_BP_AN_PEQ_Master::CallFunc_Create_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(BP_AN_PEQ_Master_C_ExecuteUbergraph_BP_AN_PEQ_Master, K2Node_CreateDelegate_OutputDelegate_1) == 0x0000E8, "Member 'BP_AN_PEQ_Master_C_ExecuteUbergraph_BP_AN_PEQ_Master::K2Node_CreateDelegate_OutputDelegate_1' has a wrong offset!");
static_assert(offsetof(BP_AN_PEQ_Master_C_ExecuteUbergraph_BP_AN_PEQ_Master, CallFunc_GetLaserActive_OutLaserActive) == 0x0000F8, "Member 'BP_AN_PEQ_Master_C_ExecuteUbergraph_BP_AN_PEQ_Master::CallFunc_GetLaserActive_OutLaserActive' has a wrong offset!");
static_assert(offsetof(BP_AN_PEQ_Master_C_ExecuteUbergraph_BP_AN_PEQ_Master, CallFunc_GetLaserActive_OutLaserActive_1) == 0x0000F9, "Member 'BP_AN_PEQ_Master_C_ExecuteUbergraph_BP_AN_PEQ_Master::CallFunc_GetLaserActive_OutLaserActive_1' has a wrong offset!");
static_assert(offsetof(BP_AN_PEQ_Master_C_ExecuteUbergraph_BP_AN_PEQ_Master, K2Node_CustomEvent_UsageMenu) == 0x000100, "Member 'BP_AN_PEQ_Master_C_ExecuteUbergraph_BP_AN_PEQ_Master::K2Node_CustomEvent_UsageMenu' has a wrong offset!");
static_assert(offsetof(BP_AN_PEQ_Master_C_ExecuteUbergraph_BP_AN_PEQ_Master, CallFunc_BooleanOR_ReturnValue) == 0x000108, "Member 'BP_AN_PEQ_Master_C_ExecuteUbergraph_BP_AN_PEQ_Master::CallFunc_BooleanOR_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_AN_PEQ_Master_C_ExecuteUbergraph_BP_AN_PEQ_Master, K2Node_CustomEvent_Index) == 0x00010C, "Member 'BP_AN_PEQ_Master_C_ExecuteUbergraph_BP_AN_PEQ_Master::K2Node_CustomEvent_Index' has a wrong offset!");
static_assert(offsetof(BP_AN_PEQ_Master_C_ExecuteUbergraph_BP_AN_PEQ_Master, Temp_struct_Variable_2) == 0x000110, "Member 'BP_AN_PEQ_Master_C_ExecuteUbergraph_BP_AN_PEQ_Master::Temp_struct_Variable_2' has a wrong offset!");
static_assert(offsetof(BP_AN_PEQ_Master_C_ExecuteUbergraph_BP_AN_PEQ_Master, CallFunc_GetLightActive_OutActive) == 0x000118, "Member 'BP_AN_PEQ_Master_C_ExecuteUbergraph_BP_AN_PEQ_Master::CallFunc_GetLightActive_OutActive' has a wrong offset!");
static_assert(offsetof(BP_AN_PEQ_Master_C_ExecuteUbergraph_BP_AN_PEQ_Master, K2Node_Select_Default) == 0x00011C, "Member 'BP_AN_PEQ_Master_C_ExecuteUbergraph_BP_AN_PEQ_Master::K2Node_Select_Default' has a wrong offset!");
static_assert(offsetof(BP_AN_PEQ_Master_C_ExecuteUbergraph_BP_AN_PEQ_Master, Temp_struct_Variable_3) == 0x000124, "Member 'BP_AN_PEQ_Master_C_ExecuteUbergraph_BP_AN_PEQ_Master::Temp_struct_Variable_3' has a wrong offset!");
static_assert(offsetof(BP_AN_PEQ_Master_C_ExecuteUbergraph_BP_AN_PEQ_Master, Temp_bool_Variable_1) == 0x00012C, "Member 'BP_AN_PEQ_Master_C_ExecuteUbergraph_BP_AN_PEQ_Master::Temp_bool_Variable_1' has a wrong offset!");
static_assert(offsetof(BP_AN_PEQ_Master_C_ExecuteUbergraph_BP_AN_PEQ_Master, CallFunc_GetIcon_ReturnValue_1) == 0x000130, "Member 'BP_AN_PEQ_Master_C_ExecuteUbergraph_BP_AN_PEQ_Master::CallFunc_GetIcon_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_AN_PEQ_Master_C_ExecuteUbergraph_BP_AN_PEQ_Master, K2Node_Select_Default_1) == 0x000158, "Member 'BP_AN_PEQ_Master_C_ExecuteUbergraph_BP_AN_PEQ_Master::K2Node_Select_Default_1' has a wrong offset!");
static_assert(offsetof(BP_AN_PEQ_Master_C_ExecuteUbergraph_BP_AN_PEQ_Master, CallFunc_GetGBInstigator_ReturnValue_2) == 0x000160, "Member 'BP_AN_PEQ_Master_C_ExecuteUbergraph_BP_AN_PEQ_Master::CallFunc_GetGBInstigator_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(BP_AN_PEQ_Master_C_ExecuteUbergraph_BP_AN_PEQ_Master, K2Node_CreateDelegate_OutputDelegate_2) == 0x000168, "Member 'BP_AN_PEQ_Master_C_ExecuteUbergraph_BP_AN_PEQ_Master::K2Node_CreateDelegate_OutputDelegate_2' has a wrong offset!");
static_assert(offsetof(BP_AN_PEQ_Master_C_ExecuteUbergraph_BP_AN_PEQ_Master, CallFunc_Create_ReturnValue_3) == 0x000178, "Member 'BP_AN_PEQ_Master_C_ExecuteUbergraph_BP_AN_PEQ_Master::CallFunc_Create_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(BP_AN_PEQ_Master_C_ExecuteUbergraph_BP_AN_PEQ_Master, Temp_bool_Variable_2) == 0x000180, "Member 'BP_AN_PEQ_Master_C_ExecuteUbergraph_BP_AN_PEQ_Master::Temp_bool_Variable_2' has a wrong offset!");
static_assert(offsetof(BP_AN_PEQ_Master_C_ExecuteUbergraph_BP_AN_PEQ_Master, K2Node_Event_Character) == 0x000188, "Member 'BP_AN_PEQ_Master_C_ExecuteUbergraph_BP_AN_PEQ_Master::K2Node_Event_Character' has a wrong offset!");
static_assert(offsetof(BP_AN_PEQ_Master_C_ExecuteUbergraph_BP_AN_PEQ_Master, K2Node_Select_Default_2) == 0x000190, "Member 'BP_AN_PEQ_Master_C_ExecuteUbergraph_BP_AN_PEQ_Master::K2Node_Select_Default_2' has a wrong offset!");
static_assert(offsetof(BP_AN_PEQ_Master_C_ExecuteUbergraph_BP_AN_PEQ_Master, CallFunc_IsDedicatedServer_ReturnValue_1) == 0x000194, "Member 'BP_AN_PEQ_Master_C_ExecuteUbergraph_BP_AN_PEQ_Master::CallFunc_IsDedicatedServer_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_AN_PEQ_Master_C_ExecuteUbergraph_BP_AN_PEQ_Master, Temp_bool_Variable_3) == 0x000195, "Member 'BP_AN_PEQ_Master_C_ExecuteUbergraph_BP_AN_PEQ_Master::Temp_bool_Variable_3' has a wrong offset!");
static_assert(offsetof(BP_AN_PEQ_Master_C_ExecuteUbergraph_BP_AN_PEQ_Master, K2Node_Select_Default_3) == 0x000198, "Member 'BP_AN_PEQ_Master_C_ExecuteUbergraph_BP_AN_PEQ_Master::K2Node_Select_Default_3' has a wrong offset!");
static_assert(offsetof(BP_AN_PEQ_Master_C_ExecuteUbergraph_BP_AN_PEQ_Master, K2Node_ComponentBoundEvent_bLightActive) == 0x00019C, "Member 'BP_AN_PEQ_Master_C_ExecuteUbergraph_BP_AN_PEQ_Master::K2Node_ComponentBoundEvent_bLightActive' has a wrong offset!");
static_assert(offsetof(BP_AN_PEQ_Master_C_ExecuteUbergraph_BP_AN_PEQ_Master, K2Node_ComponentBoundEvent_bLightVisibility) == 0x00019D, "Member 'BP_AN_PEQ_Master_C_ExecuteUbergraph_BP_AN_PEQ_Master::K2Node_ComponentBoundEvent_bLightVisibility' has a wrong offset!");
static_assert(offsetof(BP_AN_PEQ_Master_C_ExecuteUbergraph_BP_AN_PEQ_Master, Temp_bool_Variable_4) == 0x00019E, "Member 'BP_AN_PEQ_Master_C_ExecuteUbergraph_BP_AN_PEQ_Master::Temp_bool_Variable_4' has a wrong offset!");
static_assert(offsetof(BP_AN_PEQ_Master_C_ExecuteUbergraph_BP_AN_PEQ_Master, CallFunc_Conv_BoolToFloat_ReturnValue) == 0x0001A0, "Member 'BP_AN_PEQ_Master_C_ExecuteUbergraph_BP_AN_PEQ_Master::CallFunc_Conv_BoolToFloat_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_AN_PEQ_Master_C_ExecuteUbergraph_BP_AN_PEQ_Master, K2Node_Select_Default_4) == 0x0001A4, "Member 'BP_AN_PEQ_Master_C_ExecuteUbergraph_BP_AN_PEQ_Master::K2Node_Select_Default_4' has a wrong offset!");
static_assert(offsetof(BP_AN_PEQ_Master_C_ExecuteUbergraph_BP_AN_PEQ_Master, CallFunc_Conv_BoolToFloat_ReturnValue_1) == 0x0001A8, "Member 'BP_AN_PEQ_Master_C_ExecuteUbergraph_BP_AN_PEQ_Master::CallFunc_Conv_BoolToFloat_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_AN_PEQ_Master_C_ExecuteUbergraph_BP_AN_PEQ_Master, Temp_bool_Variable_5) == 0x0001AC, "Member 'BP_AN_PEQ_Master_C_ExecuteUbergraph_BP_AN_PEQ_Master::Temp_bool_Variable_5' has a wrong offset!");
static_assert(offsetof(BP_AN_PEQ_Master_C_ExecuteUbergraph_BP_AN_PEQ_Master, CallFunc_CreateDynamicMaterialInstance_ReturnValue) == 0x0001B0, "Member 'BP_AN_PEQ_Master_C_ExecuteUbergraph_BP_AN_PEQ_Master::CallFunc_CreateDynamicMaterialInstance_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_AN_PEQ_Master_C_ExecuteUbergraph_BP_AN_PEQ_Master, K2Node_Select_Default_5) == 0x0001B8, "Member 'BP_AN_PEQ_Master_C_ExecuteUbergraph_BP_AN_PEQ_Master::K2Node_Select_Default_5' has a wrong offset!");
static_assert(offsetof(BP_AN_PEQ_Master_C_ExecuteUbergraph_BP_AN_PEQ_Master, CallFunc_Create_ReturnValue_4) == 0x0001C0, "Member 'BP_AN_PEQ_Master_C_ExecuteUbergraph_BP_AN_PEQ_Master::CallFunc_Create_ReturnValue_4' has a wrong offset!");
static_assert(offsetof(BP_AN_PEQ_Master_C_ExecuteUbergraph_BP_AN_PEQ_Master, CallFunc_IsDedicatedServer_ReturnValue_2) == 0x0001C8, "Member 'BP_AN_PEQ_Master_C_ExecuteUbergraph_BP_AN_PEQ_Master::CallFunc_IsDedicatedServer_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(BP_AN_PEQ_Master_C_ExecuteUbergraph_BP_AN_PEQ_Master, CallFunc_GetIcon_ReturnValue_2) == 0x0001D0, "Member 'BP_AN_PEQ_Master_C_ExecuteUbergraph_BP_AN_PEQ_Master::CallFunc_GetIcon_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(BP_AN_PEQ_Master_C_ExecuteUbergraph_BP_AN_PEQ_Master, CallFunc_Not_PreBool_ReturnValue) == 0x0001F8, "Member 'BP_AN_PEQ_Master_C_ExecuteUbergraph_BP_AN_PEQ_Master::CallFunc_Not_PreBool_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_AN_PEQ_Master_C_ExecuteUbergraph_BP_AN_PEQ_Master, CallFunc_GetIcon_ReturnValue_3) == 0x000200, "Member 'BP_AN_PEQ_Master_C_ExecuteUbergraph_BP_AN_PEQ_Master::CallFunc_GetIcon_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(BP_AN_PEQ_Master_C_ExecuteUbergraph_BP_AN_PEQ_Master, CallFunc_GetGBInstigator_ReturnValue_3) == 0x000228, "Member 'BP_AN_PEQ_Master_C_ExecuteUbergraph_BP_AN_PEQ_Master::CallFunc_GetGBInstigator_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(BP_AN_PEQ_Master_C_ExecuteUbergraph_BP_AN_PEQ_Master, K2Node_MakeStruct_GameplayEventData) == 0x000230, "Member 'BP_AN_PEQ_Master_C_ExecuteUbergraph_BP_AN_PEQ_Master::K2Node_MakeStruct_GameplayEventData' has a wrong offset!");
static_assert(offsetof(BP_AN_PEQ_Master_C_ExecuteUbergraph_BP_AN_PEQ_Master, K2Node_MakeStruct_GameplayEventData_1) == 0x0002E0, "Member 'BP_AN_PEQ_Master_C_ExecuteUbergraph_BP_AN_PEQ_Master::K2Node_MakeStruct_GameplayEventData_1' has a wrong offset!");
static_assert(offsetof(BP_AN_PEQ_Master_C_ExecuteUbergraph_BP_AN_PEQ_Master, K2Node_MakeStruct_GameplayEventData_2) == 0x000390, "Member 'BP_AN_PEQ_Master_C_ExecuteUbergraph_BP_AN_PEQ_Master::K2Node_MakeStruct_GameplayEventData_2' has a wrong offset!");
static_assert(offsetof(BP_AN_PEQ_Master_C_ExecuteUbergraph_BP_AN_PEQ_Master, K2Node_MakeStruct_GameplayEventData_3) == 0x000440, "Member 'BP_AN_PEQ_Master_C_ExecuteUbergraph_BP_AN_PEQ_Master::K2Node_MakeStruct_GameplayEventData_3' has a wrong offset!");
static_assert(offsetof(BP_AN_PEQ_Master_C_ExecuteUbergraph_BP_AN_PEQ_Master, CallFunc_GetEffect_ReturnValue) == 0x0004F0, "Member 'BP_AN_PEQ_Master_C_ExecuteUbergraph_BP_AN_PEQ_Master::CallFunc_GetEffect_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_AN_PEQ_Master_C_ExecuteUbergraph_BP_AN_PEQ_Master, CallFunc_GetEffect_ReturnValue_1) == 0x0004F8, "Member 'BP_AN_PEQ_Master_C_ExecuteUbergraph_BP_AN_PEQ_Master::CallFunc_GetEffect_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_AN_PEQ_Master_C_ExecuteUbergraph_BP_AN_PEQ_Master, CallFunc_GetGBInstigator_ReturnValue_4) == 0x000500, "Member 'BP_AN_PEQ_Master_C_ExecuteUbergraph_BP_AN_PEQ_Master::CallFunc_GetGBInstigator_ReturnValue_4' has a wrong offset!");
static_assert(offsetof(BP_AN_PEQ_Master_C_ExecuteUbergraph_BP_AN_PEQ_Master, K2Node_CreateDelegate_OutputDelegate_3) == 0x000508, "Member 'BP_AN_PEQ_Master_C_ExecuteUbergraph_BP_AN_PEQ_Master::K2Node_CreateDelegate_OutputDelegate_3' has a wrong offset!");

// Function BP_AN_PEQ_Master.BP_AN_PEQ_Master_C.BndEvt__BP_AN_PEQ_Master_IlluminatorSpotLight_K2Node_ComponentBoundEvent_1_OnLightUpdate__DelegateSignature
// 0x0002 (0x0002 - 0x0000)
struct BP_AN_PEQ_Master_C_BndEvt__BP_AN_PEQ_Master_IlluminatorSpotLight_K2Node_ComponentBoundEvent_1_OnLightUpdate__DelegateSignature final
{
public:
	bool                                          bLightActive;                                      // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          bLightVisibility;                                  // 0x0001(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(BP_AN_PEQ_Master_C_BndEvt__BP_AN_PEQ_Master_IlluminatorSpotLight_K2Node_ComponentBoundEvent_1_OnLightUpdate__DelegateSignature) == 0x000001, "Wrong alignment on BP_AN_PEQ_Master_C_BndEvt__BP_AN_PEQ_Master_IlluminatorSpotLight_K2Node_ComponentBoundEvent_1_OnLightUpdate__DelegateSignature");
static_assert(sizeof(BP_AN_PEQ_Master_C_BndEvt__BP_AN_PEQ_Master_IlluminatorSpotLight_K2Node_ComponentBoundEvent_1_OnLightUpdate__DelegateSignature) == 0x000002, "Wrong size on BP_AN_PEQ_Master_C_BndEvt__BP_AN_PEQ_Master_IlluminatorSpotLight_K2Node_ComponentBoundEvent_1_OnLightUpdate__DelegateSignature");
static_assert(offsetof(BP_AN_PEQ_Master_C_BndEvt__BP_AN_PEQ_Master_IlluminatorSpotLight_K2Node_ComponentBoundEvent_1_OnLightUpdate__DelegateSignature, bLightActive) == 0x000000, "Member 'BP_AN_PEQ_Master_C_BndEvt__BP_AN_PEQ_Master_IlluminatorSpotLight_K2Node_ComponentBoundEvent_1_OnLightUpdate__DelegateSignature::bLightActive' has a wrong offset!");
static_assert(offsetof(BP_AN_PEQ_Master_C_BndEvt__BP_AN_PEQ_Master_IlluminatorSpotLight_K2Node_ComponentBoundEvent_1_OnLightUpdate__DelegateSignature, bLightVisibility) == 0x000001, "Member 'BP_AN_PEQ_Master_C_BndEvt__BP_AN_PEQ_Master_IlluminatorSpotLight_K2Node_ComponentBoundEvent_1_OnLightUpdate__DelegateSignature::bLightVisibility' has a wrong offset!");

// Function BP_AN_PEQ_Master.BP_AN_PEQ_Master_C.OnAddedToInventoryEvent
// 0x0008 (0x0008 - 0x0000)
struct BP_AN_PEQ_Master_C_OnAddedToInventoryEvent final
{
public:
	class AGBCharacter*                           Character;                                         // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_AN_PEQ_Master_C_OnAddedToInventoryEvent) == 0x000008, "Wrong alignment on BP_AN_PEQ_Master_C_OnAddedToInventoryEvent");
static_assert(sizeof(BP_AN_PEQ_Master_C_OnAddedToInventoryEvent) == 0x000008, "Wrong size on BP_AN_PEQ_Master_C_OnAddedToInventoryEvent");
static_assert(offsetof(BP_AN_PEQ_Master_C_OnAddedToInventoryEvent, Character) == 0x000000, "Member 'BP_AN_PEQ_Master_C_OnAddedToInventoryEvent::Character' has a wrong offset!");

// Function BP_AN_PEQ_Master.BP_AN_PEQ_Master_C.OnSelected_IlluminatorUse_Event
// 0x0004 (0x0004 - 0x0000)
struct BP_AN_PEQ_Master_C_OnSelected_IlluminatorUse_Event final
{
public:
	int32                                         Index_0;                                           // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_AN_PEQ_Master_C_OnSelected_IlluminatorUse_Event) == 0x000004, "Wrong alignment on BP_AN_PEQ_Master_C_OnSelected_IlluminatorUse_Event");
static_assert(sizeof(BP_AN_PEQ_Master_C_OnSelected_IlluminatorUse_Event) == 0x000004, "Wrong size on BP_AN_PEQ_Master_C_OnSelected_IlluminatorUse_Event");
static_assert(offsetof(BP_AN_PEQ_Master_C_OnSelected_IlluminatorUse_Event, Index_0) == 0x000000, "Member 'BP_AN_PEQ_Master_C_OnSelected_IlluminatorUse_Event::Index_0' has a wrong offset!");

// Function BP_AN_PEQ_Master.BP_AN_PEQ_Master_C.AddIlluminatorUseEntry
// 0x0008 (0x0008 - 0x0000)
struct BP_AN_PEQ_Master_C_AddIlluminatorUseEntry final
{
public:
	class UWBP_RadialMenu_C*                      UsageMenu;                                         // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_AN_PEQ_Master_C_AddIlluminatorUseEntry) == 0x000008, "Wrong alignment on BP_AN_PEQ_Master_C_AddIlluminatorUseEntry");
static_assert(sizeof(BP_AN_PEQ_Master_C_AddIlluminatorUseEntry) == 0x000008, "Wrong size on BP_AN_PEQ_Master_C_AddIlluminatorUseEntry");
static_assert(offsetof(BP_AN_PEQ_Master_C_AddIlluminatorUseEntry, UsageMenu) == 0x000000, "Member 'BP_AN_PEQ_Master_C_AddIlluminatorUseEntry::UsageMenu' has a wrong offset!");

// Function BP_AN_PEQ_Master.BP_AN_PEQ_Master_C.OnSelected_LaserUse_Event
// 0x0004 (0x0004 - 0x0000)
struct BP_AN_PEQ_Master_C_OnSelected_LaserUse_Event final
{
public:
	int32                                         Index_0;                                           // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_AN_PEQ_Master_C_OnSelected_LaserUse_Event) == 0x000004, "Wrong alignment on BP_AN_PEQ_Master_C_OnSelected_LaserUse_Event");
static_assert(sizeof(BP_AN_PEQ_Master_C_OnSelected_LaserUse_Event) == 0x000004, "Wrong size on BP_AN_PEQ_Master_C_OnSelected_LaserUse_Event");
static_assert(offsetof(BP_AN_PEQ_Master_C_OnSelected_LaserUse_Event, Index_0) == 0x000000, "Member 'BP_AN_PEQ_Master_C_OnSelected_LaserUse_Event::Index_0' has a wrong offset!");

// Function BP_AN_PEQ_Master.BP_AN_PEQ_Master_C.AddLaserUseEntry
// 0x0008 (0x0008 - 0x0000)
struct BP_AN_PEQ_Master_C_AddLaserUseEntry final
{
public:
	class UWBP_RadialMenu_C*                      UsageMenu;                                         // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_AN_PEQ_Master_C_AddLaserUseEntry) == 0x000008, "Wrong alignment on BP_AN_PEQ_Master_C_AddLaserUseEntry");
static_assert(sizeof(BP_AN_PEQ_Master_C_AddLaserUseEntry) == 0x000008, "Wrong size on BP_AN_PEQ_Master_C_AddLaserUseEntry");
static_assert(offsetof(BP_AN_PEQ_Master_C_AddLaserUseEntry, UsageMenu) == 0x000000, "Member 'BP_AN_PEQ_Master_C_AddLaserUseEntry::UsageMenu' has a wrong offset!");

// Function BP_AN_PEQ_Master.BP_AN_PEQ_Master_C.OnSelected_IlluminatorChangeMode_Event
// 0x0004 (0x0004 - 0x0000)
struct BP_AN_PEQ_Master_C_OnSelected_IlluminatorChangeMode_Event final
{
public:
	int32                                         Index_0;                                           // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_AN_PEQ_Master_C_OnSelected_IlluminatorChangeMode_Event) == 0x000004, "Wrong alignment on BP_AN_PEQ_Master_C_OnSelected_IlluminatorChangeMode_Event");
static_assert(sizeof(BP_AN_PEQ_Master_C_OnSelected_IlluminatorChangeMode_Event) == 0x000004, "Wrong size on BP_AN_PEQ_Master_C_OnSelected_IlluminatorChangeMode_Event");
static_assert(offsetof(BP_AN_PEQ_Master_C_OnSelected_IlluminatorChangeMode_Event, Index_0) == 0x000000, "Member 'BP_AN_PEQ_Master_C_OnSelected_IlluminatorChangeMode_Event::Index_0' has a wrong offset!");

// Function BP_AN_PEQ_Master.BP_AN_PEQ_Master_C.AddIlluminatorChangeModeEntry
// 0x0008 (0x0008 - 0x0000)
struct BP_AN_PEQ_Master_C_AddIlluminatorChangeModeEntry final
{
public:
	class UWBP_RadialMenu_C*                      UsageMenu;                                         // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_AN_PEQ_Master_C_AddIlluminatorChangeModeEntry) == 0x000008, "Wrong alignment on BP_AN_PEQ_Master_C_AddIlluminatorChangeModeEntry");
static_assert(sizeof(BP_AN_PEQ_Master_C_AddIlluminatorChangeModeEntry) == 0x000008, "Wrong size on BP_AN_PEQ_Master_C_AddIlluminatorChangeModeEntry");
static_assert(offsetof(BP_AN_PEQ_Master_C_AddIlluminatorChangeModeEntry, UsageMenu) == 0x000000, "Member 'BP_AN_PEQ_Master_C_AddIlluminatorChangeModeEntry::UsageMenu' has a wrong offset!");

// Function BP_AN_PEQ_Master.BP_AN_PEQ_Master_C.OnSelected_LaserMode_Event
// 0x0004 (0x0004 - 0x0000)
struct BP_AN_PEQ_Master_C_OnSelected_LaserMode_Event final
{
public:
	int32                                         Index_0;                                           // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_AN_PEQ_Master_C_OnSelected_LaserMode_Event) == 0x000004, "Wrong alignment on BP_AN_PEQ_Master_C_OnSelected_LaserMode_Event");
static_assert(sizeof(BP_AN_PEQ_Master_C_OnSelected_LaserMode_Event) == 0x000004, "Wrong size on BP_AN_PEQ_Master_C_OnSelected_LaserMode_Event");
static_assert(offsetof(BP_AN_PEQ_Master_C_OnSelected_LaserMode_Event, Index_0) == 0x000000, "Member 'BP_AN_PEQ_Master_C_OnSelected_LaserMode_Event::Index_0' has a wrong offset!");

// Function BP_AN_PEQ_Master.BP_AN_PEQ_Master_C.AddLaseMode
// 0x0008 (0x0008 - 0x0000)
struct BP_AN_PEQ_Master_C_AddLaseMode final
{
public:
	class UWBP_RadialMenu_C*                      UsageMenu;                                         // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_AN_PEQ_Master_C_AddLaseMode) == 0x000008, "Wrong alignment on BP_AN_PEQ_Master_C_AddLaseMode");
static_assert(sizeof(BP_AN_PEQ_Master_C_AddLaseMode) == 0x000008, "Wrong size on BP_AN_PEQ_Master_C_AddLaseMode");
static_assert(offsetof(BP_AN_PEQ_Master_C_AddLaseMode, UsageMenu) == 0x000000, "Member 'BP_AN_PEQ_Master_C_AddLaseMode::UsageMenu' has a wrong offset!");

// Function BP_AN_PEQ_Master.BP_AN_PEQ_Master_C.OnRemovedFromInventoryEvent
// 0x0008 (0x0008 - 0x0000)
struct BP_AN_PEQ_Master_C_OnRemovedFromInventoryEvent final
{
public:
	class AGBCharacter*                           Character;                                         // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_AN_PEQ_Master_C_OnRemovedFromInventoryEvent) == 0x000008, "Wrong alignment on BP_AN_PEQ_Master_C_OnRemovedFromInventoryEvent");
static_assert(sizeof(BP_AN_PEQ_Master_C_OnRemovedFromInventoryEvent) == 0x000008, "Wrong size on BP_AN_PEQ_Master_C_OnRemovedFromInventoryEvent");
static_assert(offsetof(BP_AN_PEQ_Master_C_OnRemovedFromInventoryEvent, Character) == 0x000000, "Member 'BP_AN_PEQ_Master_C_OnRemovedFromInventoryEvent::Character' has a wrong offset!");

// Function BP_AN_PEQ_Master.BP_AN_PEQ_Master_C.MulticastSetIlluminatorHigh
// 0x0001 (0x0001 - 0x0000)
struct BP_AN_PEQ_Master_C_MulticastSetIlluminatorHigh final
{
public:
	bool                                          bIlluminator_High;                                 // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(BP_AN_PEQ_Master_C_MulticastSetIlluminatorHigh) == 0x000001, "Wrong alignment on BP_AN_PEQ_Master_C_MulticastSetIlluminatorHigh");
static_assert(sizeof(BP_AN_PEQ_Master_C_MulticastSetIlluminatorHigh) == 0x000001, "Wrong size on BP_AN_PEQ_Master_C_MulticastSetIlluminatorHigh");
static_assert(offsetof(BP_AN_PEQ_Master_C_MulticastSetIlluminatorHigh, bIlluminator_High) == 0x000000, "Member 'BP_AN_PEQ_Master_C_MulticastSetIlluminatorHigh::bIlluminator_High' has a wrong offset!");

// Function BP_AN_PEQ_Master.BP_AN_PEQ_Master_C.AddAttachedUseMenuEntries
// 0x0008 (0x0008 - 0x0000)
struct BP_AN_PEQ_Master_C_AddAttachedUseMenuEntries final
{
public:
	class UUserWidget*                            UsageMenu;                                         // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_AN_PEQ_Master_C_AddAttachedUseMenuEntries) == 0x000008, "Wrong alignment on BP_AN_PEQ_Master_C_AddAttachedUseMenuEntries");
static_assert(sizeof(BP_AN_PEQ_Master_C_AddAttachedUseMenuEntries) == 0x000008, "Wrong size on BP_AN_PEQ_Master_C_AddAttachedUseMenuEntries");
static_assert(offsetof(BP_AN_PEQ_Master_C_AddAttachedUseMenuEntries, UsageMenu) == 0x000000, "Member 'BP_AN_PEQ_Master_C_AddAttachedUseMenuEntries::UsageMenu' has a wrong offset!");

// Function BP_AN_PEQ_Master.BP_AN_PEQ_Master_C.UserConstructionScript
// 0x0004 (0x0004 - 0x0000)
struct BP_AN_PEQ_Master_C_UserConstructionScript final
{
public:
	bool                                          CallFunc_K2_AttachToComponent_ReturnValue;         // 0x0000(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_K2_AttachToComponent_ReturnValue_1;       // 0x0001(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_DoesSocketExist_ReturnValue;              // 0x0002(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_DoesSocketExist_ReturnValue_1;            // 0x0003(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(BP_AN_PEQ_Master_C_UserConstructionScript) == 0x000001, "Wrong alignment on BP_AN_PEQ_Master_C_UserConstructionScript");
static_assert(sizeof(BP_AN_PEQ_Master_C_UserConstructionScript) == 0x000004, "Wrong size on BP_AN_PEQ_Master_C_UserConstructionScript");
static_assert(offsetof(BP_AN_PEQ_Master_C_UserConstructionScript, CallFunc_K2_AttachToComponent_ReturnValue) == 0x000000, "Member 'BP_AN_PEQ_Master_C_UserConstructionScript::CallFunc_K2_AttachToComponent_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_AN_PEQ_Master_C_UserConstructionScript, CallFunc_K2_AttachToComponent_ReturnValue_1) == 0x000001, "Member 'BP_AN_PEQ_Master_C_UserConstructionScript::CallFunc_K2_AttachToComponent_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_AN_PEQ_Master_C_UserConstructionScript, CallFunc_DoesSocketExist_ReturnValue) == 0x000002, "Member 'BP_AN_PEQ_Master_C_UserConstructionScript::CallFunc_DoesSocketExist_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_AN_PEQ_Master_C_UserConstructionScript, CallFunc_DoesSocketExist_ReturnValue_1) == 0x000003, "Member 'BP_AN_PEQ_Master_C_UserConstructionScript::CallFunc_DoesSocketExist_ReturnValue_1' has a wrong offset!");

// Function BP_AN_PEQ_Master.BP_AN_PEQ_Master_C.AllowUsageWhileAttached
// 0x0002 (0x0002 - 0x0000)
struct BP_AN_PEQ_Master_C_AllowUsageWhileAttached final
{
public:
	bool                                          ReturnValue;                                       // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsEquipped_ReturnValue;                   // 0x0001(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(BP_AN_PEQ_Master_C_AllowUsageWhileAttached) == 0x000001, "Wrong alignment on BP_AN_PEQ_Master_C_AllowUsageWhileAttached");
static_assert(sizeof(BP_AN_PEQ_Master_C_AllowUsageWhileAttached) == 0x000002, "Wrong size on BP_AN_PEQ_Master_C_AllowUsageWhileAttached");
static_assert(offsetof(BP_AN_PEQ_Master_C_AllowUsageWhileAttached, ReturnValue) == 0x000000, "Member 'BP_AN_PEQ_Master_C_AllowUsageWhileAttached::ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_AN_PEQ_Master_C_AllowUsageWhileAttached, CallFunc_IsEquipped_ReturnValue) == 0x000001, "Member 'BP_AN_PEQ_Master_C_AllowUsageWhileAttached::CallFunc_IsEquipped_ReturnValue' has a wrong offset!");

// Function BP_AN_PEQ_Master.BP_AN_PEQ_Master_C.GetAreWeADS
// 0x0028 (0x0028 - 0x0000)
struct BP_AN_PEQ_Master_C_GetAreWeADS final
{
public:
	bool                                          WeAreADS;                                          // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_1[0x7];                                        // 0x0001(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class APawn*                                  CallFunc_GetInstigator_ReturnValue;                // 0x0008(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AGBCharacter*                           K2Node_DynamicCast_AsGBCharacter;                  // 0x0010(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0018(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_19[0x3];                                       // 0x0019(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         CallFunc_GetEngagedAlpha_ReturnValue;              // 0x001C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Greater_FloatFloat_ReturnValue;           // 0x0020(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(BP_AN_PEQ_Master_C_GetAreWeADS) == 0x000008, "Wrong alignment on BP_AN_PEQ_Master_C_GetAreWeADS");
static_assert(sizeof(BP_AN_PEQ_Master_C_GetAreWeADS) == 0x000028, "Wrong size on BP_AN_PEQ_Master_C_GetAreWeADS");
static_assert(offsetof(BP_AN_PEQ_Master_C_GetAreWeADS, WeAreADS) == 0x000000, "Member 'BP_AN_PEQ_Master_C_GetAreWeADS::WeAreADS' has a wrong offset!");
static_assert(offsetof(BP_AN_PEQ_Master_C_GetAreWeADS, CallFunc_GetInstigator_ReturnValue) == 0x000008, "Member 'BP_AN_PEQ_Master_C_GetAreWeADS::CallFunc_GetInstigator_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_AN_PEQ_Master_C_GetAreWeADS, K2Node_DynamicCast_AsGBCharacter) == 0x000010, "Member 'BP_AN_PEQ_Master_C_GetAreWeADS::K2Node_DynamicCast_AsGBCharacter' has a wrong offset!");
static_assert(offsetof(BP_AN_PEQ_Master_C_GetAreWeADS, K2Node_DynamicCast_bSuccess) == 0x000018, "Member 'BP_AN_PEQ_Master_C_GetAreWeADS::K2Node_DynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(BP_AN_PEQ_Master_C_GetAreWeADS, CallFunc_GetEngagedAlpha_ReturnValue) == 0x00001C, "Member 'BP_AN_PEQ_Master_C_GetAreWeADS::CallFunc_GetEngagedAlpha_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_AN_PEQ_Master_C_GetAreWeADS, CallFunc_Greater_FloatFloat_ReturnValue) == 0x000020, "Member 'BP_AN_PEQ_Master_C_GetAreWeADS::CallFunc_Greater_FloatFloat_ReturnValue' has a wrong offset!");

// Function BP_AN_PEQ_Master.BP_AN_PEQ_Master_C.SetIRMode
// 0x0002 (0x0002 - 0x0000)
struct BP_AN_PEQ_Master_C_SetIRMode final
{
public:
	bool                                          bNewIRMode;                                        // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_NotEqual_BoolBool_ReturnValue;            // 0x0001(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(BP_AN_PEQ_Master_C_SetIRMode) == 0x000001, "Wrong alignment on BP_AN_PEQ_Master_C_SetIRMode");
static_assert(sizeof(BP_AN_PEQ_Master_C_SetIRMode) == 0x000002, "Wrong size on BP_AN_PEQ_Master_C_SetIRMode");
static_assert(offsetof(BP_AN_PEQ_Master_C_SetIRMode, bNewIRMode) == 0x000000, "Member 'BP_AN_PEQ_Master_C_SetIRMode::bNewIRMode' has a wrong offset!");
static_assert(offsetof(BP_AN_PEQ_Master_C_SetIRMode, CallFunc_NotEqual_BoolBool_ReturnValue) == 0x000001, "Member 'BP_AN_PEQ_Master_C_SetIRMode::CallFunc_NotEqual_BoolBool_ReturnValue' has a wrong offset!");

// Function BP_AN_PEQ_Master.BP_AN_PEQ_Master_C.GetIlluminatorActive
// 0x0001 (0x0001 - 0x0000)
struct BP_AN_PEQ_Master_C_GetIlluminatorActive final
{
public:
	bool                                          OutActive;                                         // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(BP_AN_PEQ_Master_C_GetIlluminatorActive) == 0x000001, "Wrong alignment on BP_AN_PEQ_Master_C_GetIlluminatorActive");
static_assert(sizeof(BP_AN_PEQ_Master_C_GetIlluminatorActive) == 0x000001, "Wrong size on BP_AN_PEQ_Master_C_GetIlluminatorActive");
static_assert(offsetof(BP_AN_PEQ_Master_C_GetIlluminatorActive, OutActive) == 0x000000, "Member 'BP_AN_PEQ_Master_C_GetIlluminatorActive::OutActive' has a wrong offset!");

// Function BP_AN_PEQ_Master.BP_AN_PEQ_Master_C.GetIlluminatorHigh
// 0x0001 (0x0001 - 0x0000)
struct BP_AN_PEQ_Master_C_GetIlluminatorHigh final
{
public:
	bool                                          OutHigh;                                           // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(BP_AN_PEQ_Master_C_GetIlluminatorHigh) == 0x000001, "Wrong alignment on BP_AN_PEQ_Master_C_GetIlluminatorHigh");
static_assert(sizeof(BP_AN_PEQ_Master_C_GetIlluminatorHigh) == 0x000001, "Wrong size on BP_AN_PEQ_Master_C_GetIlluminatorHigh");
static_assert(offsetof(BP_AN_PEQ_Master_C_GetIlluminatorHigh, OutHigh) == 0x000000, "Member 'BP_AN_PEQ_Master_C_GetIlluminatorHigh::OutHigh' has a wrong offset!");

// Function BP_AN_PEQ_Master.BP_AN_PEQ_Master_C.GetIRMode
// 0x0001 (0x0001 - 0x0000)
struct BP_AN_PEQ_Master_C_GetIRMode final
{
public:
	bool                                          bOutIRMode;                                        // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(BP_AN_PEQ_Master_C_GetIRMode) == 0x000001, "Wrong alignment on BP_AN_PEQ_Master_C_GetIRMode");
static_assert(sizeof(BP_AN_PEQ_Master_C_GetIRMode) == 0x000001, "Wrong size on BP_AN_PEQ_Master_C_GetIRMode");
static_assert(offsetof(BP_AN_PEQ_Master_C_GetIRMode, bOutIRMode) == 0x000000, "Member 'BP_AN_PEQ_Master_C_GetIRMode::bOutIRMode' has a wrong offset!");

}

