#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Character_Blufor

#include "Basic.hpp"


namespace SDK::Params
{

// Function BP_Character_Blufor.BP_Character_Blufor_C.ExecuteUbergraph_BP_Character_Blufor
// 0x00F8 (0x00F8 - 0x0000)
struct BP_Character_Blufor_C_ExecuteUbergraph_BP_Character_Blufor final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	TSubclassOf<class UObject>                    K2Node_CustomEvent_Loaded;                         // 0x0008(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, UObjectWrapper, HasGetValueTypeHash)
	class AGBInvItem*                             CallFunc_GetFirstInvItemByItemAssetId_ReturnValue; // 0x0010(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UClass*                                 Temp_class_Variable;                               // 0x0018(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0020(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_Not_PreBool_ReturnValue;                  // 0x0021(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_22[0x2];                                       // 0x0022(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	TDelegate<void(TSubclassOf<class UObject> Loaded)> K2Node_CreateDelegate_OutputDelegate;         // 0x0024(0x0010)(ZeroConstructor, NoDestructor)
	uint8                                         Pad_34[0x4];                                       // 0x0034(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	TSubclassOf<class UObject>                    K2Node_CustomEvent_Loaded_1;                       // 0x0038(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, UObjectWrapper, HasGetValueTypeHash)
	class UClass*                                 Temp_class_Variable_1;                             // 0x0040(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TDelegate<void(TSubclassOf<class UObject> Loaded)> K2Node_CreateDelegate_OutputDelegate_1;       // 0x0048(0x0010)(ZeroConstructor, NoDestructor)
	class AController*                            K2Node_Event_NewController;                        // 0x0058(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AKytGroup*                              CallFunc_GetNamedKytGroup_ReturnValue;             // 0x0060(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TArray<class FName>                           CallFunc_GetBundlesToLoad_ReturnValue;             // 0x0068(0x0010)(ReferenceParm)
	class UAsyncActionLoadPrimaryAssetClass*      CallFunc_AsyncLoadPrimaryAssetClass_ReturnValue;   // 0x0078(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TSubclassOf<class UObject>                    CallFunc_GetClassFromPrimaryAssetId_ReturnValue;   // 0x0080(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, UObjectWrapper, HasGetValueTypeHash)
	class UClass*                                 K2Node_ClassDynamicCast_AsGBInv_Item;              // 0x0088(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_ClassDynamicCast_bSuccess;                  // 0x0090(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsValid_ReturnValue_1;                    // 0x0091(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsServer_ReturnValue;                     // 0x0092(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_93[0x5];                                       // 0x0093(0x0005)(Fixing Size After Last Property [ Dumper-7 ])
	class AGBInvItem*                             CallFunc_SpawnInvItem_ReturnValue;                 // 0x0098(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TSubclassOf<class UObject>                    CallFunc_GetClassFromPrimaryAssetId_ReturnValue_1; // 0x00A0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, UObjectWrapper, HasGetValueTypeHash)
	class UClass*                                 K2Node_ClassDynamicCast_AsGBInv_Item_1;            // 0x00A8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_ClassDynamicCast_bSuccess_1;                // 0x00B0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_B1[0x7];                                       // 0x00B1(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class AGBInvItem*                             CallFunc_SpawnInvItem_ReturnValue_1;               // 0x00B8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AGBInvItem*                             CallFunc_GetFirstInvItemByItemAssetId_ReturnValue_1; // 0x00C0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_2;                    // 0x00C8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_C9[0x7];                                       // 0x00C9(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<class FName>                           CallFunc_GetBundlesToLoad_ReturnValue_1;           // 0x00D0(0x0010)(ReferenceParm)
	bool                                          CallFunc_Not_PreBool_ReturnValue_1;                // 0x00E0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_E1[0x7];                                       // 0x00E1(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UAsyncActionLoadPrimaryAssetClass*      CallFunc_AsyncLoadPrimaryAssetClass_ReturnValue_1; // 0x00E8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsServer_ReturnValue_1;                   // 0x00F0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsValid_ReturnValue_3;                    // 0x00F1(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(BP_Character_Blufor_C_ExecuteUbergraph_BP_Character_Blufor) == 0x000008, "Wrong alignment on BP_Character_Blufor_C_ExecuteUbergraph_BP_Character_Blufor");
static_assert(sizeof(BP_Character_Blufor_C_ExecuteUbergraph_BP_Character_Blufor) == 0x0000F8, "Wrong size on BP_Character_Blufor_C_ExecuteUbergraph_BP_Character_Blufor");
static_assert(offsetof(BP_Character_Blufor_C_ExecuteUbergraph_BP_Character_Blufor, EntryPoint) == 0x000000, "Member 'BP_Character_Blufor_C_ExecuteUbergraph_BP_Character_Blufor::EntryPoint' has a wrong offset!");
static_assert(offsetof(BP_Character_Blufor_C_ExecuteUbergraph_BP_Character_Blufor, K2Node_CustomEvent_Loaded) == 0x000008, "Member 'BP_Character_Blufor_C_ExecuteUbergraph_BP_Character_Blufor::K2Node_CustomEvent_Loaded' has a wrong offset!");
static_assert(offsetof(BP_Character_Blufor_C_ExecuteUbergraph_BP_Character_Blufor, CallFunc_GetFirstInvItemByItemAssetId_ReturnValue) == 0x000010, "Member 'BP_Character_Blufor_C_ExecuteUbergraph_BP_Character_Blufor::CallFunc_GetFirstInvItemByItemAssetId_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Character_Blufor_C_ExecuteUbergraph_BP_Character_Blufor, Temp_class_Variable) == 0x000018, "Member 'BP_Character_Blufor_C_ExecuteUbergraph_BP_Character_Blufor::Temp_class_Variable' has a wrong offset!");
static_assert(offsetof(BP_Character_Blufor_C_ExecuteUbergraph_BP_Character_Blufor, CallFunc_IsValid_ReturnValue) == 0x000020, "Member 'BP_Character_Blufor_C_ExecuteUbergraph_BP_Character_Blufor::CallFunc_IsValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Character_Blufor_C_ExecuteUbergraph_BP_Character_Blufor, CallFunc_Not_PreBool_ReturnValue) == 0x000021, "Member 'BP_Character_Blufor_C_ExecuteUbergraph_BP_Character_Blufor::CallFunc_Not_PreBool_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Character_Blufor_C_ExecuteUbergraph_BP_Character_Blufor, K2Node_CreateDelegate_OutputDelegate) == 0x000024, "Member 'BP_Character_Blufor_C_ExecuteUbergraph_BP_Character_Blufor::K2Node_CreateDelegate_OutputDelegate' has a wrong offset!");
static_assert(offsetof(BP_Character_Blufor_C_ExecuteUbergraph_BP_Character_Blufor, K2Node_CustomEvent_Loaded_1) == 0x000038, "Member 'BP_Character_Blufor_C_ExecuteUbergraph_BP_Character_Blufor::K2Node_CustomEvent_Loaded_1' has a wrong offset!");
static_assert(offsetof(BP_Character_Blufor_C_ExecuteUbergraph_BP_Character_Blufor, Temp_class_Variable_1) == 0x000040, "Member 'BP_Character_Blufor_C_ExecuteUbergraph_BP_Character_Blufor::Temp_class_Variable_1' has a wrong offset!");
static_assert(offsetof(BP_Character_Blufor_C_ExecuteUbergraph_BP_Character_Blufor, K2Node_CreateDelegate_OutputDelegate_1) == 0x000048, "Member 'BP_Character_Blufor_C_ExecuteUbergraph_BP_Character_Blufor::K2Node_CreateDelegate_OutputDelegate_1' has a wrong offset!");
static_assert(offsetof(BP_Character_Blufor_C_ExecuteUbergraph_BP_Character_Blufor, K2Node_Event_NewController) == 0x000058, "Member 'BP_Character_Blufor_C_ExecuteUbergraph_BP_Character_Blufor::K2Node_Event_NewController' has a wrong offset!");
static_assert(offsetof(BP_Character_Blufor_C_ExecuteUbergraph_BP_Character_Blufor, CallFunc_GetNamedKytGroup_ReturnValue) == 0x000060, "Member 'BP_Character_Blufor_C_ExecuteUbergraph_BP_Character_Blufor::CallFunc_GetNamedKytGroup_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Character_Blufor_C_ExecuteUbergraph_BP_Character_Blufor, CallFunc_GetBundlesToLoad_ReturnValue) == 0x000068, "Member 'BP_Character_Blufor_C_ExecuteUbergraph_BP_Character_Blufor::CallFunc_GetBundlesToLoad_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Character_Blufor_C_ExecuteUbergraph_BP_Character_Blufor, CallFunc_AsyncLoadPrimaryAssetClass_ReturnValue) == 0x000078, "Member 'BP_Character_Blufor_C_ExecuteUbergraph_BP_Character_Blufor::CallFunc_AsyncLoadPrimaryAssetClass_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Character_Blufor_C_ExecuteUbergraph_BP_Character_Blufor, CallFunc_GetClassFromPrimaryAssetId_ReturnValue) == 0x000080, "Member 'BP_Character_Blufor_C_ExecuteUbergraph_BP_Character_Blufor::CallFunc_GetClassFromPrimaryAssetId_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Character_Blufor_C_ExecuteUbergraph_BP_Character_Blufor, K2Node_ClassDynamicCast_AsGBInv_Item) == 0x000088, "Member 'BP_Character_Blufor_C_ExecuteUbergraph_BP_Character_Blufor::K2Node_ClassDynamicCast_AsGBInv_Item' has a wrong offset!");
static_assert(offsetof(BP_Character_Blufor_C_ExecuteUbergraph_BP_Character_Blufor, K2Node_ClassDynamicCast_bSuccess) == 0x000090, "Member 'BP_Character_Blufor_C_ExecuteUbergraph_BP_Character_Blufor::K2Node_ClassDynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(BP_Character_Blufor_C_ExecuteUbergraph_BP_Character_Blufor, CallFunc_IsValid_ReturnValue_1) == 0x000091, "Member 'BP_Character_Blufor_C_ExecuteUbergraph_BP_Character_Blufor::CallFunc_IsValid_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_Character_Blufor_C_ExecuteUbergraph_BP_Character_Blufor, CallFunc_IsServer_ReturnValue) == 0x000092, "Member 'BP_Character_Blufor_C_ExecuteUbergraph_BP_Character_Blufor::CallFunc_IsServer_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Character_Blufor_C_ExecuteUbergraph_BP_Character_Blufor, CallFunc_SpawnInvItem_ReturnValue) == 0x000098, "Member 'BP_Character_Blufor_C_ExecuteUbergraph_BP_Character_Blufor::CallFunc_SpawnInvItem_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Character_Blufor_C_ExecuteUbergraph_BP_Character_Blufor, CallFunc_GetClassFromPrimaryAssetId_ReturnValue_1) == 0x0000A0, "Member 'BP_Character_Blufor_C_ExecuteUbergraph_BP_Character_Blufor::CallFunc_GetClassFromPrimaryAssetId_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_Character_Blufor_C_ExecuteUbergraph_BP_Character_Blufor, K2Node_ClassDynamicCast_AsGBInv_Item_1) == 0x0000A8, "Member 'BP_Character_Blufor_C_ExecuteUbergraph_BP_Character_Blufor::K2Node_ClassDynamicCast_AsGBInv_Item_1' has a wrong offset!");
static_assert(offsetof(BP_Character_Blufor_C_ExecuteUbergraph_BP_Character_Blufor, K2Node_ClassDynamicCast_bSuccess_1) == 0x0000B0, "Member 'BP_Character_Blufor_C_ExecuteUbergraph_BP_Character_Blufor::K2Node_ClassDynamicCast_bSuccess_1' has a wrong offset!");
static_assert(offsetof(BP_Character_Blufor_C_ExecuteUbergraph_BP_Character_Blufor, CallFunc_SpawnInvItem_ReturnValue_1) == 0x0000B8, "Member 'BP_Character_Blufor_C_ExecuteUbergraph_BP_Character_Blufor::CallFunc_SpawnInvItem_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_Character_Blufor_C_ExecuteUbergraph_BP_Character_Blufor, CallFunc_GetFirstInvItemByItemAssetId_ReturnValue_1) == 0x0000C0, "Member 'BP_Character_Blufor_C_ExecuteUbergraph_BP_Character_Blufor::CallFunc_GetFirstInvItemByItemAssetId_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_Character_Blufor_C_ExecuteUbergraph_BP_Character_Blufor, CallFunc_IsValid_ReturnValue_2) == 0x0000C8, "Member 'BP_Character_Blufor_C_ExecuteUbergraph_BP_Character_Blufor::CallFunc_IsValid_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(BP_Character_Blufor_C_ExecuteUbergraph_BP_Character_Blufor, CallFunc_GetBundlesToLoad_ReturnValue_1) == 0x0000D0, "Member 'BP_Character_Blufor_C_ExecuteUbergraph_BP_Character_Blufor::CallFunc_GetBundlesToLoad_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_Character_Blufor_C_ExecuteUbergraph_BP_Character_Blufor, CallFunc_Not_PreBool_ReturnValue_1) == 0x0000E0, "Member 'BP_Character_Blufor_C_ExecuteUbergraph_BP_Character_Blufor::CallFunc_Not_PreBool_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_Character_Blufor_C_ExecuteUbergraph_BP_Character_Blufor, CallFunc_AsyncLoadPrimaryAssetClass_ReturnValue_1) == 0x0000E8, "Member 'BP_Character_Blufor_C_ExecuteUbergraph_BP_Character_Blufor::CallFunc_AsyncLoadPrimaryAssetClass_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_Character_Blufor_C_ExecuteUbergraph_BP_Character_Blufor, CallFunc_IsServer_ReturnValue_1) == 0x0000F0, "Member 'BP_Character_Blufor_C_ExecuteUbergraph_BP_Character_Blufor::CallFunc_IsServer_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_Character_Blufor_C_ExecuteUbergraph_BP_Character_Blufor, CallFunc_IsValid_ReturnValue_3) == 0x0000F1, "Member 'BP_Character_Blufor_C_ExecuteUbergraph_BP_Character_Blufor::CallFunc_IsValid_ReturnValue_3' has a wrong offset!");

// Function BP_Character_Blufor.BP_Character_Blufor_C.ReceivePossessed
// 0x0008 (0x0008 - 0x0000)
struct BP_Character_Blufor_C_ReceivePossessed final
{
public:
	class AController*                            NewController;                                     // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_Character_Blufor_C_ReceivePossessed) == 0x000008, "Wrong alignment on BP_Character_Blufor_C_ReceivePossessed");
static_assert(sizeof(BP_Character_Blufor_C_ReceivePossessed) == 0x000008, "Wrong size on BP_Character_Blufor_C_ReceivePossessed");
static_assert(offsetof(BP_Character_Blufor_C_ReceivePossessed, NewController) == 0x000000, "Member 'BP_Character_Blufor_C_ReceivePossessed::NewController' has a wrong offset!");

// Function BP_Character_Blufor.BP_Character_Blufor_C.Completed_9FFA034A4B8041E28E5B8F224CED2E3C
// 0x0008 (0x0008 - 0x0000)
struct BP_Character_Blufor_C_Completed_9FFA034A4B8041E28E5B8F224CED2E3C final
{
public:
	TSubclassOf<class UObject>                    Loaded;                                            // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, UObjectWrapper, HasGetValueTypeHash)
};
static_assert(alignof(BP_Character_Blufor_C_Completed_9FFA034A4B8041E28E5B8F224CED2E3C) == 0x000008, "Wrong alignment on BP_Character_Blufor_C_Completed_9FFA034A4B8041E28E5B8F224CED2E3C");
static_assert(sizeof(BP_Character_Blufor_C_Completed_9FFA034A4B8041E28E5B8F224CED2E3C) == 0x000008, "Wrong size on BP_Character_Blufor_C_Completed_9FFA034A4B8041E28E5B8F224CED2E3C");
static_assert(offsetof(BP_Character_Blufor_C_Completed_9FFA034A4B8041E28E5B8F224CED2E3C, Loaded) == 0x000000, "Member 'BP_Character_Blufor_C_Completed_9FFA034A4B8041E28E5B8F224CED2E3C::Loaded' has a wrong offset!");

// Function BP_Character_Blufor.BP_Character_Blufor_C.Completed_3EC7DF01B6864D5FA3D612FE0199D784
// 0x0008 (0x0008 - 0x0000)
struct BP_Character_Blufor_C_Completed_3EC7DF01B6864D5FA3D612FE0199D784 final
{
public:
	TSubclassOf<class UObject>                    Loaded;                                            // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, UObjectWrapper, HasGetValueTypeHash)
};
static_assert(alignof(BP_Character_Blufor_C_Completed_3EC7DF01B6864D5FA3D612FE0199D784) == 0x000008, "Wrong alignment on BP_Character_Blufor_C_Completed_3EC7DF01B6864D5FA3D612FE0199D784");
static_assert(sizeof(BP_Character_Blufor_C_Completed_3EC7DF01B6864D5FA3D612FE0199D784) == 0x000008, "Wrong size on BP_Character_Blufor_C_Completed_3EC7DF01B6864D5FA3D612FE0199D784");
static_assert(offsetof(BP_Character_Blufor_C_Completed_3EC7DF01B6864D5FA3D612FE0199D784, Loaded) == 0x000000, "Member 'BP_Character_Blufor_C_Completed_3EC7DF01B6864D5FA3D612FE0199D784::Loaded' has a wrong offset!");

}

