#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_FAL_Magazine

#include "Basic.hpp"

#include "BP_Magazine_Master_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_FAL_Magazine.BP_FAL_Magazine_C
// 0x0010 (0x04D0 - 0x04C0)
class ABP_FAL_Magazine_C final : public ABP_Magazine_Master_C
{
public:
	class UStaticMeshComponent*                   S_cal_7_62NATO_2;                                  // 0x04C0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   S_cal_7_62NATO_1;                                  // 0x04C8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_FAL_Magazine_C">();
	}
	static class ABP_FAL_Magazine_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_FAL_Magazine_C>();
	}
};
static_assert(alignof(ABP_FAL_Magazine_C) == 0x000008, "Wrong alignment on ABP_FAL_Magazine_C");
static_assert(sizeof(ABP_FAL_Magazine_C) == 0x0004D0, "Wrong size on ABP_FAL_Magazine_C");
static_assert(offsetof(ABP_FAL_Magazine_C, S_cal_7_62NATO_2) == 0x0004C0, "Member 'ABP_FAL_Magazine_C::S_cal_7_62NATO_2' has a wrong offset!");
static_assert(offsetof(ABP_FAL_Magazine_C, S_cal_7_62NATO_1) == 0x0004C8, "Member 'ABP_FAL_Magazine_C::S_cal_7_62NATO_1' has a wrong offset!");

}

