#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Galil_ARM

#include "Basic.hpp"

#include "BP_Galil_Master_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_Galil_ARM.BP_Galil_ARM_C
// 0x0010 (0x05B8 - 0x05A8)
class ABP_Galil_ARM_C final : public ABP_Galil_Master_C
{
public:
	class UGBFrontSightPostComponent*             FrontSightPost;                                    // 0x05A8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UGBSightComponent*                      IronSight;                                         // 0x05B0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_Galil_ARM_C">();
	}
	static class ABP_Galil_ARM_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_Galil_ARM_C>();
	}
};
static_assert(alignof(ABP_Galil_ARM_C) == 0x000008, "Wrong alignment on ABP_Galil_ARM_C");
static_assert(sizeof(ABP_Galil_ARM_C) == 0x0005B8, "Wrong size on ABP_Galil_ARM_C");
static_assert(offsetof(ABP_Galil_ARM_C, FrontSightPost) == 0x0005A8, "Member 'ABP_Galil_ARM_C::FrontSightPost' has a wrong offset!");
static_assert(offsetof(ABP_Galil_ARM_C, IronSight) == 0x0005B0, "Member 'ABP_Galil_ARM_C::IronSight' has a wrong offset!");

}

