#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_ShellImpact_12_Concrete

#include "Basic.hpp"

#include "BP_CasingImpact_Master_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_ShellImpact_12_Concrete.BP_ShellImpact_12_Concrete_C
// 0x0000 (0x0288 - 0x0288)
class ABP_ShellImpact_12_Concrete_C final : public ABP_CasingImpact_Master_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_ShellImpact_12_Concrete_C">();
	}
	static class ABP_ShellImpact_12_Concrete_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_ShellImpact_12_Concrete_C>();
	}
};
static_assert(alignof(ABP_ShellImpact_12_Concrete_C) == 0x000008, "Wrong alignment on ABP_ShellImpact_12_Concrete_C");
static_assert(sizeof(ABP_ShellImpact_12_Concrete_C) == 0x000288, "Wrong size on ABP_ShellImpact_12_Concrete_C");

}

