#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Suppressor_ATG

#include "Basic.hpp"

#include "BP_Suppressor_Master_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_Suppressor_ATG.BP_Suppressor_ATG_C
// 0x0000 (0x0470 - 0x0470)
class ABP_Suppressor_ATG_C final : public ABP_Suppressor_Master_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_Suppressor_ATG_C">();
	}
	static class ABP_Suppressor_ATG_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_Suppressor_ATG_C>();
	}
};
static_assert(alignof(ABP_Suppressor_ATG_C) == 0x000008, "Wrong alignment on ABP_Suppressor_ATG_C");
static_assert(sizeof(ABP_Suppressor_ATG_C) == 0x000470, "Wrong size on ABP_Suppressor_ATG_C");

}

