#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_WristWatch_Modular

#include "Basic.hpp"

#include "GameplayTags_structs.hpp"


namespace SDK::Params
{

// Function BP_WristWatch_Modular.BP_WristWatch_Modular_C.ExecuteUbergraph_BP_WristWatch_Modular
// 0x01B8 (0x01B8 - 0x0000)
struct BP_WristWatch_Modular_C_ExecuteUbergraph_BP_WristWatch_Modular final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	TSubclassOf<class UObject>                    K2Node_CustomEvent_Loaded;                         // 0x0008(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, UObjectWrapper, HasGetValueTypeHash)
	class APlayerController*                      K2Node_CustomEvent_PlayerController_1;             // 0x0010(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AGBCharacter*                           K2Node_CustomEvent_Character_1;                    // 0x0018(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class APlayerController*                      K2Node_CustomEvent_PlayerController;               // 0x0020(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AGBCharacter*                           K2Node_CustomEvent_Character;                      // 0x0028(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AGBPlayerState*                         K2Node_CustomEvent_GBPlayerState;                  // 0x0030(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TDelegate<void(TSubclassOf<class UObject> Loaded)> K2Node_CreateDelegate_OutputDelegate;         // 0x0038(0x0010)(ZeroConstructor, NoDestructor)
	class AGBCharacter*                           K2Node_DynamicCast_AsGBCharacter;                  // 0x0048(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0050(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsLocallyViewed_ReturnValue;              // 0x0051(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsPlayerControlled_ReturnValue;           // 0x0052(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsLocallyControlled_ReturnValue;          // 0x0053(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_BooleanAND_ReturnValue;                   // 0x0054(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_55[0x3];                                       // 0x0055(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class UUserWidget*                            CallFunc_GetWidget_ReturnValue;                    // 0x0058(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UWBP_WatchApp_Simple_C*                 K2Node_DynamicCast_AsWBP_Watch_App_Simple;         // 0x0060(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_1;                     // 0x0068(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_69[0x3];                                       // 0x0069(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         CallFunc_SelectFloat_ReturnValue;                  // 0x006C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AGBCharacter*                           CallFunc_GetGBInstigator_ReturnValue;              // 0x0070(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FGameplayTag                           Temp_struct_Variable;                              // 0x0078(0x0008)(NoDestructor, HasGetValueTypeHash)
	TScriptInterface<class IGameplayTagAssetInterface> CallFunc_HasMatchingGameplayTag_self_CastInput; // 0x0080(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_HasMatchingGameplayTag_ReturnValue;       // 0x0090(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_91[0x3];                                       // 0x0091(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FGameplayTag                           Temp_struct_Variable_1;                            // 0x0094(0x0008)(NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Variable;                                // 0x009C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_9D[0x3];                                       // 0x009D(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class AGBCharacter*                           CallFunc_GetGBInstigator_ReturnValue_1;            // 0x00A0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FGameplayTag                           K2Node_Select_Default;                             // 0x00A8(0x0008)(NoDestructor, HasGetValueTypeHash)
	TSoftObjectPtr<class UTexture2D>              CallFunc_GetIcon_ReturnValue;                      // 0x00B0(0x0028)(UObjectWrapper, HasGetValueTypeHash)
	class UWBP_RadialMenu_Entry_C*                CallFunc_Create_ReturnValue;                       // 0x00D8(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TDelegate<void(int32 Index)>                  K2Node_CreateDelegate_OutputDelegate_1;            // 0x00E0(0x0010)(ZeroConstructor, NoDestructor)
	class AGBCharacter*                           K2Node_Event_Character;                            // 0x00F0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AGBCharacter*                           CallFunc_GetGBInstigator_ReturnValue_2;            // 0x00F8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AGBCharacter*                           CallFunc_GetGBInstigator_ReturnValue_3;            // 0x0100(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_BP_AttachItemTo_ReturnValue;              // 0x0108(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_109[0x7];                                      // 0x0109(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class AGBCharacter*                           CallFunc_GetGBInstigator_ReturnValue_4;            // 0x0110(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AGBCharacter*                           CallFunc_GetGBInstigator_ReturnValue_5;            // 0x0118(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AGBCharacter*                           CallFunc_GetGBInstigator_ReturnValue_6;            // 0x0120(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsUICharacter_ReturnValue;                // 0x0128(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_129[0x7];                                      // 0x0129(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class AGBPlayerState*                         K2Node_DynamicCast_AsGBPlayer_State;               // 0x0130(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_2;                     // 0x0138(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_Not_PreBool_ReturnValue;                  // 0x0139(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x013A(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_13B[0x1];                                      // 0x013B(0x0001)(Fixing Size After Last Property [ Dumper-7 ])
	TDelegate<void(class AGBPlayerState* GBPlayerState)> K2Node_CreateDelegate_OutputDelegate_2;     // 0x013C(0x0010)(ZeroConstructor, NoDestructor)
	uint8                                         Pad_14C[0x4];                                      // 0x014C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class AGBCharacter*                           CallFunc_GetGBInstigator_ReturnValue_7;            // 0x0150(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsAlive_ReturnValue;                      // 0x0158(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_Not_PreBool_ReturnValue_1;                // 0x0159(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_15A[0x2];                                      // 0x015A(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	TDelegate<void(class APlayerController* PlayerController, class AGBCharacter* Character)> K2Node_CreateDelegate_OutputDelegate_3; // 0x015C(0x0010)(ZeroConstructor, NoDestructor)
	uint8                                         Pad_16C[0x4];                                      // 0x016C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UUserWidget*                            K2Node_Event_UsageMenu;                            // 0x0170(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TDelegate<void(class APlayerController* PlayerController, class AGBCharacter* Character)> K2Node_CreateDelegate_OutputDelegate_4; // 0x0178(0x0010)(ZeroConstructor, NoDestructor)
	class UWBP_RadialMenu_C*                      K2Node_DynamicCast_AsWBP_Radial_Menu;              // 0x0188(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_3;                     // 0x0190(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_191[0x3];                                      // 0x0191(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         K2Node_CustomEvent_Index;                          // 0x0194(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UClass*                                 Temp_class_Variable;                               // 0x0198(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UClass*                                 K2Node_ClassDynamicCast_AsWBP_Watch_App;           // 0x01A0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_ClassDynamicCast_bSuccess;                  // 0x01A8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_1A9[0x7];                                      // 0x01A9(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UWBP_WatchApp_C*                        CallFunc_Create_ReturnValue_1;                     // 0x01B0(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_WristWatch_Modular_C_ExecuteUbergraph_BP_WristWatch_Modular) == 0x000008, "Wrong alignment on BP_WristWatch_Modular_C_ExecuteUbergraph_BP_WristWatch_Modular");
static_assert(sizeof(BP_WristWatch_Modular_C_ExecuteUbergraph_BP_WristWatch_Modular) == 0x0001B8, "Wrong size on BP_WristWatch_Modular_C_ExecuteUbergraph_BP_WristWatch_Modular");
static_assert(offsetof(BP_WristWatch_Modular_C_ExecuteUbergraph_BP_WristWatch_Modular, EntryPoint) == 0x000000, "Member 'BP_WristWatch_Modular_C_ExecuteUbergraph_BP_WristWatch_Modular::EntryPoint' has a wrong offset!");
static_assert(offsetof(BP_WristWatch_Modular_C_ExecuteUbergraph_BP_WristWatch_Modular, K2Node_CustomEvent_Loaded) == 0x000008, "Member 'BP_WristWatch_Modular_C_ExecuteUbergraph_BP_WristWatch_Modular::K2Node_CustomEvent_Loaded' has a wrong offset!");
static_assert(offsetof(BP_WristWatch_Modular_C_ExecuteUbergraph_BP_WristWatch_Modular, K2Node_CustomEvent_PlayerController_1) == 0x000010, "Member 'BP_WristWatch_Modular_C_ExecuteUbergraph_BP_WristWatch_Modular::K2Node_CustomEvent_PlayerController_1' has a wrong offset!");
static_assert(offsetof(BP_WristWatch_Modular_C_ExecuteUbergraph_BP_WristWatch_Modular, K2Node_CustomEvent_Character_1) == 0x000018, "Member 'BP_WristWatch_Modular_C_ExecuteUbergraph_BP_WristWatch_Modular::K2Node_CustomEvent_Character_1' has a wrong offset!");
static_assert(offsetof(BP_WristWatch_Modular_C_ExecuteUbergraph_BP_WristWatch_Modular, K2Node_CustomEvent_PlayerController) == 0x000020, "Member 'BP_WristWatch_Modular_C_ExecuteUbergraph_BP_WristWatch_Modular::K2Node_CustomEvent_PlayerController' has a wrong offset!");
static_assert(offsetof(BP_WristWatch_Modular_C_ExecuteUbergraph_BP_WristWatch_Modular, K2Node_CustomEvent_Character) == 0x000028, "Member 'BP_WristWatch_Modular_C_ExecuteUbergraph_BP_WristWatch_Modular::K2Node_CustomEvent_Character' has a wrong offset!");
static_assert(offsetof(BP_WristWatch_Modular_C_ExecuteUbergraph_BP_WristWatch_Modular, K2Node_CustomEvent_GBPlayerState) == 0x000030, "Member 'BP_WristWatch_Modular_C_ExecuteUbergraph_BP_WristWatch_Modular::K2Node_CustomEvent_GBPlayerState' has a wrong offset!");
static_assert(offsetof(BP_WristWatch_Modular_C_ExecuteUbergraph_BP_WristWatch_Modular, K2Node_CreateDelegate_OutputDelegate) == 0x000038, "Member 'BP_WristWatch_Modular_C_ExecuteUbergraph_BP_WristWatch_Modular::K2Node_CreateDelegate_OutputDelegate' has a wrong offset!");
static_assert(offsetof(BP_WristWatch_Modular_C_ExecuteUbergraph_BP_WristWatch_Modular, K2Node_DynamicCast_AsGBCharacter) == 0x000048, "Member 'BP_WristWatch_Modular_C_ExecuteUbergraph_BP_WristWatch_Modular::K2Node_DynamicCast_AsGBCharacter' has a wrong offset!");
static_assert(offsetof(BP_WristWatch_Modular_C_ExecuteUbergraph_BP_WristWatch_Modular, K2Node_DynamicCast_bSuccess) == 0x000050, "Member 'BP_WristWatch_Modular_C_ExecuteUbergraph_BP_WristWatch_Modular::K2Node_DynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(BP_WristWatch_Modular_C_ExecuteUbergraph_BP_WristWatch_Modular, CallFunc_IsLocallyViewed_ReturnValue) == 0x000051, "Member 'BP_WristWatch_Modular_C_ExecuteUbergraph_BP_WristWatch_Modular::CallFunc_IsLocallyViewed_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_WristWatch_Modular_C_ExecuteUbergraph_BP_WristWatch_Modular, CallFunc_IsPlayerControlled_ReturnValue) == 0x000052, "Member 'BP_WristWatch_Modular_C_ExecuteUbergraph_BP_WristWatch_Modular::CallFunc_IsPlayerControlled_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_WristWatch_Modular_C_ExecuteUbergraph_BP_WristWatch_Modular, CallFunc_IsLocallyControlled_ReturnValue) == 0x000053, "Member 'BP_WristWatch_Modular_C_ExecuteUbergraph_BP_WristWatch_Modular::CallFunc_IsLocallyControlled_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_WristWatch_Modular_C_ExecuteUbergraph_BP_WristWatch_Modular, CallFunc_BooleanAND_ReturnValue) == 0x000054, "Member 'BP_WristWatch_Modular_C_ExecuteUbergraph_BP_WristWatch_Modular::CallFunc_BooleanAND_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_WristWatch_Modular_C_ExecuteUbergraph_BP_WristWatch_Modular, CallFunc_GetWidget_ReturnValue) == 0x000058, "Member 'BP_WristWatch_Modular_C_ExecuteUbergraph_BP_WristWatch_Modular::CallFunc_GetWidget_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_WristWatch_Modular_C_ExecuteUbergraph_BP_WristWatch_Modular, K2Node_DynamicCast_AsWBP_Watch_App_Simple) == 0x000060, "Member 'BP_WristWatch_Modular_C_ExecuteUbergraph_BP_WristWatch_Modular::K2Node_DynamicCast_AsWBP_Watch_App_Simple' has a wrong offset!");
static_assert(offsetof(BP_WristWatch_Modular_C_ExecuteUbergraph_BP_WristWatch_Modular, K2Node_DynamicCast_bSuccess_1) == 0x000068, "Member 'BP_WristWatch_Modular_C_ExecuteUbergraph_BP_WristWatch_Modular::K2Node_DynamicCast_bSuccess_1' has a wrong offset!");
static_assert(offsetof(BP_WristWatch_Modular_C_ExecuteUbergraph_BP_WristWatch_Modular, CallFunc_SelectFloat_ReturnValue) == 0x00006C, "Member 'BP_WristWatch_Modular_C_ExecuteUbergraph_BP_WristWatch_Modular::CallFunc_SelectFloat_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_WristWatch_Modular_C_ExecuteUbergraph_BP_WristWatch_Modular, CallFunc_GetGBInstigator_ReturnValue) == 0x000070, "Member 'BP_WristWatch_Modular_C_ExecuteUbergraph_BP_WristWatch_Modular::CallFunc_GetGBInstigator_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_WristWatch_Modular_C_ExecuteUbergraph_BP_WristWatch_Modular, Temp_struct_Variable) == 0x000078, "Member 'BP_WristWatch_Modular_C_ExecuteUbergraph_BP_WristWatch_Modular::Temp_struct_Variable' has a wrong offset!");
static_assert(offsetof(BP_WristWatch_Modular_C_ExecuteUbergraph_BP_WristWatch_Modular, CallFunc_HasMatchingGameplayTag_self_CastInput) == 0x000080, "Member 'BP_WristWatch_Modular_C_ExecuteUbergraph_BP_WristWatch_Modular::CallFunc_HasMatchingGameplayTag_self_CastInput' has a wrong offset!");
static_assert(offsetof(BP_WristWatch_Modular_C_ExecuteUbergraph_BP_WristWatch_Modular, CallFunc_HasMatchingGameplayTag_ReturnValue) == 0x000090, "Member 'BP_WristWatch_Modular_C_ExecuteUbergraph_BP_WristWatch_Modular::CallFunc_HasMatchingGameplayTag_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_WristWatch_Modular_C_ExecuteUbergraph_BP_WristWatch_Modular, Temp_struct_Variable_1) == 0x000094, "Member 'BP_WristWatch_Modular_C_ExecuteUbergraph_BP_WristWatch_Modular::Temp_struct_Variable_1' has a wrong offset!");
static_assert(offsetof(BP_WristWatch_Modular_C_ExecuteUbergraph_BP_WristWatch_Modular, Temp_bool_Variable) == 0x00009C, "Member 'BP_WristWatch_Modular_C_ExecuteUbergraph_BP_WristWatch_Modular::Temp_bool_Variable' has a wrong offset!");
static_assert(offsetof(BP_WristWatch_Modular_C_ExecuteUbergraph_BP_WristWatch_Modular, CallFunc_GetGBInstigator_ReturnValue_1) == 0x0000A0, "Member 'BP_WristWatch_Modular_C_ExecuteUbergraph_BP_WristWatch_Modular::CallFunc_GetGBInstigator_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_WristWatch_Modular_C_ExecuteUbergraph_BP_WristWatch_Modular, K2Node_Select_Default) == 0x0000A8, "Member 'BP_WristWatch_Modular_C_ExecuteUbergraph_BP_WristWatch_Modular::K2Node_Select_Default' has a wrong offset!");
static_assert(offsetof(BP_WristWatch_Modular_C_ExecuteUbergraph_BP_WristWatch_Modular, CallFunc_GetIcon_ReturnValue) == 0x0000B0, "Member 'BP_WristWatch_Modular_C_ExecuteUbergraph_BP_WristWatch_Modular::CallFunc_GetIcon_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_WristWatch_Modular_C_ExecuteUbergraph_BP_WristWatch_Modular, CallFunc_Create_ReturnValue) == 0x0000D8, "Member 'BP_WristWatch_Modular_C_ExecuteUbergraph_BP_WristWatch_Modular::CallFunc_Create_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_WristWatch_Modular_C_ExecuteUbergraph_BP_WristWatch_Modular, K2Node_CreateDelegate_OutputDelegate_1) == 0x0000E0, "Member 'BP_WristWatch_Modular_C_ExecuteUbergraph_BP_WristWatch_Modular::K2Node_CreateDelegate_OutputDelegate_1' has a wrong offset!");
static_assert(offsetof(BP_WristWatch_Modular_C_ExecuteUbergraph_BP_WristWatch_Modular, K2Node_Event_Character) == 0x0000F0, "Member 'BP_WristWatch_Modular_C_ExecuteUbergraph_BP_WristWatch_Modular::K2Node_Event_Character' has a wrong offset!");
static_assert(offsetof(BP_WristWatch_Modular_C_ExecuteUbergraph_BP_WristWatch_Modular, CallFunc_GetGBInstigator_ReturnValue_2) == 0x0000F8, "Member 'BP_WristWatch_Modular_C_ExecuteUbergraph_BP_WristWatch_Modular::CallFunc_GetGBInstigator_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(BP_WristWatch_Modular_C_ExecuteUbergraph_BP_WristWatch_Modular, CallFunc_GetGBInstigator_ReturnValue_3) == 0x000100, "Member 'BP_WristWatch_Modular_C_ExecuteUbergraph_BP_WristWatch_Modular::CallFunc_GetGBInstigator_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(BP_WristWatch_Modular_C_ExecuteUbergraph_BP_WristWatch_Modular, CallFunc_BP_AttachItemTo_ReturnValue) == 0x000108, "Member 'BP_WristWatch_Modular_C_ExecuteUbergraph_BP_WristWatch_Modular::CallFunc_BP_AttachItemTo_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_WristWatch_Modular_C_ExecuteUbergraph_BP_WristWatch_Modular, CallFunc_GetGBInstigator_ReturnValue_4) == 0x000110, "Member 'BP_WristWatch_Modular_C_ExecuteUbergraph_BP_WristWatch_Modular::CallFunc_GetGBInstigator_ReturnValue_4' has a wrong offset!");
static_assert(offsetof(BP_WristWatch_Modular_C_ExecuteUbergraph_BP_WristWatch_Modular, CallFunc_GetGBInstigator_ReturnValue_5) == 0x000118, "Member 'BP_WristWatch_Modular_C_ExecuteUbergraph_BP_WristWatch_Modular::CallFunc_GetGBInstigator_ReturnValue_5' has a wrong offset!");
static_assert(offsetof(BP_WristWatch_Modular_C_ExecuteUbergraph_BP_WristWatch_Modular, CallFunc_GetGBInstigator_ReturnValue_6) == 0x000120, "Member 'BP_WristWatch_Modular_C_ExecuteUbergraph_BP_WristWatch_Modular::CallFunc_GetGBInstigator_ReturnValue_6' has a wrong offset!");
static_assert(offsetof(BP_WristWatch_Modular_C_ExecuteUbergraph_BP_WristWatch_Modular, CallFunc_IsUICharacter_ReturnValue) == 0x000128, "Member 'BP_WristWatch_Modular_C_ExecuteUbergraph_BP_WristWatch_Modular::CallFunc_IsUICharacter_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_WristWatch_Modular_C_ExecuteUbergraph_BP_WristWatch_Modular, K2Node_DynamicCast_AsGBPlayer_State) == 0x000130, "Member 'BP_WristWatch_Modular_C_ExecuteUbergraph_BP_WristWatch_Modular::K2Node_DynamicCast_AsGBPlayer_State' has a wrong offset!");
static_assert(offsetof(BP_WristWatch_Modular_C_ExecuteUbergraph_BP_WristWatch_Modular, K2Node_DynamicCast_bSuccess_2) == 0x000138, "Member 'BP_WristWatch_Modular_C_ExecuteUbergraph_BP_WristWatch_Modular::K2Node_DynamicCast_bSuccess_2' has a wrong offset!");
static_assert(offsetof(BP_WristWatch_Modular_C_ExecuteUbergraph_BP_WristWatch_Modular, CallFunc_Not_PreBool_ReturnValue) == 0x000139, "Member 'BP_WristWatch_Modular_C_ExecuteUbergraph_BP_WristWatch_Modular::CallFunc_Not_PreBool_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_WristWatch_Modular_C_ExecuteUbergraph_BP_WristWatch_Modular, CallFunc_IsValid_ReturnValue) == 0x00013A, "Member 'BP_WristWatch_Modular_C_ExecuteUbergraph_BP_WristWatch_Modular::CallFunc_IsValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_WristWatch_Modular_C_ExecuteUbergraph_BP_WristWatch_Modular, K2Node_CreateDelegate_OutputDelegate_2) == 0x00013C, "Member 'BP_WristWatch_Modular_C_ExecuteUbergraph_BP_WristWatch_Modular::K2Node_CreateDelegate_OutputDelegate_2' has a wrong offset!");
static_assert(offsetof(BP_WristWatch_Modular_C_ExecuteUbergraph_BP_WristWatch_Modular, CallFunc_GetGBInstigator_ReturnValue_7) == 0x000150, "Member 'BP_WristWatch_Modular_C_ExecuteUbergraph_BP_WristWatch_Modular::CallFunc_GetGBInstigator_ReturnValue_7' has a wrong offset!");
static_assert(offsetof(BP_WristWatch_Modular_C_ExecuteUbergraph_BP_WristWatch_Modular, CallFunc_IsAlive_ReturnValue) == 0x000158, "Member 'BP_WristWatch_Modular_C_ExecuteUbergraph_BP_WristWatch_Modular::CallFunc_IsAlive_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_WristWatch_Modular_C_ExecuteUbergraph_BP_WristWatch_Modular, CallFunc_Not_PreBool_ReturnValue_1) == 0x000159, "Member 'BP_WristWatch_Modular_C_ExecuteUbergraph_BP_WristWatch_Modular::CallFunc_Not_PreBool_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_WristWatch_Modular_C_ExecuteUbergraph_BP_WristWatch_Modular, K2Node_CreateDelegate_OutputDelegate_3) == 0x00015C, "Member 'BP_WristWatch_Modular_C_ExecuteUbergraph_BP_WristWatch_Modular::K2Node_CreateDelegate_OutputDelegate_3' has a wrong offset!");
static_assert(offsetof(BP_WristWatch_Modular_C_ExecuteUbergraph_BP_WristWatch_Modular, K2Node_Event_UsageMenu) == 0x000170, "Member 'BP_WristWatch_Modular_C_ExecuteUbergraph_BP_WristWatch_Modular::K2Node_Event_UsageMenu' has a wrong offset!");
static_assert(offsetof(BP_WristWatch_Modular_C_ExecuteUbergraph_BP_WristWatch_Modular, K2Node_CreateDelegate_OutputDelegate_4) == 0x000178, "Member 'BP_WristWatch_Modular_C_ExecuteUbergraph_BP_WristWatch_Modular::K2Node_CreateDelegate_OutputDelegate_4' has a wrong offset!");
static_assert(offsetof(BP_WristWatch_Modular_C_ExecuteUbergraph_BP_WristWatch_Modular, K2Node_DynamicCast_AsWBP_Radial_Menu) == 0x000188, "Member 'BP_WristWatch_Modular_C_ExecuteUbergraph_BP_WristWatch_Modular::K2Node_DynamicCast_AsWBP_Radial_Menu' has a wrong offset!");
static_assert(offsetof(BP_WristWatch_Modular_C_ExecuteUbergraph_BP_WristWatch_Modular, K2Node_DynamicCast_bSuccess_3) == 0x000190, "Member 'BP_WristWatch_Modular_C_ExecuteUbergraph_BP_WristWatch_Modular::K2Node_DynamicCast_bSuccess_3' has a wrong offset!");
static_assert(offsetof(BP_WristWatch_Modular_C_ExecuteUbergraph_BP_WristWatch_Modular, K2Node_CustomEvent_Index) == 0x000194, "Member 'BP_WristWatch_Modular_C_ExecuteUbergraph_BP_WristWatch_Modular::K2Node_CustomEvent_Index' has a wrong offset!");
static_assert(offsetof(BP_WristWatch_Modular_C_ExecuteUbergraph_BP_WristWatch_Modular, Temp_class_Variable) == 0x000198, "Member 'BP_WristWatch_Modular_C_ExecuteUbergraph_BP_WristWatch_Modular::Temp_class_Variable' has a wrong offset!");
static_assert(offsetof(BP_WristWatch_Modular_C_ExecuteUbergraph_BP_WristWatch_Modular, K2Node_ClassDynamicCast_AsWBP_Watch_App) == 0x0001A0, "Member 'BP_WristWatch_Modular_C_ExecuteUbergraph_BP_WristWatch_Modular::K2Node_ClassDynamicCast_AsWBP_Watch_App' has a wrong offset!");
static_assert(offsetof(BP_WristWatch_Modular_C_ExecuteUbergraph_BP_WristWatch_Modular, K2Node_ClassDynamicCast_bSuccess) == 0x0001A8, "Member 'BP_WristWatch_Modular_C_ExecuteUbergraph_BP_WristWatch_Modular::K2Node_ClassDynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(BP_WristWatch_Modular_C_ExecuteUbergraph_BP_WristWatch_Modular, CallFunc_Create_ReturnValue_1) == 0x0001B0, "Member 'BP_WristWatch_Modular_C_ExecuteUbergraph_BP_WristWatch_Modular::CallFunc_Create_ReturnValue_1' has a wrong offset!");

// Function BP_WristWatch_Modular.BP_WristWatch_Modular_C.OnSelected_Watch_Event
// 0x0004 (0x0004 - 0x0000)
struct BP_WristWatch_Modular_C_OnSelected_Watch_Event final
{
public:
	int32                                         Index_0;                                           // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_WristWatch_Modular_C_OnSelected_Watch_Event) == 0x000004, "Wrong alignment on BP_WristWatch_Modular_C_OnSelected_Watch_Event");
static_assert(sizeof(BP_WristWatch_Modular_C_OnSelected_Watch_Event) == 0x000004, "Wrong size on BP_WristWatch_Modular_C_OnSelected_Watch_Event");
static_assert(offsetof(BP_WristWatch_Modular_C_OnSelected_Watch_Event, Index_0) == 0x000000, "Member 'BP_WristWatch_Modular_C_OnSelected_Watch_Event::Index_0' has a wrong offset!");

// Function BP_WristWatch_Modular.BP_WristWatch_Modular_C.AddAttachedUseMenuEntries
// 0x0008 (0x0008 - 0x0000)
struct BP_WristWatch_Modular_C_AddAttachedUseMenuEntries final
{
public:
	class UUserWidget*                            UsageMenu;                                         // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_WristWatch_Modular_C_AddAttachedUseMenuEntries) == 0x000008, "Wrong alignment on BP_WristWatch_Modular_C_AddAttachedUseMenuEntries");
static_assert(sizeof(BP_WristWatch_Modular_C_AddAttachedUseMenuEntries) == 0x000008, "Wrong size on BP_WristWatch_Modular_C_AddAttachedUseMenuEntries");
static_assert(offsetof(BP_WristWatch_Modular_C_AddAttachedUseMenuEntries, UsageMenu) == 0x000000, "Member 'BP_WristWatch_Modular_C_AddAttachedUseMenuEntries::UsageMenu' has a wrong offset!");

// Function BP_WristWatch_Modular.BP_WristWatch_Modular_C.OnAddedToInventoryEvent
// 0x0008 (0x0008 - 0x0000)
struct BP_WristWatch_Modular_C_OnAddedToInventoryEvent final
{
public:
	class AGBCharacter*                           Character;                                         // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_WristWatch_Modular_C_OnAddedToInventoryEvent) == 0x000008, "Wrong alignment on BP_WristWatch_Modular_C_OnAddedToInventoryEvent");
static_assert(sizeof(BP_WristWatch_Modular_C_OnAddedToInventoryEvent) == 0x000008, "Wrong size on BP_WristWatch_Modular_C_OnAddedToInventoryEvent");
static_assert(offsetof(BP_WristWatch_Modular_C_OnAddedToInventoryEvent, Character) == 0x000000, "Member 'BP_WristWatch_Modular_C_OnAddedToInventoryEvent::Character' has a wrong offset!");

// Function BP_WristWatch_Modular.BP_WristWatch_Modular_C.OnReceivePlayerState_Event_0
// 0x0008 (0x0008 - 0x0000)
struct BP_WristWatch_Modular_C_OnReceivePlayerState_Event_0 final
{
public:
	class AGBPlayerState*                         GBPlayerState;                                     // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_WristWatch_Modular_C_OnReceivePlayerState_Event_0) == 0x000008, "Wrong alignment on BP_WristWatch_Modular_C_OnReceivePlayerState_Event_0");
static_assert(sizeof(BP_WristWatch_Modular_C_OnReceivePlayerState_Event_0) == 0x000008, "Wrong size on BP_WristWatch_Modular_C_OnReceivePlayerState_Event_0");
static_assert(offsetof(BP_WristWatch_Modular_C_OnReceivePlayerState_Event_0, GBPlayerState) == 0x000000, "Member 'BP_WristWatch_Modular_C_OnReceivePlayerState_Event_0::GBPlayerState' has a wrong offset!");

// Function BP_WristWatch_Modular.BP_WristWatch_Modular_C.OnEndViewTarget_Event_0
// 0x0010 (0x0010 - 0x0000)
struct BP_WristWatch_Modular_C_OnEndViewTarget_Event_0 final
{
public:
	class APlayerController*                      PlayerController;                                  // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AGBCharacter*                           Character;                                         // 0x0008(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_WristWatch_Modular_C_OnEndViewTarget_Event_0) == 0x000008, "Wrong alignment on BP_WristWatch_Modular_C_OnEndViewTarget_Event_0");
static_assert(sizeof(BP_WristWatch_Modular_C_OnEndViewTarget_Event_0) == 0x000010, "Wrong size on BP_WristWatch_Modular_C_OnEndViewTarget_Event_0");
static_assert(offsetof(BP_WristWatch_Modular_C_OnEndViewTarget_Event_0, PlayerController) == 0x000000, "Member 'BP_WristWatch_Modular_C_OnEndViewTarget_Event_0::PlayerController' has a wrong offset!");
static_assert(offsetof(BP_WristWatch_Modular_C_OnEndViewTarget_Event_0, Character) == 0x000008, "Member 'BP_WristWatch_Modular_C_OnEndViewTarget_Event_0::Character' has a wrong offset!");

// Function BP_WristWatch_Modular.BP_WristWatch_Modular_C.OnBecomeViewTarget_Event_0
// 0x0010 (0x0010 - 0x0000)
struct BP_WristWatch_Modular_C_OnBecomeViewTarget_Event_0 final
{
public:
	class APlayerController*                      PlayerController;                                  // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AGBCharacter*                           Character;                                         // 0x0008(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_WristWatch_Modular_C_OnBecomeViewTarget_Event_0) == 0x000008, "Wrong alignment on BP_WristWatch_Modular_C_OnBecomeViewTarget_Event_0");
static_assert(sizeof(BP_WristWatch_Modular_C_OnBecomeViewTarget_Event_0) == 0x000010, "Wrong size on BP_WristWatch_Modular_C_OnBecomeViewTarget_Event_0");
static_assert(offsetof(BP_WristWatch_Modular_C_OnBecomeViewTarget_Event_0, PlayerController) == 0x000000, "Member 'BP_WristWatch_Modular_C_OnBecomeViewTarget_Event_0::PlayerController' has a wrong offset!");
static_assert(offsetof(BP_WristWatch_Modular_C_OnBecomeViewTarget_Event_0, Character) == 0x000008, "Member 'BP_WristWatch_Modular_C_OnBecomeViewTarget_Event_0::Character' has a wrong offset!");

// Function BP_WristWatch_Modular.BP_WristWatch_Modular_C.OnLoaded_ACB25BB1431690D222BD5B836B55DB38
// 0x0008 (0x0008 - 0x0000)
struct BP_WristWatch_Modular_C_OnLoaded_ACB25BB1431690D222BD5B836B55DB38 final
{
public:
	TSubclassOf<class UObject>                    Loaded;                                            // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, UObjectWrapper, HasGetValueTypeHash)
};
static_assert(alignof(BP_WristWatch_Modular_C_OnLoaded_ACB25BB1431690D222BD5B836B55DB38) == 0x000008, "Wrong alignment on BP_WristWatch_Modular_C_OnLoaded_ACB25BB1431690D222BD5B836B55DB38");
static_assert(sizeof(BP_WristWatch_Modular_C_OnLoaded_ACB25BB1431690D222BD5B836B55DB38) == 0x000008, "Wrong size on BP_WristWatch_Modular_C_OnLoaded_ACB25BB1431690D222BD5B836B55DB38");
static_assert(offsetof(BP_WristWatch_Modular_C_OnLoaded_ACB25BB1431690D222BD5B836B55DB38, Loaded) == 0x000000, "Member 'BP_WristWatch_Modular_C_OnLoaded_ACB25BB1431690D222BD5B836B55DB38::Loaded' has a wrong offset!");

// Function BP_WristWatch_Modular.BP_WristWatch_Modular_C.AllowUsageWhileAttached
// 0x0001 (0x0001 - 0x0000)
struct BP_WristWatch_Modular_C_AllowUsageWhileAttached final
{
public:
	bool                                          ReturnValue;                                       // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor)
};
static_assert(alignof(BP_WristWatch_Modular_C_AllowUsageWhileAttached) == 0x000001, "Wrong alignment on BP_WristWatch_Modular_C_AllowUsageWhileAttached");
static_assert(sizeof(BP_WristWatch_Modular_C_AllowUsageWhileAttached) == 0x000001, "Wrong size on BP_WristWatch_Modular_C_AllowUsageWhileAttached");
static_assert(offsetof(BP_WristWatch_Modular_C_AllowUsageWhileAttached, ReturnValue) == 0x000000, "Member 'BP_WristWatch_Modular_C_AllowUsageWhileAttached::ReturnValue' has a wrong offset!");

}

