#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Zenitco_Grip

#include "Basic.hpp"

#include "BP_Foregrip_Master_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_Zenitco_Grip.BP_Zenitco_Grip_C
// 0x0008 (0x04B0 - 0x04A8)
class ABP_Zenitco_Grip_C final : public ABP_Foregrip_Master_C
{
public:
	class UStaticMeshComponent*                   TDStubby_VertGrip;                                 // 0x04A8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_Zenitco_Grip_C">();
	}
	static class ABP_Zenitco_Grip_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_Zenitco_Grip_C>();
	}
};
static_assert(alignof(ABP_Zenitco_Grip_C) == 0x000008, "Wrong alignment on ABP_Zenitco_Grip_C");
static_assert(sizeof(ABP_Zenitco_Grip_C) == 0x0004B0, "Wrong size on ABP_Zenitco_Grip_C");
static_assert(offsetof(ABP_Zenitco_Grip_C, TDStubby_VertGrip) == 0x0004A8, "Member 'ABP_Zenitco_Grip_C::TDStubby_VertGrip' has a wrong offset!");

}

