#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BT_GB_Ky_PlayCheckBody

#include "Basic.hpp"

#include "BT_GB_Ky_PlayCheckBody_classes.hpp"
#include "BT_GB_Ky_PlayCheckBody_parameters.hpp"


namespace SDK
{

// Function BT_GB_Ky_PlayCheckBody.BT_GB_Ky_PlayCheckBody_C.ExecuteUbergraph_BT_GB_Ky_PlayCheckBody
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBT_GB_Ky_PlayCheckBody_C::ExecuteUbergraph_BT_GB_Ky_PlayCheckBody(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BT_GB_Ky_PlayCheckBody_C", "ExecuteUbergraph_BT_GB_Ky_PlayCheckBody");

	Params::BT_GB_Ky_PlayCheckBody_C_ExecuteUbergraph_BT_GB_Ky_PlayCheckBody Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BT_GB_Ky_PlayCheckBody.BT_GB_Ky_PlayCheckBody_C.DoCleanup
// (Event, Public, BlueprintEvent)
// Parameters:
// class AKytController*                   Controller                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UKytBlackboard*                   BehaviorBlackboard                                     (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBT_GB_Ky_PlayCheckBody_C::DoCleanup(class AKytController* Controller, class UKytBlackboard* BehaviorBlackboard)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BT_GB_Ky_PlayCheckBody_C", "DoCleanup");

	Params::BT_GB_Ky_PlayCheckBody_C_DoCleanup Parms{};

	Parms.Controller = Controller;
	Parms.BehaviorBlackboard = BehaviorBlackboard;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BT_GB_Ky_PlayCheckBody.BT_GB_Ky_PlayCheckBody_C.WaitCompletion
// (BlueprintCallable, BlueprintEvent)

void UBT_GB_Ky_PlayCheckBody_C::WaitCompletion()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BT_GB_Ky_PlayCheckBody_C", "WaitCompletion");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BT_GB_Ky_PlayCheckBody.BT_GB_Ky_PlayCheckBody_C.Removed_69B7507A4FB5EFDD259517894E34B3AB
// (BlueprintCallable, BlueprintEvent)

void UBT_GB_Ky_PlayCheckBody_C::Removed_69B7507A4FB5EFDD259517894E34B3AB()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BT_GB_Ky_PlayCheckBody_C", "Removed_69B7507A4FB5EFDD259517894E34B3AB");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BT_GB_Ky_PlayCheckBody.BT_GB_Ky_PlayCheckBody_C.DoEnter
// (Event, Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// class AKytController*                   Controller                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UKytBlackboard*                   BehaviorBlackboard                                     (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// EKytBTEnterResult                       ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

EKytBTEnterResult UBT_GB_Ky_PlayCheckBody_C::DoEnter(class AKytController* Controller, class UKytBlackboard* BehaviorBlackboard)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BT_GB_Ky_PlayCheckBody_C", "DoEnter");

	Params::BT_GB_Ky_PlayCheckBody_C_DoEnter Parms{};

	Parms.Controller = Controller;
	Parms.BehaviorBlackboard = BehaviorBlackboard;

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function BT_GB_Ky_PlayCheckBody.BT_GB_Ky_PlayCheckBody_C.DoUpdate
// (Event, Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// class AKytController*                   Controller                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UKytBlackboard*                   BehaviorBlackboard                                     (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// EKytBTUpdateResult                      ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

EKytBTUpdateResult UBT_GB_Ky_PlayCheckBody_C::DoUpdate(class AKytController* Controller, class UKytBlackboard* BehaviorBlackboard)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BT_GB_Ky_PlayCheckBody_C", "DoUpdate");

	Params::BT_GB_Ky_PlayCheckBody_C_DoUpdate Parms{};

	Parms.Controller = Controller;
	Parms.BehaviorBlackboard = BehaviorBlackboard;

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}

}

