#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GA_Emote

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "GroundBranch_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GA_Emote.GA_Emote_C
// 0x0008 (0x03C0 - 0x03B8)
class UGA_Emote_C final : public UGBGameplayAbility
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x03B8(0x0008)(ZeroConstructor, Transient, DuplicateTransient)

public:
	void ExecuteUbergraph_GA_Emote(int32 EntryPoint);
	void K2_ActivateAbilityFromEvent(const struct FGameplayEventData& EventData);
	void OnCompleted_CE2E4E412CCD4431B8AB53B0F0BC0BCD();
	void OnBlendOut_CE2E4E412CCD4431B8AB53B0F0BC0BCD();
	void OnInterrupted_CE2E4E412CCD4431B8AB53B0F0BC0BCD();
	void OnCancelled_CE2E4E412CCD4431B8AB53B0F0BC0BCD();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"GA_Emote_C">();
	}
	static class UGA_Emote_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGA_Emote_C>();
	}
};
static_assert(alignof(UGA_Emote_C) == 0x000008, "Wrong alignment on UGA_Emote_C");
static_assert(sizeof(UGA_Emote_C) == 0x0003C0, "Wrong size on UGA_Emote_C");
static_assert(offsetof(UGA_Emote_C, UberGraphFrame) == 0x0003B8, "Member 'UGA_Emote_C::UberGraphFrame' has a wrong offset!");

}

