#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GA_Galil_Reload

#include "Basic.hpp"

#include "GA_Reload_ExternalMag_Master_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GA_Galil_Reload.GA_Galil_Reload_C
// 0x0000 (0x0530 - 0x0530)
class UGA_Galil_Reload_C final : public UGA_Reload_ExternalMag_Master_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"GA_Galil_Reload_C">();
	}
	static class UGA_Galil_Reload_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGA_Galil_Reload_C>();
	}
};
static_assert(alignof(UGA_Galil_Reload_C) == 0x000010, "Wrong alignment on UGA_Galil_Reload_C");
static_assert(sizeof(UGA_Galil_Reload_C) == 0x000530, "Wrong size on UGA_Galil_Reload_C");

}

