#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GA_HandSignal_Master

#include "Basic.hpp"

#include "GA_HandSignal_Master_classes.hpp"
#include "GA_HandSignal_Master_parameters.hpp"


namespace SDK
{

// Function GA_HandSignal_Master.GA_HandSignal_Master_C.ExecuteUbergraph_GA_HandSignal_Master
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UGA_HandSignal_Master_C::ExecuteUbergraph_GA_HandSignal_Master(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_HandSignal_Master_C", "ExecuteUbergraph_GA_HandSignal_Master");

	Params::GA_HandSignal_Master_C_ExecuteUbergraph_GA_HandSignal_Master Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function GA_HandSignal_Master.GA_HandSignal_Master_C.EndEvent
// (BlueprintCallable, BlueprintEvent)

void UGA_HandSignal_Master_C::EndEvent()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_HandSignal_Master_C", "EndEvent");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_HandSignal_Master.GA_HandSignal_Master_C.BeginEvent
// (BlueprintCallable, BlueprintEvent)

void UGA_HandSignal_Master_C::BeginEvent()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_HandSignal_Master_C", "BeginEvent");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_HandSignal_Master.GA_HandSignal_Master_C.WaitForHandSignalEvents
// (BlueprintCallable, BlueprintEvent)

void UGA_HandSignal_Master_C::WaitForHandSignalEvents()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_HandSignal_Master_C", "WaitForHandSignalEvents");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_HandSignal_Master.GA_HandSignal_Master_C.K2_ActivateAbilityFromEvent
// (Event, Protected, HasOutParams, BlueprintEvent)
// Parameters:
// const struct FGameplayEventData&        EventData                                              (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)

void UGA_HandSignal_Master_C::K2_ActivateAbilityFromEvent(const struct FGameplayEventData& EventData)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_HandSignal_Master_C", "K2_ActivateAbilityFromEvent");

	Params::GA_HandSignal_Master_C_K2_ActivateAbilityFromEvent Parms{};

	Parms.EventData = std::move(EventData);

	UObject::ProcessEvent(Func, &Parms);
}


// Function GA_HandSignal_Master.GA_HandSignal_Master_C.EventReceived_73D21BAD067147E1A5C50BAF867829CE
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FGameplayEventData&        Payload                                                (BlueprintVisible, BlueprintReadOnly, Parm)

void UGA_HandSignal_Master_C::EventReceived_73D21BAD067147E1A5C50BAF867829CE(const struct FGameplayEventData& Payload)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_HandSignal_Master_C", "EventReceived_73D21BAD067147E1A5C50BAF867829CE");

	Params::GA_HandSignal_Master_C_EventReceived_73D21BAD067147E1A5C50BAF867829CE Parms{};

	Parms.Payload = std::move(Payload);

	UObject::ProcessEvent(Func, &Parms);
}


// Function GA_HandSignal_Master.GA_HandSignal_Master_C.EventReceived_96F3887E28054F1B9CD42EE822728198
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FGameplayEventData&        Payload                                                (BlueprintVisible, BlueprintReadOnly, Parm)

void UGA_HandSignal_Master_C::EventReceived_96F3887E28054F1B9CD42EE822728198(const struct FGameplayEventData& Payload)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_HandSignal_Master_C", "EventReceived_96F3887E28054F1B9CD42EE822728198");

	Params::GA_HandSignal_Master_C_EventReceived_96F3887E28054F1B9CD42EE822728198 Parms{};

	Parms.Payload = std::move(Payload);

	UObject::ProcessEvent(Func, &Parms);
}


// Function GA_HandSignal_Master.GA_HandSignal_Master_C.OnCompleted_196ED3A76F0845829C7413EEB47D4E5A
// (BlueprintCallable, BlueprintEvent)

void UGA_HandSignal_Master_C::OnCompleted_196ED3A76F0845829C7413EEB47D4E5A()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_HandSignal_Master_C", "OnCompleted_196ED3A76F0845829C7413EEB47D4E5A");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_HandSignal_Master.GA_HandSignal_Master_C.OnBlendOut_196ED3A76F0845829C7413EEB47D4E5A
// (BlueprintCallable, BlueprintEvent)

void UGA_HandSignal_Master_C::OnBlendOut_196ED3A76F0845829C7413EEB47D4E5A()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_HandSignal_Master_C", "OnBlendOut_196ED3A76F0845829C7413EEB47D4E5A");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_HandSignal_Master.GA_HandSignal_Master_C.OnInterrupted_196ED3A76F0845829C7413EEB47D4E5A
// (BlueprintCallable, BlueprintEvent)

void UGA_HandSignal_Master_C::OnInterrupted_196ED3A76F0845829C7413EEB47D4E5A()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_HandSignal_Master_C", "OnInterrupted_196ED3A76F0845829C7413EEB47D4E5A");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_HandSignal_Master.GA_HandSignal_Master_C.OnCancelled_196ED3A76F0845829C7413EEB47D4E5A
// (BlueprintCallable, BlueprintEvent)

void UGA_HandSignal_Master_C::OnCancelled_196ED3A76F0845829C7413EEB47D4E5A()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_HandSignal_Master_C", "OnCancelled_196ED3A76F0845829C7413EEB47D4E5A");

	UObject::ProcessEvent(Func, nullptr);
}

}

