#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GA_HandSignal_Go_There

#include "Basic.hpp"

#include "GA_HandSignal_Master_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GA_HandSignal_Go_There.GA_HandSignal_Go_There_C
// 0x0000 (0x03E8 - 0x03E8)
class UGA_HandSignal_Go_There_C final : public UGA_HandSignal_Master_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"GA_HandSignal_Go_There_C">();
	}
	static class UGA_HandSignal_Go_There_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGA_HandSignal_Go_There_C>();
	}
};
static_assert(alignof(UGA_HandSignal_Go_There_C) == 0x000008, "Wrong alignment on UGA_HandSignal_Go_There_C");
static_assert(sizeof(UGA_HandSignal_Go_There_C) == 0x0003E8, "Wrong size on UGA_HandSignal_Go_There_C");

}

