#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GA_Tablet_FreeLook

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "GroundBranch_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GA_Tablet_FreeLook.GA_Tablet_FreeLook_C
// 0x0008 (0x03C0 - 0x03B8)
class UGA_Tablet_FreeLook_C final : public UGBEquippedGameplayAbility
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x03B8(0x0008)(ZeroConstructor, Transient, DuplicateTransient)

public:
	void ExecuteUbergraph_GA_Tablet_FreeLook(int32 EntryPoint);
	void K2_OnEndAbility(bool bWasCancelled);
	void K2_ActivateAbility();

	bool K2_CanActivateAbility(const struct FGameplayAbilityActorInfo& ActorInfo, const struct FGameplayAbilitySpecHandle& Handle, struct FGameplayTagContainer* RelevantTags) const;

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"GA_Tablet_FreeLook_C">();
	}
	static class UGA_Tablet_FreeLook_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGA_Tablet_FreeLook_C>();
	}
};
static_assert(alignof(UGA_Tablet_FreeLook_C) == 0x000008, "Wrong alignment on UGA_Tablet_FreeLook_C");
static_assert(sizeof(UGA_Tablet_FreeLook_C) == 0x0003C0, "Wrong size on UGA_Tablet_FreeLook_C");
static_assert(offsetof(UGA_Tablet_FreeLook_C, UberGraphFrame) == 0x0003B8, "Member 'UGA_Tablet_FreeLook_C::UberGraphFrame' has a wrong offset!");

}

