#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GA_WristWatch_Input

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "GroundBranch_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GA_WristWatch_Input.GA_WristWatch_Input_C
// 0x0010 (0x03C8 - 0x03B8)
class UGA_WristWatch_Input_C final : public UGBGameplayAbility
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x03B8(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	float                                         InitialInputTime;                                  // 0x03C0(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_GA_WristWatch_Input(int32 EntryPoint);
	void K2_ActivateAbility();
	void OnRelease_EC322D838035465FBAB2BD21352626B6(float TimeHeld);
	void OnPress_C8BFD5C076FF45FDB1430A907F2D3F3D(float TimeWaited);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"GA_WristWatch_Input_C">();
	}
	static class UGA_WristWatch_Input_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGA_WristWatch_Input_C>();
	}
};
static_assert(alignof(UGA_WristWatch_Input_C) == 0x000008, "Wrong alignment on UGA_WristWatch_Input_C");
static_assert(sizeof(UGA_WristWatch_Input_C) == 0x0003C8, "Wrong size on UGA_WristWatch_Input_C");
static_assert(offsetof(UGA_WristWatch_Input_C, UberGraphFrame) == 0x0003B8, "Member 'UGA_WristWatch_Input_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UGA_WristWatch_Input_C, InitialInputTime) == 0x0003C0, "Member 'UGA_WristWatch_Input_C::InitialInputTime' has a wrong offset!");

}

