#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: RIG_SeparateLeftArm_Post

#include "Basic.hpp"

#include "ControlRig_classes.hpp"


namespace SDK
{

// ControlRigBlueprintGeneratedClass RIG_SeparateLeftArm_Post.RIG_SeparateLeftArm_Post_C
// 0x0000 (0x0650 - 0x0650)
class URIG_SeparateLeftArm_Post_C final : public UControlRig
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"RIG_SeparateLeftArm_Post_C">();
	}
	static class URIG_SeparateLeftArm_Post_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<URIG_SeparateLeftArm_Post_C>();
	}
};
static_assert(alignof(URIG_SeparateLeftArm_Post_C) == 0x000008, "Wrong alignment on URIG_SeparateLeftArm_Post_C");
static_assert(sizeof(URIG_SeparateLeftArm_Post_C) == 0x000650, "Wrong size on URIG_SeparateLeftArm_Post_C");

}

