#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_Patch_CallSignWidget

#include "Basic.hpp"

#include "WBP_Patch_CallSignWidget_classes.hpp"
#include "WBP_Patch_CallSignWidget_parameters.hpp"


namespace SDK
{

// Function WBP_Patch_CallSignWidget.WBP_Patch_CallSignWidget_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UWBP_Patch_CallSignWidget_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Patch_CallSignWidget_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_Patch_CallSignWidget.WBP_Patch_CallSignWidget_C.SetCallSignEvent
// (Event, Public, BlueprintEvent)
// Parameters:
// const class FString&                    NewCallSign                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)

void UWBP_Patch_CallSignWidget_C::SetCallSignEvent(const class FString& NewCallSign)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Patch_CallSignWidget_C", "SetCallSignEvent");

	Params::WBP_Patch_CallSignWidget_C_SetCallSignEvent Parms{};

	Parms.NewCallSign = std::move(NewCallSign);

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_Patch_CallSignWidget.WBP_Patch_CallSignWidget_C.ExecuteUbergraph_WBP_Patch_CallSignWidget
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_Patch_CallSignWidget_C::ExecuteUbergraph_WBP_Patch_CallSignWidget(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Patch_CallSignWidget_C", "ExecuteUbergraph_WBP_Patch_CallSignWidget");

	Params::WBP_Patch_CallSignWidget_C_ExecuteUbergraph_WBP_Patch_CallSignWidget Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}

}

